// Cibles RÉELLES « Ascenseur privatif de villa » (INDESCALE).
// 19 cibles FR/CH/BE/LU. Liste figée. Notes denses regroupant positionnement, gamme prix,
// réalisations, signaux marketing. 'n/a' laissé vide (jamais inventé).

let _c = 0
const cid = () => 'lift-' + (++_c)

export const ASCENSEUR_PRIVATIF_PROSPECTS = [
  // ─── PRIORITÉ HAUTE ────────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Ascenseur privatif de villa","entreprise":"Aritco Lift AB (HQ Suède)","ville":"France","zone":"","dirigeant_principal":"Martin Idbrant (CEO groupe Suède)","portable_dirigeant":"","telephone":"+46 8 120 401 00","email":"","email_dirigeant":"","linkedin_dirigeant":"https://www.linkedin.com/company/aritco/","site_web":"https://www.aritco.com/fr","note_priorite":"Haute","source":"fichier ascenseur privatif enrichi","statut":"À contacter","data":{"note":"Leader ascenseur privatif design coloré (HomeLift Aritco Access). Positionnement : design suédois premium villa. Gamme prix : 35-75k€. Réalisations : réseau revendeurs FR + projets villa haut de gamme. Signaux marketing : très bonne présence digitale FR + showcase LinkedIn dédié + design éditorial. France via réseau revendeurs (GPH Mobilité IDF / LTC Access Bretagne / ACDM). HQ : Energivägen 7, 19624 Kungsängen Suède.","sources":"aritco.com | annuaire-entreprises.data.gouv.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Ascenseur privatif de villa","entreprise":"Cibes Lift France","ville":"France","zone":"","dirigeant_principal":"Lars Mathias Brandhammar / Merjin Aldewereld (DG Cibes Lift Group AB)","portable_dirigeant":"","telephone":"03 28 38 50 88","email":"","email_dirigeant":"contact@cibeslift.com","linkedin_dirigeant":"","site_web":"https://cibeslift.com/fr-fr","note_priorite":"Haute","source":"fichier ascenseur privatif enrichi","statut":"À contacter","data":{"note":"🔥 Vrai luxe résidentiel cœur de cible PRODIGIO. Positionnement : Suédois — vrai luxe résidentiel design sur-mesure ascenseur 1m² depuis 1947. Gamme prix : 40-90k€. Réalisations : 70 000+ ascenseurs dans 70 pays — gros pipeline villa CSP+++. Signaux marketing : site multi-pays soigné + LinkedIn actif + magazines déco. Siège : Parc d'Activités Pierre Mauroy 2 rue Pierre-Antoine Delahousse 59223 Roncq. Cibes Group couvre aussi BE/NL via Aesy Liften.","sources":"pappers.fr | cibeslift.com"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Ascenseur privatif de villa","entreprise":"DomusLift (IGV Group Italie)","ville":"France","zone":"","dirigeant_principal":"Marco Cogliati (CEO IGV Group)","portable_dirigeant":"","telephone":"+39 0444 482111","email":"","email_dirigeant":"info@igvgroup.com","linkedin_dirigeant":"","site_web":"https://en.domuslift.com","note_priorite":"Haute","source":"fichier ascenseur privatif enrichi","statut":"À contacter","data":{"note":"Made in Italy — l'ascenseur résidentiel le plus vendu en Europe. Positionnement : haut de gamme italien (XS/Standard/XL). Gamme prix : 30-70k€. Réalisations : villas Côte d'Azur Monaco + IDF. Signaux marketing : site très soigné + réseau distributeurs structuré + présence salons design. France via Still'9 (IDF) + Voltalift/Novak (PACA + Monaco). HQ : Via Della Lova 22, 36077 Altavilla Vicentina Italie.","sources":"domuslift.com"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Ascenseur privatif de villa","entreprise":"Voltalift / Novak SAS","ville":"France","zone":"","dirigeant_principal":"Dirigeant Novak (nom non identifié publiquement)","portable_dirigeant":"","telephone":"04 94 65 22 33","email":"","email_dirigeant":"contact@voltalift.com","linkedin_dirigeant":"","site_web":"https://www.voltalift.com","note_priorite":"Haute","source":"fichier ascenseur privatif enrichi","statut":"À contacter","data":{"note":"🔥 Zone CSP+++ Côte d'Azur idéale pour pitch Mitja-like. Positionnement : distributeur DomusLift PACA depuis 2007 — villas Riviera & Monaco. Gamme prix : 30-70k€. Réalisations : villas Toulon/Saint-Tropez/Sanary/Monaco. Signaux marketing : SEO local fort sur 'ascenseur privatif PACA' — pas d'ads, site fonctionnel. Siège : 196 rue Nicéphore Niepce ZA du Palyvestre 83400 Hyères.","sources":"voltalift.com | verif.com"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Ascenseur privatif de villa","entreprise":"FreedHome","ville":"Belgique","zone":"","dirigeant_principal":"Christophe Desmarez (Fondateur / Directeur)","portable_dirigeant":"","telephone":"065 65 65 22","email":"","email_dirigeant":"info@freedhome.be","linkedin_dirigeant":"https://be.linkedin.com/in/christophe-desmarez-2b9a695b","site_web":"https://www.freedhome.be","note_priorite":"Haute","source":"fichier ascenseur privatif enrichi","statut":"À contacter","data":{"note":"🔥 N°1 ascenseur privatif Belgique + récemment racheté par Geslift (budget marketing à débloquer). Positionnement : multimarques Aritco/Ascendor/AEA. Gamme prix : 30-65k€. Réalisations : villas Wallonie + appartements Bruxelles. Signaux marketing : site soigné + brochure + LinkedIn fondateur actif + presse Construire La Wallonie. Siège : Rue de la Platinerie 10 7340 Colfontaine (Mons). Étendu Namur/Charleroi/Tournai/Waterloo.","sources":"freedhome.be | fb-transmission.com"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Ascenseur privatif de villa","entreprise":"Ascenseurs Menétrey SA","ville":"Suisse","zone":"","dirigeant_principal":"Yvan Menétrey (3e génération) + Gil Menétrey (4e génération)","portable_dirigeant":"","telephone":"026 651 92 92","email":"","email_dirigeant":"info@menetrey-lift.ch","linkedin_dirigeant":"https://ch.linkedin.com/in/gil-menétrey-868568173","site_web":"https://menetrey-lift.ch","note_priorite":"Haute","source":"fichier ascenseur privatif enrichi","statut":"À contacter","data":{"note":"🔥 Plus grand fabricant ascenseur Swiss Made romandie + famille 4 générations (ticket Lac Léman énorme). Positionnement : Swiss Made depuis 1924, 140 employés. Gamme prix : 40-90k CHF. Réalisations : ascenseurs sur-mesure villas Lac Léman + chalets Valais. Signaux marketing : site solide + chaîne YouTube + presse PME magazine + LinkedIn famille. Siège : Route André-Piller 1 1762 Givisiez (+ usine Romont) + agences GE/VD/VS/NE.","sources":"linkedin.com | pme.ch"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Ascenseur privatif de villa","entreprise":"Garaventa Lift (Liftech AG)","ville":"Suisse","zone":"","dirigeant_principal":"Enrico Ghidotti (Head of Sales) — groupe TK Elevator","portable_dirigeant":"","telephone":"041 854 78 80","email":"","email_dirigeant":"info@garaventalift.ch","linkedin_dirigeant":"","site_web":"https://www.garaventalift.ch","note_priorite":"Haute","source":"fichier ascenseur privatif enrichi","statut":"À contacter","data":{"note":"Leader homelift Suisse + racines 1928 Karl Garaventa — 100 000 ascenseurs monde. Positionnement : Genesis Typ B homelift villa intérieur/extérieur. Gamme prix : 40-80k CHF. Réalisations : Genesis Typ B homelift villa intérieur/extérieur. Signaux marketing : site multilingue très pro + showroom virtuel. Siège : Bahnhofstrasse 10 6403 Küssnacht am Rigi (SZ). Antennes romandie via Rigert/réseau.","sources":"garaventalift.ch"}},

  // ─── PRIORITÉ MOYENNE ──────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Ascenseur privatif de villa","entreprise":"Still'9 (distrib DomusLift IDF)","ville":"France","zone":"","dirigeant_principal":"Michel Dubois (Associé-Gérant SARL)","portable_dirigeant":"","telephone":"01 60 86 21 32","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.still9.fr","note_priorite":"Moyenne","source":"fichier ascenseur privatif enrichi","statut":"À contacter","data":{"note":"Distributeur officiel DomusLift IDF depuis 1989 (36 ans). Positionnement : villas IDF + appartements haussmanniens Paris. Gamme prix : 30-60k€. Réalisations : villas IDF + appartements haussmanniens. Signaux marketing : site très daté visuellement (années 2000) — pas d'ads. Marché capté par bouche-à-oreille. Siège : 11 rue Léonard de Vinci 91220 Le Plessis-Pâté.","sources":"societe.com | still9.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Ascenseur privatif de villa","entreprise":"Etna France","ville":"France","zone":"","dirigeant_principal":"ADME France SAS (Président pers. morale depuis 08/2023, ex Vincent Bronze)","portable_dirigeant":"","telephone":"01 30 40 84 84","email":"","email_dirigeant":"contact@etnafrance.com","linkedin_dirigeant":"","site_web":"https://etnafrance.com","note_priorite":"Moyenne","source":"fichier ascenseur privatif enrichi","statut":"À contacter","data":{"note":"Fabricant français Normandie depuis 1986 + Origine France Garantie. Positionnement : gammes Essentiels/Créatifs/Premiums. Gamme prix : 25-55k€. Réalisations : mini-ascenseur 4 étages 8.5m + modèle extérieur Opale. Signaux marketing : site dense + segment premium revendiqué + présence Batiproduits. Siège : 8 rue Constantin Pecqueur 95150 Taverny (HQ) + La Rochelle + Vendargues.","sources":"societe.com | etnafrance.com"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Ascenseur privatif de villa","entreprise":"ERMHES","ville":"France","zone":"","dirigeant_principal":"Philippe Blitek (CEO)","portable_dirigeant":"","telephone":"02 99 75 13 03","email":"","email_dirigeant":"contact@ermhes.fr","linkedin_dirigeant":"","site_web":"https://ermhes.fr","note_priorite":"Moyenne","source":"fichier ascenseur privatif enrichi","statut":"À contacter","data":{"note":"Fabricant français sur-mesure depuis 1996 + 8000+ installations + virage international. Positionnement : ascenseurs panoramiques sur-mesure + EPMR. Gamme prix : 30-80k€. Réalisations : ascenseurs panoramiques sur-mesure. Signaux marketing : SEO solide + presse régionale (Bretagne Économique) + chaîne maîtrisée. Siège : 23 rue Pierre et Marie Curie 35500 Vitré (16 000m² usine BZH).","sources":"bretagne-economique.com | ermhes.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Ascenseur privatif de villa","entreprise":"Lift-Up Engineering SA","ville":"Belgique","zone":"","dirigeant_principal":"Marc-Henri Gonda (Fondateur — ex-DG Sodimas 10 ans)","portable_dirigeant":"","telephone":"02 808 22 22","email":"","email_dirigeant":"info@lift-up.be","linkedin_dirigeant":"https://www.linkedin.com/in/marc-henri-gonda-25834328/","site_web":"https://www.lift-up.be","note_priorite":"Moyenne","source":"fichier ascenseur privatif enrichi","statut":"À contacter","data":{"note":"Fondé 2012 + LinkedIn fondateur actif. Positionnement : ascenseur privatif + résidentiel + modernisation patrimoine. Gamme prix : 30-70k€. Réalisations : modernisations + résidentiel BE. Signaux marketing : LinkedIn fondateur actif + site clair + référencé Homegrade Brussels. Siège : Belgique (adresse précise non identifiée publiquement).","sources":"lift-up.be | linkedin.com"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Ascenseur privatif de villa","entreprise":"Liftinc SRL","ville":"Belgique","zone":"","dirigeant_principal":"Direction non publique","portable_dirigeant":"","telephone":"02 522 80 80","email":"","email_dirigeant":"info@liftinc.be","linkedin_dirigeant":"https://be.linkedin.com/company/liftinc","site_web":"https://www.liftinc.be","note_priorite":"Moyenne","source":"fichier ascenseur privatif enrichi","statut":"À contacter","data":{"note":"40 personnes + 2700 ascenseurs en parc. Positionnement : résidentiel + commercial. Gamme prix : 30-60k€. Réalisations : installations BE + LU. Signaux marketing : site fonctionnel BE+LU + LinkedIn entreprise actif. Siège : Place Thomas Balis 3 1160 Auderghem. Filiale LU 2011.","sources":"trendstop.levif.be | liftinc.be"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Ascenseur privatif de villa","entreprise":"Home-Lift","ville":"Belgique","zone":"","dirigeant_principal":"Direction non publique","portable_dirigeant":"","telephone":"015 50 21 21","email":"","email_dirigeant":"info@home-lift.be","linkedin_dirigeant":"","site_web":"https://home-lift.be","note_priorite":"Moyenne","source":"fichier ascenseur privatif enrichi","statut":"À contacter","data":{"note":"Spécialiste homelift résidentiel élégant compact. Positionnement : homelift Belgique depuis 2016. Gamme prix : 30-55k€. Réalisations : homelift Belgique. Signaux marketing : site soigné + segment design. Siège : Antwerpsesteenweg 261/21 2800 Mechelen.","sources":"home-lift.be"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Ascenseur privatif de villa","entreprise":"Rigert AG (groupe Garaventa)","ville":"Suisse","zone":"","dirigeant_principal":"Direction groupe Garaventa Lift","portable_dirigeant":"","telephone":"041 854 80 80","email":"","email_dirigeant":"info@rigert.ch","linkedin_dirigeant":"","site_web":"https://www.rigert.ch","note_priorite":"Moyenne","source":"fichier ascenseur privatif enrichi","statut":"À contacter","data":{"note":"Spécialiste Suisse depuis 1962 + design alu + verre. Positionnement : homelift Luma 180kg 2 étages — design alu + verre. Gamme prix : 35-70k CHF. Réalisations : Luma homelift villa rénovation sans gros œuvre. Signaux marketing : site très propre + free consultation + showroom virtuel. Siège : Rütmattstrasse 7 6055 Alpnach Dorf (OW).","sources":"rigert.ch"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Ascenseur privatif de villa","entreprise":"Liftinc Luxembourg SA","ville":"Luxembourg","zone":"","dirigeant_principal":"Non identifié distinctement (filiale Liftinc BE)","portable_dirigeant":"","telephone":"+352 26 50 19 99","email":"","email_dirigeant":"info@liftinc.eu","linkedin_dirigeant":"","site_web":"https://www.liftinc.eu","note_priorite":"Moyenne","source":"fichier ascenseur privatif enrichi","statut":"À contacter","data":{"note":"Filiale luxembourgeoise Liftinc depuis 2011 — résidentiel + tertiaire. Positionnement : villas LU + projets Wallonie sud. Gamme prix : 30-60k€. Réalisations : villas LU + projets Wallonie sud. Signaux marketing : site bilingue FR/EN + bonne intégration corporate. Siège : Rodange (LU).","sources":"liftinc.eu | editus.lu"}},

  // ─── PRIORITÉ BASSE ─────────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Ascenseur privatif de villa","entreprise":"Stannah SAS (France)","ville":"France","zone":"","dirigeant_principal":"Marco Luna (Directeur Général depuis 01/10/2025)","portable_dirigeant":"","telephone":"01 48 79 22 22","email":"","email_dirigeant":"","linkedin_dirigeant":"https://www.linkedin.com/in/marcoluna-london/","site_web":"https://www.stannah.fr","note_priorite":"Basse","source":"fichier ascenseur privatif enrichi","statut":"À contacter","data":{"note":"⚠️ PEU LUXE — leader monte-escalier FR + ads Google + magazines seniors. Positionnement : Uplifts S2/S3 entrée gamme privatif. Gamme prix : 15-35k€. Réalisations : 60 000+ monte-escaliers installés FR / réseau Derby Stannah. Signaux marketing : très SEO senior + ads Google. Siège : 157 Av. Charles Floquet 93150 Le Blanc-Mesnil.","sources":"pappers.fr | stannah.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Ascenseur privatif de villa","entreprise":"GPH Mobilité","ville":"France","zone":"","dirigeant_principal":"Pablo Torres (Président SAS)","portable_dirigeant":"","telephone":"01 39 95 65 00","email":"","email_dirigeant":"info@gph-mobilite.fr","linkedin_dirigeant":"https://fr.linkedin.com/company/gph-mobilite","site_web":"https://www.ascenseurs-privatifs.fr","note_priorite":"Basse","source":"fichier ascenseur privatif enrichi","statut":"À contacter","data":{"note":"⚠️ ATTENTION : LIQUIDATION JUDICIAIRE 18/08/2025 — vérifier statut avant prospection. Positionnement : premier revendeur Aritco FR (segment villa IDF). Gamme prix : 30-70k€. Réalisations : Aritco 4000/6000/7000/9000 villas IDF. Signaux marketing : SEO faible, site daté. Siège : 6 bis rue Jacques Kellner Bât 4 95150 Taverny.","sources":"societe.com | pagesjaunes.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Ascenseur privatif de villa","entreprise":"Stiltz Lifts France","ville":"France","zone":"","dirigeant_principal":"Mike Lord (CEO Stiltz Group UK) / Cameron Gillespie & Lachlan Faulker (fondateurs)","portable_dirigeant":"","telephone":"0800 941 1110","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.stiltzlifts.fr","note_priorite":"Basse","source":"fichier ascenseur privatif enrichi","statut":"À contacter","data":{"note":"⚠️ Ticket plus bas que cible PRODIGIO. Positionnement : mini-ascenseur 1m² UK rails autoportants sans gros œuvre. Gamme prix : 18-35k€ (entrée gamme). Réalisations : Duo+ et Trio+ — niche compact urbain. Signaux marketing : ads Google FR + magazines seniors. Siège FR non identifié (HQ UK Kingswinford West Midlands).","sources":"stiltzlifts.fr | find-and-update.company-information.service.gov.uk"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Ascenseur privatif de villa","entreprise":"Sylift SAS","ville":"France","zone":"","dirigeant_principal":"Bilel Yousfi (Président SAS)","portable_dirigeant":"","telephone":"01 84 60 51 67","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.sylift.fr","note_priorite":"Basse","source":"fichier ascenseur privatif enrichi","statut":"À contacter","data":{"note":"Acteur multimarques jeune — orientation senior plus que pur luxe villa. Positionnement : monte-escalier + ascenseur privatif IDF. Gamme prix : 20-45k€. Réalisations : installations IDF — communication grand public. Signaux marketing : SEO ciblé MaPrimeAdapt. Siège : 8 Avenue Henri Barbusse 93000 Bobigny.","sources":"pappers.fr | sylift.fr"}}

].map(p => ({ qualification: '', date_relance: null, ne_plus_contacter: false, ...p }))
