// Cibles RÉELLES « Home cinéma / salle de projection privée » (INDESCALE).
// Importées du fichier installateurs-cinema-portables-enrichis.csv (15 cibles, FR/BE/LU/MC/CH).
// Cette catégorie est une LISTE FIGÉE (pas de navigation par ville) : marché de niche
// national/international. Données telles que fournies ; 'n/a' laissé vide (jamais inventé),
// la note de qualification et les sources sont conservées dans `data`.

let _c = 0
const cid = () => 'cine-' + (++_c)

export const CINEMA_PROSPECTS = [
  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Home cinéma / salle de projection privée","entreprise":"Ocinema","ville":"France","zone":"","dirigeant_principal":"Lodoïck de la Forest Divonne","portable_dirigeant":"+33 6 25 47 16 62","telephone":"03 44 66 30 99","email":"","email_dirigeant":"lodoick.dlfd@ocinema.com","linkedin_dirigeant":"https://www.linkedin.com/in/lodoïck-de-la-forest-divonne-a94205155/","site_web":"","note_priorite":"Haute","source":"fichier cinéma enrichi","statut":"À contacter","data":{"note":"🔥 CIBLE LA PLUS QUALIFIÉE — portable + email perso direct confirmés via LinkedIn About + Pappers","sources":"https://www.linkedin.com/in/lodoïck-de-la-forest-divonne-a94205155/ | https://www.pappers.fr/entreprise/ocinema-440256485"}},
  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Home cinéma / salle de projection privée","entreprise":"AV Architects","ville":"Belgique","zone":"","dirigeant_principal":"Lionel Pierrard / Kevin Brouwet","portable_dirigeant":"+32 477 52 54 54","telephone":"+32 81 84 10 11","email":"","email_dirigeant":"info@avarchitects.be","linkedin_dirigeant":"https://be.linkedin.com/company/av-architects1","site_web":"","note_priorite":"Haute","source":"fichier cinéma enrichi","statut":"À contacter","data":{"note":"🔥 Mobile belge 0477 (= 06 en BE) — ligne directe agence — email perso Pierrard/Brouwet probable prenom@avarchitects.be (à confirmer LinkedIn)","sources":"https://www.electriciens.pro/gembloux/audio-visual-architects/ | https://be.linkedin.com/company/av-architects1"}},
  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Home cinéma / salle de projection privée","entreprise":"Cinemotion","ville":"Luxembourg","zone":"","dirigeant_principal":"Richard Czapla","portable_dirigeant":"+352 661 15 67 15","telephone":"+352 26 67 12 14","email":"","email_dirigeant":"contact@cinemotion.biz","linkedin_dirigeant":"https://lu.linkedin.com/in/richard-czapla-20406990","site_web":"","note_priorite":"Haute","source":"fichier cinéma enrichi","statut":"À contacter","data":{"note":"🔥 Portable Luxembourg direct — alias HCFR \"moudugnou\" confirme — CIBLE TRÈS QUALIFIÉE","sources":"https://lu.linkedin.com/in/richard-czapla-20406990 | https://www.yellow.lu/en/yellow-pages/6051520-cinemotion-ellange"}},
  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Home cinéma / salle de projection privée","entreprise":"Votre Cinéma","ville":"France","zone":"","dirigeant_principal":"Lionel Lavaure","portable_dirigeant":"","telephone":"09 62 03 31 24","email":"","email_dirigeant":"lionel@votrecinema.fr","linkedin_dirigeant":"","site_web":"","note_priorite":"Moyenne","source":"fichier cinéma enrichi","statut":"À contacter","data":{"note":"Email direct format prenom@votrecinema.fr (100%) — fixe 09 (non-géo) = standard — portable perso non publié — LinkedIn DM https://www.linkedin.com/in/lionel-lavaure-245b70122/","sources":"https://rocketreach.co/votre-cinema-email-format_b7d58190c0e121db | https://www.houzz.fr/pro/votrecinema/"}},
  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Home cinéma / salle de projection privée","entreprise":"ASC Audiovisuel","ville":"France","zone":"","dirigeant_principal":"Eric Farnet","portable_dirigeant":"","telephone":"04 92 28 30 00","email":"","email_dirigeant":"eric@asc-france.com","linkedin_dirigeant":"https://www.linkedin.com/in/eric-farnet-6b801823/","site_web":"","note_priorite":"Moyenne","source":"fichier cinéma enrichi","statut":"À contacter","data":{"note":"Email perso direct (eric@) confirmé via article presse — LinkedIn actif — portable perso à demander via standard","sources":"https://www.webtimemedias.com/article/mougins-eric-farnet-le-petit-poucet-qui-defie-orange-sur-la-fibre | https://www.linkedin.com/in/eric-farnet-6b801823/"}},
  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Home cinéma / salle de projection privée","entreprise":"AVM Cinesound","ville":"France","zone":"","dirigeant_principal":"Patrick Havy","portable_dirigeant":"","telephone":"04 92 18 10 15","email":"","email_dirigeant":"patrick.havy@avm-cinesound.com","linkedin_dirigeant":"","site_web":"","note_priorite":"Moyenne","source":"fichier cinéma enrichi","statut":"À contacter","data":{"note":"Email perso confirmé ContactOut + Viadeo — Membre BNI Cagnes Baie des Anges — portable accessible via inscription BNI","sources":"https://contactout.com/patrick-havy-70431 | https://bni-alpesmaritimes.fr/cagnes-baie-des-anges/fr/memberdetails?encryptedMemberId=QNLk2TKMLNaQmJ83hKsHpw%3D%3D&name=Patrick+HAVY"}},
  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Home cinéma / salle de projection privée","entreprise":"Audio Feeling International (AFI MC)","ville":"Monaco","zone":"","dirigeant_principal":"Jean-François Fabre","portable_dirigeant":"","telephone":"+377 92 05 75 65","email":"","email_dirigeant":"afimc@monaco377.com","linkedin_dirigeant":"","site_web":"","note_priorite":"Moyenne","source":"fichier cinéma enrichi","statut":"À contacter","data":{"note":"Dirigeant = JF Fabre confirmé. Monaco = portable opaque sectoriellement. Email = boîte directe (showroom 22 Quai Jean-Charles Rey)","sources":"https://www.afimc.com/mentions-legales | https://www.afimc.com/contact"}},
  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Home cinéma / salle de projection privée","entreprise":"THC Monaco","ville":"Monaco","zone":"","dirigeant_principal":"pdm + jlg (initiales DAF + Dir Projets)","portable_dirigeant":"","telephone":"+377 97 70 70 42","email":"","email_dirigeant":"pdm@thcmonaco.com","linkedin_dirigeant":"","site_web":"","note_priorite":"Moyenne","source":"fichier cinéma enrichi","statut":"À contacter","data":{"note":"2 emails directs initiales (pdm = DAF / jlg = Dir Projets) — Monaco extrêmement opaque — visite physique 2 Bd Jardin Exotique seule solution pour identifier","sources":"https://thcmonaco.com/en/ | https://www.monte-carlo.mc/en/directory/shopping/household-appliances-audiovisual/thc-total-home-control/"}},
  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Home cinéma / salle de projection privée","entreprise":"Video Systems SA","ville":"Suisse","zone":"","dirigeant_principal":"Eric Rabischung","portable_dirigeant":"","telephone":"+41 22 329 22 88","email":"","email_dirigeant":"","linkedin_dirigeant":"https://fr.linkedin.com/in/eric-rabischung-0024ab52","site_web":"","note_priorite":"Moyenne","source":"fichier cinéma enrichi","statut":"À contacter","data":{"note":"Mentions légales confirment Rabischung comme responsable — adresse 5 route des Jeunes 1227 Genève — LinkedIn DM recommandé","sources":"https://www.vidsys.ch/mentions-legales | https://fr.linkedin.com/in/eric-rabischung-0024ab52"}},
  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Home cinéma / salle de projection privée","entreprise":"Digistore SA","ville":"Suisse","zone":"","dirigeant_principal":"Henri Emmanuel Feige (administrateur unique)","portable_dirigeant":"","telephone":"+41 22 329 22 88","email":"","email_dirigeant":"digistore@digistore.ch","linkedin_dirigeant":"","site_web":"","note_priorite":"Haute","source":"fichier cinéma enrichi","statut":"À contacter","data":{"note":"✅ NOUVEAU dirigeant identifié = Henri Emmanuel Feige via Moneyhouse — ex-président devenu administrateur unique — passer standard pour transfert","sources":"https://www.moneyhouse.ch/en/company/digistore-sa-12050265021 | https://digistore.ch/nous-contacter"}},
  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Home cinéma / salle de projection privée","entreprise":"Cinephil SRL","ville":"Belgique","zone":"","dirigeant_principal":"Direction non identifiée","portable_dirigeant":"","telephone":"+32 81 22 41 49","email":"","email_dirigeant":"info@cinephil.be","linkedin_dirigeant":"","site_web":"","note_priorite":"Moyenne","source":"fichier cinéma enrichi","statut":"À contacter","data":{"note":"SRL déc. 2002 BE0479027372 — 5.9 ETP — dirigeant non publié sur Companyweb gratuit — 75 avis Google 4.7/5 — visite showroom 30 rue Rogier 5000 Namur recommandée","sources":"https://www.companyweb.be/en/0479027372/cine-phil | https://www.cinephil.be/contact.html"}},
  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Home cinéma / salle de projection privée","entreprise":"Cine Install Services","ville":"France","zone":"","dirigeant_principal":"Direction non identifiée (ex-SAE)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"","note_priorite":"Moyenne","source":"fichier cinéma enrichi","statut":"À contacter","data":{"note":"Aucun nom dirigeant publié — équipe d'anciens SAE depuis 2004 — non trouvé Pappers/Societe.com/LinkedIn avec ces termes — appel direct standard ou LinkedIn search employés","sources":"https://www.cine-install.fr/ | http://www.cine-install.fr/contactez-nous"}},
  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Home cinéma / salle de projection privée","entreprise":"Custom Cinéma","ville":"France","zone":"","dirigeant_principal":"Gil Pétuaud-Létang","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"contact@custom-cinema.fr","linkedin_dirigeant":"https://fr.linkedin.com/in/gil-petuaud-letang-25622934","site_web":"","note_priorite":"Moyenne","source":"fichier cinéma enrichi","statut":"À contacter","data":{"note":"Mentions légales = SAS HAT 4 rue Massenet 33680 LACANAU — siège réel Lacanau pas Bouliac — portable absent Houzz/Pappers/LinkedIn — appeler standard ou LinkedIn DM","sources":"https://custom-cinema.fr/custom-cinema-une-entreprise-a-votre-service/mentions-legales/ | https://fr.linkedin.com/in/gil-petuaud-letang-25622934"}},
  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Home cinéma / salle de projection privée","entreprise":"L'Audiovidéiste","ville":"France","zone":"","dirigeant_principal":"Thomas Lamouche","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"t.lamouche@laudiovideiste.fr","linkedin_dirigeant":"https://www.linkedin.com/in/thomas-lamouche-771913153/","site_web":"","note_priorite":"Haute","source":"fichier cinéma enrichi","statut":"À contacter","data":{"note":"✅ NOUVEAU dirigeant identifié = Thomas Lamouche — Gérant SARL créée sept 2018 (SIREN 842475196) Valencin 38540 — email direct confirmé Societe.com","sources":"https://www.societe.com/manager/Thomas.LAMOUCHE.yen3_C7RUsu.html | https://www.linkedin.com/in/thomas-lamouche-771913153/"}},
  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Home cinéma / salle de projection privée","entreprise":"Mon Ciné Privé","ville":"France","zone":"","dirigeant_principal":"Didier Autric","portable_dirigeant":"","telephone":"04 84 88 53 28","email":"","email_dirigeant":"","linkedin_dirigeant":"https://www.linkedin.com/in/didier-autric/","site_web":"","note_priorite":"Moyenne","source":"fichier cinéma enrichi","statut":"À contacter","data":{"note":"Gérant A DYNAMIC HOME CINEMA (SIRET 43359877800044) — adresse réelle Rue Sainte 13000 Marseille — chaîne YouTube Didier AUTRIC active — LinkedIn DM ou formulaire","sources":"https://www.linkedin.com/in/didier-autric/ | https://www.moncineprive.com/mentions-legales"}}
].map(p => ({ qualification: '', date_relance: null, ne_plus_contacter: false, ...p }))
