// Cibles RÉELLES « Cryothérapie / récupération / longévité » (INDESCALE).
// 17 cibles FR/CH/BE/LU. Liste figée. Notes denses regroupant positionnement, gamme prix,
// réalisations, signaux marketing. 'n/a' laissé vide (jamais inventé).

let _c = 0
const cid = () => 'cryo-' + (++_c)

export const CRYOTHERAPIE_PROSPECTS = [
  // ─── PRIORITÉ HAUTE ────────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Cryothérapie / récupération / longévité","entreprise":"CRYOFAST Group","ville":"France","zone":"","dirigeant_principal":"Pascal Jarmoune (Founder & CEO)","portable_dirigeant":"","telephone":"09 83 61 83 55","email":"","email_dirigeant":"contact@cryofast.fr","linkedin_dirigeant":"https://www.linkedin.com/in/pascal-jarmoune-ab6aa58/","site_web":"https://cryofast.fr","note_priorite":"Haute","source":"fichier cryothérapie enrichi","statut":"À contacter","data":{"note":"🔥 Leader FR cryo + lancement Cryofast Plunge + ouverture showroom Paris 2025. Positionnement : leader FR cryo, fabricant + franchisseur, gamme premium cabines électriques + cryosauna. Gamme prix : cabines 30-80k€ HT (azote) / jusqu'à 350k€ électriques multi-sas. Réalisations : ouverture showroom Paris 2025 + lancement Cryofast Plunge (bains froid). Signaux marketing : très actif LinkedIn / franchise / SEO fort. Siège : 19 rue de Cléry 75002 Paris.","sources":"toute-la-franchise.com | linkedin"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Cryothérapie / récupération / longévité","entreprise":"France Cryo","ville":"France","zone":"","dirigeant_principal":"Non public (entreprise depuis 2017)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"contact@francecryo.com","linkedin_dirigeant":"","site_web":"https://www.francecryo.com","note_priorite":"Haute","source":"fichier cryothérapie enrichi","statut":"À contacter","data":{"note":"🔥 Explicitement positionné 'marché privé + yachts de luxe' avec IcePod modulaire. Positionnement : distributeur multi-marques (IcePod, PowerCab, CRYO°CABIN Finlande, Mecotec) — gamme spa luxe + yacht. Gamme prix : 30-150k€ par cabine + installation + formation. Réalisations : IcePod positionnée explicitement 'marché privé / yachts de luxe'. Signaux marketing : site SEO costaud + Instagram @france_cryo actif. Siège : Aix-en-Provence 13. France entière + export Belgique/Suisse/Lux.","sources":"francecryo.com"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Cryothérapie / récupération / longévité","entreprise":"CryoZen Benelux","ville":"Belgique","zone":"","dirigeant_principal":"Christian Cloos","portable_dirigeant":"+32 492 27 23 86","telephone":"","email":"","email_dirigeant":"info@cryozen.be","linkedin_dirigeant":"https://www.linkedin.com/in/cryozen-cryothérapie-belgique-a107a1130/","site_web":"https://www.cryozen.be","note_priorite":"Haute","source":"fichier cryothérapie enrichi","statut":"À contacter","data":{"note":"🔥 Exclusif KRION sur 3 pays = pas concurrencé + mobile direct. Positionnement : distributeur exclusif KRION (Russie/St-Pétersbourg) Benelux. Gamme prix : cryosauna 35-90k€ + installation européens. Réalisations : centre Bruxelles + vente B2B Benelux. Signaux marketing : site bilingue FR/EN + présence Belgique B2B. Siège : Avenue Winston Churchill 84 1180 Uccle Bruxelles.","sources":"cryozen.be | belgiquebd.com"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Cryothérapie / récupération / longévité","entreprise":"Kino-B / O2 Relax","ville":"France","zone":"","dirigeant_principal":"Mikaël Ermine (créateur/gérant SARL Kino-B) + Stéphane Bochart (centre Paris)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"contact@kino-b.fr","linkedin_dirigeant":"https://fr.linkedin.com/in/mikael-ermine-28017273","site_web":"https://kino-b.fr","note_priorite":"Haute","source":"fichier cryothérapie enrichi","statut":"À contacter","data":{"note":"🔥 Pionnier hyperbare wellness FR + dirigeant actif LinkedIn. Positionnement : location + vente domicile (caisson souple 80x225cm). Gamme prix : caisson 12-25k€ (vente) / 800-2000€/sem location. Réalisations : ouverture O2 Relax Paris 15 (premier centre dédié) + livraison nationale. Signaux marketing : LinkedIn articles réguliers Mikaël Ermine. Siège : Châteaubriant (Loire-Atlantique) + centre Paris 15e (19 rue Croix-Nivert).","sources":"linkedin.com | kino-b.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Cryothérapie / récupération / longévité","entreprise":"Atelier Wellness","ville":"Suisse","zone":"","dirigeant_principal":"Non public","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"info@atelierwellness.ch","linkedin_dirigeant":"","site_web":"https://www.atelierwellness.ch","note_priorite":"Haute","source":"fichier cryothérapie enrichi","statut":"À contacter","data":{"note":"🔥 Wellness suite intégrée villa CHF — ticket 100-500k€. Positionnement : fabricant artisanal sur-mesure SPA + sauna + hammam + cabine à neige villa luxe + hôtels. Gamme prix : 50-300k€ projet villa complet. Réalisations : hôtels prestige + clients privés Suisse romande. Signaux marketing : site bilingue + portfolio références. Siège : Nyon Vaud.","sources":"atelierwellness.ch"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Cryothérapie / récupération / longévité","entreprise":"Atelier Nordic","ville":"Suisse","zone":"","dirigeant_principal":"Non public","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.ateliernordic.ch","note_priorite":"Haute","source":"fichier cryothérapie enrichi","statut":"À contacter","data":{"note":"Fabricant sauna bois + spa Jacuzzi haut de gamme installation villa Genève/Lausanne. Positionnement : sur-mesure CH romande. Gamme prix : 30-150k€. Réalisations : sauna Cosmic bubble panoramique + saunas extérieurs cèdre rouge. Signaux marketing : site EN/FR optimisé. Atelier près Genève.","sources":"ateliernordic.ch"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Cryothérapie / récupération / longévité","entreprise":"KLAFS Suisse","ville":"Suisse","zone":"","dirigeant_principal":"Direction CH (HQ Allemagne KLAFS GmbH)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.fr.klafs.ch","note_priorite":"Haute","source":"fichier cryothérapie enrichi","statut":"À contacter","data":{"note":"Référence absolue sauna luxe DE/CH depuis 1928 — sur mesure villa. Positionnement : Tessin + Suisse alémanique + romande. Gamme prix : 80-500k€ projets villa. Réalisations : référence privée Aargau (annexe wellness AURA). Signaux marketing : catalogue très haut de gamme + showrooms physiques. Multiple showrooms CH.","sources":"fr.klafs.ch"}},

  // ─── PRIORITÉ MOYENNE ──────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Cryothérapie / récupération / longévité","entreprise":"Mecotec France","ville":"France","zone":"","dirigeant_principal":"Direction FR (HQ Allemagne Mecotec GmbH)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"contact@mecotec.fr","linkedin_dirigeant":"","site_web":"https://www.mecotec.fr","note_priorite":"Moyenne","source":"fichier cryothérapie enrichi","statut":"À contacter","data":{"note":"Made in Germany TÜV cryo électrique sans azote. Positionnement : pro/clinique + chambre haut de gamme. Gamme prix : cabines 80-250k€. Réalisations : installations Pontarlier/Montpellier/Béziers/Toulouse/Bron/Marseille. Signaux marketing : Facebook Mecotec France actif + ArchiExpo. Siège : Mauguio 34 (filiale FR). France + Benelux + Suisse.","sources":"mecotec.fr | mecotec.net"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Cryothérapie / récupération / longévité","entreprise":"Recoveric","ville":"France","zone":"","dirigeant_principal":"Lidija (fondatrice, nom famille non public)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"info@recoveric.fr","linkedin_dirigeant":"","site_web":"https://recoveric.fr","note_priorite":"Moyenne","source":"fichier cryothérapie enrichi","statut":"À contacter","data":{"note":"Caisson hyperbare 1.5 ATA souple/rigide + accompagnement biohacking récup. Positionnement : niche récup sportive premium. Gamme prix : caisson 8-25k€ selon modèle. Réalisations : gamme Hyperbaric XL assis/allongé + caisson allongé 1.5 ATA. Signaux marketing : blog FAQ récup sportive + référencement SEO récup.","sources":"recoveric.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Cryothérapie / récupération / longévité","entreprise":"Hyperbare Revolution","ville":"France","zone":"","dirigeant_principal":"Dr Pencalet (neurochirurgien fondateur)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://hyperbarerevolution.fr","note_priorite":"Moyenne","source":"fichier cryothérapie enrichi","statut":"À contacter","data":{"note":"Caution médicale = différenciant CSP+++ santé. Positionnement : caisson nouvelle génération pour centres privés (mais peut équiper villa). Gamme prix : sur devis (15-40k€ probable). Réalisations : cabine Hyperbare Révolution installée à Complexe La Salle. Signaux marketing : caution médicale = différenciant.","sources":"hyperbarerevolution.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Cryothérapie / récupération / longévité","entreprise":"Sport Orthèse (KAATSU France officiel)","ville":"France","zone":"","dirigeant_principal":"Direction FR","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.sport-orthese.com","note_priorite":"Moyenne","source":"fichier cryothérapie enrichi","statut":"À contacter","data":{"note":"Distributeur exclusif KAATSU (BFM training) — équipement biohacking portable haut de gamme. Positionnement : France + Belgique + Luxembourg + Monaco + Andorre. Gamme prix : KAATSU Cycle 3/4 1.5-3k€ / Master 2.0 5-8k€. Réalisations : Cycle 4 BFM nouvelle gen disponible 2026. Signaux marketing : SEO fort BFR/KAATSU + PDF technique.","sources":"sport-orthese.com"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Cryothérapie / récupération / longévité","entreprise":"Wellness Concept","ville":"Belgique","zone":"","dirigeant_principal":"Direction (Companyweb.be)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://wellness-concept.be","note_priorite":"Moyenne","source":"fichier cryothérapie enrichi","statut":"À contacter","data":{"note":"Installateur Jacuzzi + Vivo Spa + sauna luxe vitré (Barrel/Terrasse/Hobbit). Positionnement : Liège + Wallonie. Gamme prix : 20-80k€ par projet villa. Réalisations : showroom Fléron 2024 + chantiers Visé. Signaux marketing : site SEO sauna Liège dominant. Siège : Fléron (Liège).","sources":"wellness-concept.be"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Cryothérapie / récupération / longévité","entreprise":"Beverley Distribution Suisse","ville":"Suisse","zone":"","dirigeant_principal":"Denis Goehry (Bodycocoon Wellness Suisse) + Anne-Sophie Van Hoove","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"https://ch.linkedin.com/in/denis-goehry-541491a2","site_web":"https://www.beverley-distribution.ch","note_priorite":"Moyenne","source":"fichier cryothérapie enrichi","statut":"À contacter","data":{"note":"⚠️ ATTENTION : entité FR en liquidation déc. 2022 — vérifier si CH active. Positionnement : distributeur sauna infrarouge Red10 + body cocoon + PowerPlate + Sybaritic (multi-marques wellness premium). Gamme prix : 5-40k€ par produit. Réalisations : multi-magasins CH/FR. Siège : Lausanne CH + Chens-sur-Léman 74140 FR (BodySelect Sàrl).","sources":"beverley-distribution.ch | societe.com 845271782"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Cryothérapie / récupération / longévité","entreprise":"Sunlighten France/Europe","ville":"France","zone":"","dirigeant_principal":"Direction Europe (HQ USA Aaron Zack)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.sunlighten.eu/fr","note_priorite":"Moyenne","source":"fichier cryothérapie enrichi","statut":"À contacter","data":{"note":"Marque US référence sauna IR premium. Positionnement : gamme Signature/mPulse/Solo. Gamme prix : 8-30k€ par sauna. Réalisations : présence FR avec architectes intérieur. Signaux marketing : catalogue Markets We Serve - Home Designers. HQ EU à confirmer (sunlighten.eu).","sources":"sunlighten.com/fr-fr"}},

  // ─── PRIORITÉ BASSE ─────────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Cryothérapie / récupération / longévité","entreprise":"Octane Wellness","ville":"France","zone":"","dirigeant_principal":"François Galtié (fondateur)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.octane-wellness.com","note_priorite":"Basse","source":"fichier cryothérapie enrichi","statut":"À contacter","data":{"note":"Hub réseau distributeurs équipements CSP+++. Positionnement : premier centre régénératif FR (cryo + hyperbare + red light + sauna). Gamme prix : centre B2C principalement. Réalisations : ouvert déc. 2023 175m² 6 cabines Paris 9e. Signaux marketing : presse Vogue / Anti-Age Magazine / Sense of Wellness. Angle = ils KNOWN les CSP+++ qui veulent à la maison.","sources":"octane-wellness.com"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Cryothérapie / récupération / longévité","entreprise":"R15 Studio","ville":"France","zone":"","dirigeant_principal":"George Kozma (Président) + Florian Mouchel (cofondateur)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"https://www.linkedin.com/in/george-kozma-68b6544/","site_web":"https://www.r15-studio.com","note_priorite":"Basse","source":"fichier cryothérapie enrichi","statut":"À contacter","data":{"note":"Premier biohacking studio FR (ARX + photobiomod + PEMF + hyperbare + KAATSU). Positionnement : centre B2C mais prescripteur équipement villa. Gamme prix : hub influence CSP+++. Réalisations : Sommet Hypersanté 2025/26 sponsor. Signaux marketing : présence média The Good Life / Alliancy. Siège : 96 av. Mozart 75016 Paris.","sources":"r15-studio.com | societe.com 885063867"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Cryothérapie / récupération / longévité","entreprise":"Clearlight Saunas Europe GmbH","ville":"France","zone":"","dirigeant_principal":"Direction EU","portable_dirigeant":"","telephone":"+49 40 4011 0162","email":"","email_dirigeant":"info@clearlight-saunen.de","linkedin_dirigeant":"","site_web":"https://www.clearlightsaunas.eu","note_priorite":"Basse","source":"fichier cryothérapie enrichi","statut":"À contacter","data":{"note":"⚠️ HQ DE = friction langue FR / présence locale faible. Positionnement : sauna IR haut de gamme garantie à vie résidentielle. Gamme prix : 5-25k€. Réalisations : livraison 5-10j ouvrés FR depuis hub Hambourg. Signaux marketing : distribution directe (pas de réseau dealer FR/CH structuré). Siège : Rödingsmarkt 9 20359 Hamburg DE.","sources":"clearlightsaunas.eu"}}

].map(p => ({ qualification: '', date_relance: null, ne_plus_contacter: false, ...p }))
