// Cibles RÉELLES « Domotique luxe intégrée (Crestron, KNX) » (INDESCALE).
// 32 cibles FR/CH/BE/LU. Liste figée. Notes denses regroupant positionnement, gamme prix,
// réalisations, signaux marketing. 'n/a' laissé vide (jamais inventé).
// Overlap fort avec catégorie 'Home cinéma / salle de projection privée' (intégrateurs custom install).

let _c = 0
const cid = () => 'domo-' + (++_c)

export const DOMOTIQUE_LUXE_PROSPECTS = [
  // ─── PRIORITÉ HAUTE ────────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"HENRI","ville":"France","zone":"","dirigeant_principal":"Lionel Sherman (Président) / Michael Sherman (DG)","portable_dirigeant":"","telephone":"01 43 28 56 14","email":"","email_dirigeant":"m.sherman@henri.fr","linkedin_dirigeant":"https://www.linkedin.com/company/henri-int-grateur-domotique","site_web":"https://www.henri.fr","note_priorite":"Haute","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"🔥 LE GRAAL — seul français Crestron Platinum Elite. Positionnement : référence historique du luxe parisien depuis 1961. Gamme prix : 150-500k€+. Réalisations : cuisine Tristan Auer, hôtels particuliers Paris, La Maison Henri showroom. Signaux marketing : site très soigné + presse pro (Smart Intégrations Mag, CEDIA Awards) — pas d'ads visibles. Paris (siège) + agences Cannes et Annecy. ⚠️ OVERLAP catégorie Home cinéma.","sources":"henri.fr | smartintegrationsmag.com | LinkedIn"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"OÏKO","ville":"France","zone":"","dirigeant_principal":"Alexandre Dupeu (Fondateur & CEO)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"contact@oiko.eu","linkedin_dirigeant":"https://www.linkedin.com/in/alexandredupeu/","site_web":"https://www.oiko.eu","note_priorite":"Haute","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"🔥 Crestron Platinum + Lutron HTI + levée 1,5M€ + croissance +120%. Positionnement : digitalisation d'intérieur ultra-luxe (hôtellerie + villas). Gamme prix : 200k-1M€+. Réalisations : Hotel Martinez (Lutron), 200+ projets dont chalets Alpes, rachat IPEK 2022. Signaux marketing : levée 1,5M€ Odyssée Venture + branding très haut de gamme. Siège : 33 avenue du Maine 75015 Paris. Couvre Paris + Alpes françaises + intl 3 continents. ⚠️ OVERLAP catégorie Home cinéma.","sources":"oiko.eu | linkedin | fusacq.com"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"FC INTEGRATION","ville":"France","zone":"","dirigeant_principal":"Frantz Carion (Fondateur & CEO)","portable_dirigeant":"","telephone":"+33 4 93 24 03 70","email":"","email_dirigeant":"contact2@fc-integration.com","linkedin_dirigeant":"https://www.linkedin.com/in/frantz-carion-91a923/","site_web":"https://fc-integration.com","note_priorite":"Haute","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"🔥 Conciergerie IT haut de gamme villas + yachts depuis 2011. Positionnement : référence Riviera. Gamme prix : 100-500k€. Réalisations : villas Cap d'Antibes, yachts Monaco, projets St-Tropez. Signaux marketing : récente ouverture entité Monaco + presse économique locale. Siège : 6 av Princesse Alice Monaco + Vence (06140). Couvre Monaco + Côte d'Azur + yachts. ⚠️ OVERLAP catégorie Home cinéma.","sources":"fc-integration.com | monaco-economie.com | societe.com"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"MONACO DOMOTIQUE SARL","ville":"Monaco","zone":"","dirigeant_principal":"Fondateur (35 ans d'exp, nom à valider)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"https://mc.linkedin.com/company/monaco-domotique","site_web":"https://monacodomotique.mc","note_priorite":"Haute","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"🔥 Crestron + KNX référence villas Monaco. Positionnement : programmes immobiliers neufs Monaco. Gamme prix : 100-400k€. Réalisations : programmes immobiliers neufs Monaco + yachts. Signaux marketing : société récente (2023) issue d'un fondateur historique + branding institutionnel. Siège : Le Patio Palace 41 Av Hector Otto Monaco.","sources":"monacodomotique.mc | pappers.fr | annuaire-entreprises.data.gouv.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"IMMOTIK","ville":"France","zone":"","dirigeant_principal":"Karl Santamarina (cofondateur, ex-DSI)","portable_dirigeant":"06 19 40 96 56","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.immotik.fr","note_priorite":"Haute","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct + certifié KNX + Crestron + Lutron + Control4 + Smart Home AFNOR. Positionnement : clientèle premium IDF/Lyon. Gamme prix : 50-200k€. Réalisations : hôtels particuliers Paris, villas IDF. Signaux marketing : site SEO+++ (multi pages par dpt) + labellisé AFNOR. Siège : 164 Bd de Bezons 78500 Sartrouville.","sources":"immotik.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"DSR (Dark Side of the Room)","ville":"France","zone":"","dirigeant_principal":"Direction non publique","portable_dirigeant":"","telephone":"04 72 73 01 71","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://dsr.fr","note_priorite":"Haute","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"Lutron HomeWorks + Crestron + membre CEDIA depuis 2005. Positionnement : chalets/appartements haussmanniens. Gamme prix : 100-500k€. Réalisations : chalet Megève La Maille (Lutron HomeWorks 140 circuits), appartement bourgeois Paris. Signaux marketing : réalisations photo+++ avec descriptifs techniques précis. Siège : 13 rue Jarente 69002 Lyon. ⚠️ OVERLAP catégorie Home cinéma.","sources":"dsr.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"iDOMOTEC","ville":"Suisse","zone":"","dirigeant_principal":"Soufiane Benbkhat (Fondateur & CEO, 1er CSP Crestron CH)","portable_dirigeant":"","telephone":"+41 22 940 30 00","email":"","email_dirigeant":"","linkedin_dirigeant":"https://www.linkedin.com/in/idomotec-5278b8105/","site_web":"https://www.idomotec.ch","note_priorite":"Haute","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"🔥 1ère société Suisse Crestron Services Provider (CSP) + signaux digitaux faibles = ENORME upside acquisition. Positionnement : Crestron + KNX + OPC + BACNET. Gamme prix : 100-500k€. Réalisations : villas Cologny + Genève + projets Maroc. Signaux marketing : LinkedIn + Instagram actifs (idomotec_ch). Siège : Chemin du Château-Bloch 10 1219 Genève (Grand-Lancy).","sources":"idomotec.ch | rocketreach.co | linkedin"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"HOME AUTOMATION BY NJ","ville":"Suisse","zone":"","dirigeant_principal":"Nawsad Joomratty (Fondateur & DG, depuis 2018)","portable_dirigeant":"","telephone":"+41 21 653 18 86","email":"","email_dirigeant":"info@home-automationbynj.ch","linkedin_dirigeant":"https://www.linkedin.com/in/nawsad-joomratty-09653872/","site_web":"https://www.home-automationbynj.ch","note_priorite":"Haute","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"🔥 Croissance forte + email direct + LinkedIn dispo = profil parfait pour campagne ciblée. Positionnement : Crestron + Control4 + KNX + Legrand. Gamme prix : 80-400k€. Réalisations : villas Vaud + Genève. Signaux marketing : blog actif + LinkedIn entreprise + Facebook. Siège : Chemin d'Entre-Bois 29A 1018 Lausanne.","sources":"home-automationbynj.ch | LinkedIn | moneyhouse.ch"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"VIDEO SYSTEMS SA (Vidsys)","ville":"Suisse","zone":"","dirigeant_principal":"Eric Rabischung (responsable, depuis 1982)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.vidsys.ch","note_priorite":"Haute","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"Crestron + AMX + Extron + Bang & Olufsen. Positionnement : résidentiel + hôtels + pro depuis 1982. Gamme prix : 80-400k€. Réalisations : chalets Megève + villas Genève/Lausanne. Signaux marketing : site bilingue FR/EN + historique 40 ans. Siège : 5 route des Jeunes Les Acacias 1227 Genève. ⚠️ AUSSI dans catégorie Home cinéma (overlap).","sources":"vidsys.ch | business-monitor.ch | LinkedIn"}},

  // ─── PRIORITÉ MOYENNE ──────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"DOMOTIC","ville":"France","zone":"","dirigeant_principal":"Équipe Alexis + Bruno (dirigeants Pappers à confirmer)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://domotic.fr","note_priorite":"Moyenne","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"Crestron Major Partner France — bureau d'études domotique PACA/Monaco. Positionnement : 20 ans d'historique. Gamme prix : 100-400k€. Réalisations : villas Cap-Ferrat, Mougins, Monaco. Signaux marketing : site institutionnel modeste — peu de signaux digitaux récents. Siège : Mougins (06) depuis 2004.","sources":"domotic.fr | travaux.com"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"TEKITIZY","ville":"France","zone":"","dirigeant_principal":"Bastien Collin & Térence Scalabre (co-gérants)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.tekitizy.com","note_priorite":"Moyenne","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"Multi-marques Loxone/Lutron/KNX/Control4/Jeedom — villas + yachts Riviera. Positionnement : Cannes/Mougins/Mandelieu/Monaco/Antibes/Nice + yachts. Gamme prix : 50-200k€. Réalisations : villas Cannes + projets yachts Antibes. Signaux marketing : site bilingue FR/EN propre + jeune SARL (2018). Siège : 11 Rue des Moulières 06110 Le Cannet.","sources":"tekitizy.com | pappers.fr | manageo.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"AEID (Absolu Electricité Intégration Domotique)","ville":"France","zone":"","dirigeant_principal":"Daniel Lochon (gérant)","portable_dirigeant":"06 08 28 27 06","telephone":"","email":"","email_dirigeant":"absolu.electricite@free.fr","linkedin_dirigeant":"","site_web":"https://www.aeid-domotique.fr","note_priorite":"Moyenne","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct + certifié KNX + Savant Systems + LED. Positionnement : villas haut de gamme PACA depuis 2002. Gamme prix : 80-300k€. Réalisations : villas Valbonne, Cap d'Antibes, projets architectes. Signaux marketing : site daté + WordPress modeste — peu de présence digitale. Siège : 1422 Ch du Val Martin 06560 Valbonne.","sources":"aeid-domotique.fr | absoludomotique.wordpress.com | monartisan.info"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"VESTALIA","ville":"France","zone":"","dirigeant_principal":"Jean-Marie Allard (Fondateur) + Cédric Allard + Yann Scardino (co-gérants)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"https://fr.linkedin.com/in/jean-marie-allard-b8b6498a","site_web":"https://vestalia-domotique.fr","note_priorite":"Moyenne","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"Crestron + Lutron + LinkedIn Fondateur actif. Positionnement : domotique + home cinéma haut de gamme PACA. Gamme prix : 80-300k€. Réalisations : résidences exceptionnelles Provence + PACA. Signaux marketing : LinkedIn Fondateur actif + branding clean. Siège : 195 Rue de l'Acacia 13300 Salon-de-Provence.","sources":"vestalia-domotique.fr | pappers.fr | LinkedIn"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"CRYSTAL TECHNOLOGY","ville":"France","zone":"","dirigeant_principal":"Direction non publique","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"https://fr.linkedin.com/company/crystal-technology","site_web":"https://www.crystaltechnology.fr","note_priorite":"Moyenne","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"Smart home chalets de prestige Alpes + Côte d'Azur depuis 2003. Positionnement : Alpes FR + Alpes CH + Provence + Côte d'Azur. Gamme prix : 100-400k€. Réalisations : chalets Megève, villas Provence, hôtels. Signaux marketing : galerie réalisations forte + site bien fait. Siège : Megève (74). ⚠️ OVERLAP catégorie Home cinéma.","sources":"crystaltechnology.fr | LinkedIn"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"HI-CONCEPT","ville":"France","zone":"","dirigeant_principal":"Direction non publique","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://hi-concept.fr","note_priorite":"Moyenne","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"Certifié Crestron + Control4 + Lutron + KNX + Sonos. Positionnement : cinéma privé primé + appartements haussmanniens. Gamme prix : 80-400k€. Réalisations : Avenue Montaigne (Haussmann), hôtels particuliers, cinémas privés primés. Signaux marketing : site très soigné + galerie projets + langue EN. Siège : Laval (Mayenne) + agence Paris. ⚠️ OVERLAP catégorie Home cinéma.","sources":"hi-concept.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"CONNECTING TECHNOLOGY","ville":"France","zone":"","dirigeant_principal":"Direction non publique","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.connecting-technology.com","note_priorite":"Moyenne","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"Kalismart + Crestron + KNX + certifié Crestron Marine (yachts). Positionnement : Paris + Antibes + yachts. Gamme prix : 80-300k€. Réalisations : yachts + résidences Paris/Côte d'Azur. Signaux marketing : membre Smart Building Alliance + AFNOR + site institutionnel.","sources":"connecting-technology.com"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"HI-TECHNOLOGIES SA","ville":"Suisse","zone":"","dirigeant_principal":"Direction non publique (36 salariés)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://hi-technologies.ch","note_priorite":"Moyenne","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"Crestron Elite Partner — AV + domotique pro & résidentiel — 15 ans. Positionnement : Genève + Lausanne + Fribourg + Neuchâtel + Paris. Gamme prix : 100-500k€. Réalisations : salles cinéma privées, multiroom, résidences + tertiaire. Signaux marketing : site très pro + équipe affichée + EN/FR. Siège : Genève + filiale Paris.","sources":"hi-technologies.ch"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"SO SMART SA","ville":"Suisse","zone":"","dirigeant_principal":"Gérald Ferrari (associé capital)","portable_dirigeant":"","telephone":"021 963 11 74","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.so-smart.swiss","note_priorite":"Moyenne","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"Showroom Control4 certifié Montreux + apps iOS/Android sur mesure. Positionnement : Vaud + Suisse romande. Gamme prix : 50-200k€. Réalisations : résidences Montreux/Vevey/Lavaux. Signaux marketing : showroom physique + site clean. Siège : Chailly-Montreux + showroom St-Légier.","sources":"so-smart.swiss | local.infobel.ch | moneyhouse.ch"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"AV ARCHITECTS","ville":"Belgique","zone":"","dirigeant_principal":"Équipe : Lionel Pierrard + Kevin Brouwet","portable_dirigeant":"+32 477 52 54 54","telephone":"+32 81 84 10 11","email":"","email_dirigeant":"info@avarchitects.be","linkedin_dirigeant":"https://be.linkedin.com/company/av-architects1","site_web":"https://www.avarchitects.be","note_priorite":"Moyenne","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"Home cinéma + domotique + WiFi + vidéosurveillance + multiroom. Positionnement : résidentiel/hôtellerie. Gamme prix : 50-200k€. Réalisations : villas Brabant Wallon + Bruxelles. Signaux marketing : Instagram actif + Facebook + LinkedIn. Siège : Rue Moulin Brabant 16 Gembloux (créée 2009). ⚠️ AUSSI dans catégorie Home cinéma (overlap).","sources":"avarchitects.be | electriciens.pro | LinkedIn"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"INTEGRATION AT HOME (iAhome)","ville":"Belgique","zone":"","dirigeant_principal":"Cédric (prénom seul publié)","portable_dirigeant":"0487 59 46 38","telephone":"","email":"","email_dirigeant":"cedric@iahome.be","linkedin_dirigeant":"","site_web":"https://iahome.be","note_priorite":"Moyenne","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"🔥 Mobile direct + Control4 + KNX + interrupteurs Lithoss/Meljac luxe. Positionnement : design + tech. Gamme prix : 80-300k€. Réalisations : intérieurs design avec Lithoss/Meljac. Signaux marketing : site bilingue FR/EN + branding design.","sources":"iahome.be"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"KNX SOLUTIONS / knx-domotique.lu","ville":"Luxembourg","zone":"","dirigeant_principal":"Direction (15+ ans exp depuis 2010)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://knx-domotique.lu","note_priorite":"Moyenne","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"Expert KNX Luxembourg depuis 2010 — domotique + multimedia + tertiaire. Positionnement : Luxembourg + Grande Région. Gamme prix : 30-150k€ (12-30k€ pour 150m²). Réalisations : villa luxe Luxembourg avec multimédia KNX intégré. Signaux marketing : site clean + blog SEO (guide prix 2025).","sources":"knx-domotique.lu"}},

  // ─── PRIORITÉ BASSE ─────────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"AUDIRE","ville":"France","zone":"","dirigeant_principal":"Dominique Rigolet (gérant)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"http://www.audire.fr","note_priorite":"Basse","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"Home cinema + advanced home automation Paris — membre CEDIA. Positionnement : Paris + IDF. Gamme prix : 100-300k€. Réalisations : appartements + maisons IDF — réalisations confidentielles. Signaux marketing : site daté + branding discret/référencement faible. ⚠️ OVERLAP catégorie Home cinéma.","sources":"audire.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"NORDOM","ville":"France","zone":"","dirigeant_principal":"Direction non publique","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.nordom.fr","note_priorite":"Basse","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"KNX Partner + éco-expert Schneider. Positionnement : résidentiel + tertiaire 0-5000m². Gamme prix : 50-200k€. Réalisations : résidences moyenne et haute gamme Normandie. Signaux marketing : site fonctionnel — peu de signaux marketing premium. Siège : 5 rue de Paris 76600 Le Havre.","sources":"nordom.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"FCS DOMOTIQUE","ville":"France","zone":"","dirigeant_principal":"Etienne Chanal + Florent Chanal (frères co-gérants)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://fcsdomotique.com","note_priorite":"Basse","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"KNX Partner + Advanced — membre collège intégrateur KNX France. Positionnement : Drôme + Sud-Est. Gamme prix : 50-200k€. Réalisations : maisons Drôme/Ardèche/Vaucluse. Signaux marketing : présence pro KNX France + LinkedIn entreprise. Siège : Montélimar (26).","sources":"fcsdomotique.com | LinkedIn"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"ECS-ELEC","ville":"France","zone":"","dirigeant_principal":"Jean-Frédéric (gérant, nom complet non publié)","portable_dirigeant":"06 09 28 85 02","telephone":"","email":"","email_dirigeant":"Ecs.elec95@gmail.com","linkedin_dirigeant":"","site_web":"https://ecs-elec.fr","note_priorite":"Basse","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct + KNX Advanced + HVAC + AJAX Systems. Positionnement : domotique sur mesure IDF. Gamme prix : 30-150k€. Réalisations : maisons + appartements IDF — alarmes NFA2P. Signaux marketing : site SEO local + Trustpilot positif. Siège : Ézanville (95).","sources":"ecs-elec.fr | pagesjaunes.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"DOMÉSIA","ville":"France","zone":"","dirigeant_principal":"Laurent Sapart (Tech AMX/Crestron)","portable_dirigeant":"","telephone":"04 72 17 86 00","email":"","email_dirigeant":"","linkedin_dirigeant":"https://www.linkedin.com/in/laurent-sapart-a9637913/","site_web":"https://www.domesia.fr","note_priorite":"Basse","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"Partenaire AMX + Crestron + Extron. Positionnement : intégration AV + domotique + réseaux. Gamme prix : 50-200k€. Réalisations : projets Lyon + Limonest + Vénissieux. Signaux marketing : site SEO local fort — peu de signaux ads. Siège : 693A impasse Baccot 69210 L'Arbresle.","sources":"domesia.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"OJEA ELECTRONICS","ville":"Suisse","zone":"","dirigeant_principal":"Kevin Ojea Silva (Fondateur & gérant, depuis 2015)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.ojeaelectronics.ch","note_priorite":"Basse","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"Centre de formation KNX certifié — domotique + réseaux + multimédia. Positionnement : Valais + Vaud + Suisse romande. Gamme prix : 50-200k€. Réalisations : villas Valais + chalets. Signaux marketing : Facebook actif + site clean — petite structure. Siège : Route des Iles 62 1897 Bouveret.","sources":"ojeaelectronics.ch | moneyhouse.ch | search.ch"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"JEANFAVRE & FILS SA","ville":"Suisse","zone":"","dirigeant_principal":"Entreprise familiale Jeanfavre","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.jeanfavre.ch","note_priorite":"Basse","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"Domotique + élec traditionnelle + fibre + GTB — entreprise familiale historique Vaud. Positionnement : Vaud + Suisse romande. Gamme prix : 50-200k€. Réalisations : villas Vaud + installations spéciales. Signaux marketing : site institutionnel — branding électricien plus que domoticien luxe pur. Siège : Chemin de Budron B13 1052 Le Mont-sur-Lausanne.","sources":"jeanfavre.ch"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"CS DOMOTIC","ville":"Suisse","zone":"","dirigeant_principal":"Direction non publique","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://csdomotic.ch","note_priorite":"Basse","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"Bureau d'études domotique smart home Suisse romande. Positionnement : Fribourg + Suisse romande. Gamme prix : 50-200k€. Réalisations : résidences Suisse romande. Signaux marketing : site sobre — peu de signaux marketing. Siège : Fribourg.","sources":"csdomotic.ch"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"EASY TECHNOLOGY","ville":"Belgique","zone":"","dirigeant_principal":"Direction non publique","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"https://be.linkedin.com/company/easy-technology-be","site_web":"https://www.easytechnology.be","note_priorite":"Basse","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"Certifié Control4 + KNX universel — domotique + audio/vidéo + télécom + WiFi. Positionnement : Brabant Wallon + Bruxelles. Gamme prix : 30-150k€. Réalisations : appartements + maisons + domaines privés + entreprises. Signaux marketing : site clean — moins luxe pur, plus généraliste premium. Siège : Rue Dries 48 B-1200 Bruxelles (Woluwé-St-Lambert) + Chaumont-Gistoux.","sources":"easytechnology.be | LinkedIn"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"DOMOEXPERT","ville":"Belgique","zone":"","dirigeant_principal":"Direction non publique","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"https://www.linkedin.com/company/domexpert74000/","site_web":"https://www.domoexpert.be","note_priorite":"Basse","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"Domotique Niko Home Control II + Ubiquiti UniFi + Casambi. Positionnement : Bruxelles + Brabant Wallon (particuliers + PME). Gamme prix : 30-150k€. Réalisations : maisons Bruxelles + Brabant. Signaux marketing : site simple — Niko est mid-premium plus que ultra-luxe.","sources":"domoexpert.be | pappers.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Domotique luxe intégrée (Crestron, KNX)","entreprise":"PRORATECH SARL-S","ville":"Luxembourg","zone":"","dirigeant_principal":"Khouchi Abdellah (gérant depuis 2021)","portable_dirigeant":"+352 691 235 469","telephone":"+352 691 235 469","email":"","email_dirigeant":"ak@proratech.lu","linkedin_dirigeant":"https://lu.linkedin.com/in/proratech-sarl-s-094144241","site_web":"https://www.proratech.lu","note_priorite":"Basse","source":"fichier domotique luxe enrichi","statut":"À contacter","data":{"note":"🔥 Mobile direct + KNX + élec générale + IRVE + fibre optique. Positionnement : Luxembourg (3 salariés). Gamme prix : 30-100k€. Réalisations : maisons + petits tertiaires Luxembourg. Signaux marketing : petite structure — peu de signaux premium. Siège : 70-72 rue Muhlenweg L-2155 Luxembourg.","sources":"proratech.lu | europages | LinkedIn"}}

].map(p => ({ qualification: '', date_relance: null, ne_plus_contacter: false, ...p }))
