// Cibles RÉELLES « Golf simulateur indoor » (INDESCALE).
// Importées du mapping spécialiste, 16 cibles FR/CH/BE/LU.
// Liste figée (pas de navigation par ville). Notes denses regroupant positionnement,
// gamme prix, réalisations, signaux marketing. 'n/a' laissé vide (jamais inventé).

let _c = 0
const cid = () => 'golf-' + (++_c)

export const GOLF_SIMULATEUR_PROSPECTS = [
  // ─── PRIORITÉ HAUTE ────────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Golf simulateur indoor","entreprise":"Here We Golf (HWG SARL)","ville":"France","zone":"","dirigeant_principal":"Damien Henaff (gérant) + Caroline Itie (co-fondatrice)","portable_dirigeant":"+33 6 77 99 93 85","telephone":"","email":"","email_dirigeant":"contact@herewegolf.fr","linkedin_dirigeant":"https://linkedin.com/in/damien-henaff-24166a192","site_web":"https://herewegolf.fr","note_priorite":"Haute","source":"fichier golf simulateur enrichi","statut":"À contacter","data":{"note":"🔥 Match parfait acheteurs villas — mobile direct dirigeant + LinkedIn actif. Positionnement : spécialiste installations Trackman/Skytrak à domicile + salle Toulouse. Gamme prix : 15-90k€ (DIY net à high-end Trackman iO turnkey). Réalisations : Trackman iO Home multi-projets résidentiels + salle Toulouse + partenariat ViewSonic. Signaux marketing : site e-commerce fort + blog + LinkedIn actif + cas client ViewSonic. Siège : 1 rue Delacroix 31000 Toulouse.","sources":"Pappers | Mappy | Mentions légales herewegolf.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Golf simulateur indoor","entreprise":"GolfIn France (SimBooth)","ville":"France","zone":"","dirigeant_principal":"Guillaume Perdu (gérant)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://golfin.fr","note_priorite":"Haute","source":"fichier golf simulateur enrichi","statut":"À contacter","data":{"note":"Fabricant FR premium. Positionnement : fabricant français de cabines SimBooth sur-mesure premium (résidentiel + commercial). Gamme prix : 30-80k€ (gammes SimBooth 1/2/4). Réalisations : distribué chez Golf Plus + multiples installations résidentielles France. Signaux marketing : marque produit forte (SimBooth) + distribution via Golf Plus + LinkedIn entreprise actif. Siège : Servon-sur-Vilaine 35530 (Bretagne).","sources":"Societe.com 752999409 | golfinsim.com"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Golf simulateur indoor","entreprise":"EGT - Eden Golf Technologies","ville":"France","zone":"","dirigeant_principal":"Direction EGT (à confirmer Pappers)","portable_dirigeant":"+33 6 12 60 22 23","telephone":"","email":"","email_dirigeant":"info@egolf-tech.com","linkedin_dirigeant":"","site_web":"https://simulateur-golf.com","note_priorite":"Haute","source":"fichier golf simulateur enrichi","statut":"À contacter","data":{"note":"Plus ancien spécialiste FR (depuis 2005) + portable direct publié. Positionnement : multi-marques (AboutGolf, Trackman, Foresight, SkyTrak). Gamme prix : 20-100k€ (DIY → turnkey AboutGolf). Réalisations : distribue AboutGolf en France + installations PACA et France entière. Signaux marketing : site historique + multi-marques + base de fidélité. Siège : 81 chemin de Maraval 83600 Les Adrets-de-l'Estérel (Var).","sources":"simulateur-golf.com | golf-simulateur.com"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Golf simulateur indoor","entreprise":"Addon Golf (Addon Sport SAS)","ville":"France","zone":"","dirigeant_principal":"Romain Pallier (co-dirigeant Addon Golf)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"https://linkedin.com/in/romain-pallier-2349a6100","site_web":"https://addongolf.com","note_priorite":"Haute","source":"fichier golf simulateur enrichi","statut":"À contacter","data":{"note":"Sur-mesure intégral villa + LinkedIn dirigeant joignable. Positionnement : fabricant haut de gamme français (scan 3D + modélisation + écrans/mobilier fabriqués FR). Gamme prix : 40-100k€ (sur-mesure intégral villa). Réalisations : centre indoor à Namur (BE) + installations particuliers FR/BE/CH. Signaux marketing : site EN/FR pro + LinkedIn entreprise actif + Instagram + vocabulaire CSP+++. Siège : 679 rue Le Chatelier 38090 Vaulx-Milieu (Isère). Couvre France + Belgique + Suisse + Espagne + Allemagne.","sources":"annuaire-entreprises.data.gouv.fr SIREN 817582745 | addongolf.com"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Golf simulateur indoor","entreprise":"Beats of Golf","ville":"Belgique","zone":"","dirigeant_principal":"Luk De Meester + Christophe Pape (co-fondateurs - ex-Decathlon golf)","portable_dirigeant":"+32 485 39 88 73","telephone":"+32 485 39 88 73","email":"","email_dirigeant":"info@beatsofgolf.com","linkedin_dirigeant":"https://linkedin.com/in/christophe-pape-58689b43","site_web":"https://beatsofgolf.com","note_priorite":"Haute","source":"fichier golf simulateur enrichi","statut":"À contacter","data":{"note":"🔥 Pipeline B2C CSP+++ déjà actif — Thomas Pieters investisseur. Positionnement : référence indoor golf BE + division Home Golf Studio pour résidentiel sur-mesure. Gamme prix : 30-90k€ (Home Golf Studio multi-marques Trackman/Uneekor/Skytrak/Flightscope). Réalisations : club Anvers 5 boxes + club Hasselt + multiples Home Studios privés. Signaux marketing : presse Libre/Antwerpse Persbureau + LinkedIn entreprise + podcast Golfcultuur. Siège : Noorderlaan 53 2030 Antwerpen.","sources":"beatsofgolf.com/about | La Libre | LinkedIn"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Golf simulateur indoor","entreprise":"Quick Golf Company","ville":"Belgique","zone":"","dirigeant_principal":"Quentin de Valensart (fondateur - ex-pro player)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://quickgolf.be","note_priorite":"Haute","source":"fichier golf simulateur enrichi","statut":"À contacter","data":{"note":"🎯 Accès royauté/UHNW — référence Prince Albert II de Monaco. Positionnement : créateur d'univers golfique (greens synthétiques + simulateurs + events corporate haut de gamme). Gamme prix : 30-100k€ (sur-mesure design intégral). Réalisations : installation Prince Albert II de Monaco + projets résidentiels haut de gamme BE/LU/MC. Signaux marketing : presse Paris Match BE (le Prince Albert) + High Level Com. Siège : Overijse (Belgique).","sources":"parismatch.be | highlevelcom.be"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Golf simulateur indoor","entreprise":"Indoor Golf Partner (IGP)","ville":"France","zone":"","dirigeant_principal":"Direction Danemark (à identifier)","portable_dirigeant":"","telephone":"+45 30 20 65 24","email":"","email_dirigeant":"info@igpartner.dk","linkedin_dirigeant":"","site_web":"https://igpartner.dk","note_priorite":"Haute","source":"fichier golf simulateur enrichi","statut":"À contacter","data":{"note":"Seul partenaire officiel Trackman pour design+installation EMEA — 1500+ installations en 12 ans. Positionnement : Trackman pur turnkey + Flexcages. Gamme prix : 40-120k€. Réalisations : plus de 1500 simulateurs Trackman installés EMEA depuis 12 ans (project leaders locaux FR/BE). Signaux marketing : The Hub Danemark + Trackman branding officiel. Siège : Copenhague, Danemark.","sources":"igpartner.dk"}},

  // ─── PRIORITÉ MOYENNE ──────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Golf simulateur indoor","entreprise":"VGolf Europe","ville":"France","zone":"","dirigeant_principal":"Christophe Muller + Hugo Muller (frères co-fondateurs)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"info@vgolf.eu","linkedin_dirigeant":"https://linkedin.com/in/christophe-muller-aa121014a","site_web":"https://vgolf.eu","note_priorite":"Moyenne","source":"fichier golf simulateur enrichi","statut":"À contacter","data":{"note":"15 ans expertise + showroom Alsace. Positionnement : simulateurs maison + fitting center + partenariat TruGolf E6. Gamme prix : 25-70k€ (installation domicile sur-mesure). Réalisations : showroom Alsace + articles presse régionale + particuliers Grand-Est et CH. Signaux marketing : presse régionale + LinkedIn + Facebook actif. Siège : 1 rue de la Weiss 68125 Houssen + showroom 2 rue de Bâle 68180 Horbourg-Wihr.","sources":"marque.alsace | mentions légales vgolf.eu"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Golf simulateur indoor","entreprise":"Golf and Greens Europe","ville":"Luxembourg","zone":"","dirigeant_principal":"Nicolas (\"Nic\") - dirigeant (nom complet non publié)","portable_dirigeant":"","telephone":"+352 20 600 870","email":"","email_dirigeant":"experts@golfandgreens.eu","linkedin_dirigeant":"https://linkedin.com/company/golfandgreens","site_web":"https://golfandgreens.eu","note_priorite":"Moyenne","source":"fichier golf simulateur enrichi","statut":"À contacter","data":{"note":"Distributeur transfrontalier multi-marques. Positionnement : multi-marques SkyTrak/TruGolf/Foresight GC3/Mevo+ + offre plus accessible que pure-Trackman. Gamme prix : 15-60k€. Réalisations : installations LU/FR/BE résidentielles + commerciales. Signaux marketing : site e-commerce multilingue + LinkedIn actif. Couverture LU/FR/BE/EU (lignes : +352 20 600 870 LU / +33 9 70 44 16 54 FR / +32 2 781 12 32 BE).","sources":"golfandgreens.eu/en/content/4-about-us"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Golf simulateur indoor","entreprise":"LuxGolfHouse","ville":"Luxembourg","zone":"","dirigeant_principal":"Olivier Schmit (PGA Luxembourg)","portable_dirigeant":"","telephone":"+352 26 11 95 05","email":"","email_dirigeant":"","linkedin_dirigeant":"https://linkedin.com/in/olivier-schmit-0b084463","site_web":"https://luxgolfhouse.lu","note_priorite":"Moyenne","source":"fichier golf simulateur enrichi","statut":"À contacter","data":{"note":"Plus grand centre indoor LU (600m²) — vitrine références CSP+++. Positionnement : centre indoor + fitting + pro shop (extension installation domicile à creuser). Gamme prix : centre B2C principalement. Réalisations : centre 600m² Bertrange. Signaux marketing : centre référent LU + Editus + Waze. Siège : 26 Rue de l'Industrie L-8069 Bertrange.","sources":"editus.lu | luxgolfhouse.lu"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Golf simulateur indoor","entreprise":"TPG / Golf at Home","ville":"France","zone":"","dirigeant_principal":"Antoine Leleu (fondateur TPG) + Maxime Kubyn (équipe)","portable_dirigeant":"","telephone":"+33 3 20 09 04 78","email":"","email_dirigeant":"m.kubyn@tpg-golf.com","linkedin_dirigeant":"https://linkedin.com/in/maxime-kubyn-0313b2104","site_web":"https://golfathome.com","note_priorite":"Moyenne","source":"fichier golf simulateur enrichi","statut":"À contacter","data":{"note":"Acteur historique FR équipement golf. Positionnement : équipement golf + branche Golf at Home (simulateurs/practice/putting). Gamme prix : 8-50k€ (e-shop + sur-mesure). Réalisations : équipement de practices clubs + simulateurs domicile + présence Paris Golf Show. Signaux marketing : site e-commerce + Paris Golf Show + LinkedIn entreprise. Siège : 72 Rue des Sureaux 59262 Sainghin-en-Mélantois.","sources":"manageo.fr SIREN 487513848 | tpg-golf.com"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Golf simulateur indoor","entreprise":"Doma Golf / True Spec Europe","ville":"Suisse","zone":"","dirigeant_principal":"Direction Doma Golf SA (à confirmer Moneyhouse)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://domagolf.com","note_priorite":"Moyenne","source":"fichier golf simulateur enrichi","statut":"À contacter","data":{"note":"Accès à la base prospects PRODIGIO via fitting VIP. Positionnement : centres fitting premium + simulateurs Trackman intégrés (4 villes : Genève/Cannes/Paris/Munich) — cible CSP+++ exclusive (pas pur installateur résidentiel mais réseau golfeurs aisés). Gamme prix : fitting + simulateur expérience. Réalisations : studios Genève + Paris (Chavenay) + Cannes + Munich. Signaux marketing : partenariat True Spec USA + presse Golf Business News + Bogeymag. Siège : La Pallanterie Route de Thonon 152C 1222 Vésenaz (Genève).","sources":"domagolf.com | thegolfwire.com"}},

  // ─── PRIORITÉ BASSE ─────────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Golf simulateur indoor","entreprise":"SwingLab Waterloo","ville":"Belgique","zone":"","dirigeant_principal":"Mathieu Herbay (fondateur)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://swinglab.be","note_priorite":"Basse","source":"fichier golf simulateur enrichi","statut":"À contacter","data":{"note":"Activité B2C principalement (location/cours) — extension installation à confirmer. Positionnement : indoor TrackMan haut de gamme + bar (6 simulateurs) — vitrine technique forte. Réalisations : centre 6 simulateurs Trackman Waterloo + partenariats événementiels. Signaux marketing : presse La Libre fév 2026 (offre 25€/18 trous). Siège : 720 Chaussée de Bruxelles Waterloo.","sources":"swinglab.be | La Libre"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Golf simulateur indoor","entreprise":"All In Golf Waterloo","ville":"Belgique","zone":"","dirigeant_principal":"À identifier (Crossroads Bank)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://allingolf.be","note_priorite":"Basse","source":"fichier golf simulateur enrichi","statut":"À contacter","data":{"note":"Principalement B2C centre — installation domicile non mise en avant. Positionnement : club indoor multi-format (simulateurs + putting green + practice) — peu d'angle résidentiel visible. Réalisations : club Waterloo opérationnel. Signaux marketing : site web pro. Siège : Waterloo (à préciser via Crossroads BE).","sources":"allingolf.be"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Golf simulateur indoor","entreprise":"Trackman France (commercial)","ville":"France","zone":"","dirigeant_principal":"Nicolas Tacher (Country Manager FR/BE/LU/CH Romande)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://trackman.com","note_priorite":"Basse","source":"fichier golf simulateur enrichi","statut":"À contacter","data":{"note":"⚠️ MARQUE pas installateur direct — utile comme orchestrateur de partenariats. Positionnement : oriente les leads vers installateurs partenaires = intéressant pour PRODIGIO comme prescripteur. Réalisations : référence partenaires FR/BE/LU/CH Romande. Signaux marketing : force réseau Trackman.","sources":"theorg.com/org/trackman"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Golf simulateur indoor","entreprise":"Foresight Sports Europe (FR)","ville":"France","zone":"","dirigeant_principal":"Rayan Didi (Sales Exec FR) + Raphael Galvani (2026)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"rayan.didi@foresightsports.eu","linkedin_dirigeant":"https://linkedin.com/in/rayan-didi-39489863","site_web":"https://foresightsports.eu","note_priorite":"Basse","source":"fichier golf simulateur enrichi","statut":"À contacter","data":{"note":"⚠️ MARQUE (GCQuad/Falcon) — utile pour mapping dealers. Positionnement : oriente les installateurs résidentiels. Réalisations : réseau dealers FR en construction 2025-2026. Signaux marketing : press release Golf Business News 2025/2026. Siège : Bureau France (basé Sud-Ouest).","sources":"golfbusinessnews.com | foresightsports.eu"}}

].map(p => ({ qualification: '', date_relance: null, ne_plus_contacter: false, ...p }))
