// Cibles RÉELLES « Salle de sport / home gym » (INDESCALE).
// 18 cibles FR/CH/BE/LU. Liste figée. Notes denses regroupant positionnement, gamme prix,
// réalisations, signaux marketing. 'n/a' laissé vide (jamais inventé).

let _c = 0
const cid = () => 'gym-' + (++_c)

export const HOME_GYM_PROSPECTS = [
  // ─── PRIORITÉ HAUTE ────────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Salle de sport / home gym","entreprise":"Exclusive Fit","ville":"France","zone":"","dirigeant_principal":"Rémy & Benoît Bourcier (frères co-gérants)","portable_dirigeant":"","telephone":"04 83 88 33 30","email":"","email_dirigeant":"contact@exclusive-fit.fr","linkedin_dirigeant":"https://fr.linkedin.com/company/exclusive-fit","site_web":"https://exclusive-fit.com","note_priorite":"Haute","source":"fichier home gym enrichi","statut":"À contacter","data":{"note":"🔥 BEST-FIT ABSOLU — acheteurs CSP+++ identiques à PRODIGIO. Positionnement : Sport & Wellness designer haut de gamme, architecture intérieure fitness, showrooms Cannes/Monaco/Saint-Barth. Gamme prix : 30k-150k€+ projet. Réalisations : MareTerra Monaco / Le Mirabeau / Le Stella / SBM Monaco / yachts privés. Signaux marketing : très forte présence digitale, Instagram + site éditorial + Côte Magazine + 3 showrooms premium. Siège : 8 Av Saint Jean 06400 Cannes.","sources":"Exclusive Fit | Pappers | Côte Magazine"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Salle de sport / home gym","entreprise":"Inteam Développement","ville":"France","zone":"","dirigeant_principal":"Tangi David (Président-fondateur) + Christelle David","portable_dirigeant":"06 61 94 42 50","telephone":"09 73 89 05 14","email":"","email_dirigeant":"contact@inteam.fr","linkedin_dirigeant":"https://fr.linkedin.com/in/tangi-david-353a464a","site_web":"https://www.inteam.fr","note_priorite":"Haute","source":"fichier home gym enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct + N°1 conception fitness France. Positionnement : conception fitness sur-mesure design + équipement + suites luxe hôtels. Gamme prix : 20k-100k€+ projet. Réalisations : suites hôtels 5* / home gyms Monaco / centres performance. Signaux marketing : site éditorial fort + LinkedIn actif Tangi David + presse. Siège : 304 A Route d'Alix 69380 Châtillon (Beaujolais).","sources":"Inteam.fr | Pappers | LinkedIn Tangi David"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Salle de sport / home gym","entreprise":"RAKK","ville":"France","zone":"","dirigeant_principal":"Théo Cannière (DG fondateur) & Hugo de Francesco (cofondateur)","portable_dirigeant":"","telephone":"09 80 80 11 41","email":"","email_dirigeant":"contact@rakk.fr","linkedin_dirigeant":"https://www.linkedin.com/in/théo-cannière-491b5225a/","site_web":"https://www.rakk.fr","note_priorite":"Haute","source":"fichier home gym enrichi","statut":"À contacter","data":{"note":"1500+ home gyms installés + deux fondateurs jeunes même hub géo que Mitja. Positionnement : home gym sur-mesure clé en main pour particuliers et entreprises (3D + installation). Gamme prix : 15k-80k€ projet. Réalisations : 1500+ home gyms installés / clients sport pro et entreprises. Signaux marketing : Instagram +50k followers + Facebook actif + BFM Business + contenu fort. Siège : 11 Rue Gutenberg 06000 Nice.","sources":"RAKK.fr | Pappers | Infonet"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Salle de sport / home gym","entreprise":"MC Protech","ville":"France","zone":"","dirigeant_principal":"Cheikh Thioub (DG cofondateur) + Magid Ouchène + Nicolas Benezet (Président)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"contact@mcprotech.com","linkedin_dirigeant":"https://www.linkedin.com/in/cheikh-thioub-2710b1204/","site_web":"https://mcprotech.com","note_priorite":"Haute","source":"fichier home gym enrichi","statut":"À contacter","data":{"note":"🎯 Notoriété Messi/Benzema = clientèle ultra-CSP+++. Positionnement : home gym pro pour footballeurs et particuliers fortunés (équipement custom premium). Gamme prix : 25k-100k€+. Réalisations : home gyms Messi/Benzema/Fabregas/Fekir/Thuram/Hernandez/Mané/Barcola/Bellegarde. Signaux marketing : très forte notoriété sport pro + Canal+ reportage + Instagram solide + presse régionale. Siège : 30620 Bernis (Gard).","sources":"MCProtech.com | Objectif Gard | Pappers"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Salle de sport / home gym","entreprise":"Sport Protech","ville":"France","zone":"","dirigeant_principal":"Yann Obitz (cofondateur) + Florian Rivet (cofondateur)","portable_dirigeant":"","telephone":"04 37 28 98 61","email":"","email_dirigeant":"contact@sport-protech.com","linkedin_dirigeant":"https://fr.linkedin.com/company/sport-protech","site_web":"https://www.sport-protech.com","note_priorite":"Haute","source":"fichier home gym enrichi","statut":"À contacter","data":{"note":"N°1 français protection corporelle + nouvelle activité home gym athlètes haut niveau. Positionnement : home gym clé en main athlètes haut niveau. Gamme prix : 20k-80k€. Réalisations : home gyms footballeurs pro (Sylla / Barcola) / clubs / particuliers. Signaux marketing : YouTube actif + presse + Instagram + influence sport pro. Siège : 3 rue Pierre Devaux 69360 Sérézin-du-Rhône.","sources":"Sport-Protech.com | monfoot69"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Salle de sport / home gym","entreprise":"Fitspro Equipement","ville":"Suisse","zone":"","dirigeant_principal":"Fred Gall + Isabelle Gall (gérants)","portable_dirigeant":"079 950 26 63","telephone":"022 779 10 62","email":"","email_dirigeant":"fred@fitspro.com","linkedin_dirigeant":"","site_web":"https://www.fitsproequipement.ch","note_priorite":"Haute","source":"fichier home gym enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct + email perso + même territoire CH romande que chalets/villas PRODIGIO. Positionnement : leader Suisse romande aménagement home gym et clubs (10 ans expérience). Gamme prix : 20k-80k€. Réalisations : home gyms résidences Genève / clubs / hôtels. Signaux marketing : LinkedIn + lien fort avec école Fitspro formation. Siège : 243 Route des Fayards 1290 Versoix (canton Genève).","sources":"Fitsproequipement.ch | Ader-Versoix"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Salle de sport / home gym","entreprise":"SportAddict Service","ville":"Suisse","zone":"","dirigeant_principal":"Sylvain Palermo (CEO) + Jonathan (DAF)","portable_dirigeant":"","telephone":"+41 58 255 28 99","email":"","email_dirigeant":"service-client@sportaddict.ch","linkedin_dirigeant":"https://ch.linkedin.com/in/sylvainpalermo","site_web":"https://sportaddict-service.ch","note_priorite":"Haute","source":"fichier home gym enrichi","statut":"À contacter","data":{"note":"PME suisse 10 ans + LinkedIn CEO actif. Positionnement : design espaces fitness sur-mesure résidentiel + pro suisse. Gamme prix : 20k-80k€. Réalisations : home gyms copropriétés et résidentiels Suisse + kinésithérapie + arts martiaux. Signaux marketing : LinkedIn CEO actif (Sylvain Palermo) + Facebook Gland + landing page dédiée. Siège : Route des Avouillons 16 1196 Gland (VD).","sources":"SportAddict.ch | LinkedIn Sylvain Palermo"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Salle de sport / home gym","entreprise":"InstalFit","ville":"Luxembourg","zone":"","dirigeant_principal":"Direction non publique (40 ans expérience)","portable_dirigeant":"","telephone":"+352 42 30 32 1","email":"","email_dirigeant":"info@instalfit.lu","linkedin_dirigeant":"https://lu.linkedin.com/company/instalfit","site_web":"https://www.instalfit.lu","note_priorite":"Haute","source":"fichier home gym enrichi","statut":"À contacter","data":{"note":"N°1 Home Wellness Luxembourg 40 ans + distributeur Technogym. Positionnement : distributeur Technogym + pools/spas + home gym premium villas Lux. Gamme prix : 30k-150k€. Réalisations : villas Luxembourg + résidences Kirchberg + châteaux. Signaux marketing : site éditorial fort + Editus + LinkedIn entreprise. Siège : 7c rue de Bitbourg L-1273 Luxembourg-Hamm. ⚠️ AUSSI dans catégorie Spa intérieur / hammam / piscine intérieure (overlap).","sources":"Instalfit.lu | Editus.lu"}},

  // ─── PRIORITÉ MOYENNE ──────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Salle de sport / home gym","entreprise":"Athletica Design","ville":"France","zone":"","dirigeant_principal":"Matthias & Laurie (cofondateurs)","portable_dirigeant":"06 45 56 57 58","telephone":"","email":"","email_dirigeant":"contact@athletica-design.com","linkedin_dirigeant":"","site_web":"http://www.athletica-design.com","note_priorite":"Moyenne","source":"fichier home gym enrichi","statut":"À contacter","data":{"note":"Portable direct + Houzz pro 4.9/5 (59 avis). Positionnement : designer dédié salles de sport résidentielles + Fitness Cube extension de maison. Gamme prix : 30k-120k€. Réalisations : home gyms scandinave Bordeaux / Fitness Cube / extensions design. Signaux marketing : Houzz pro 4.9/5 + portfolio fort. Siège : Le Bouscat 33110 (Gironde).","sources":"Houzz | Athletica-design.com"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Salle de sport / home gym","entreprise":"Light In Fitness","ville":"France","zone":"","dirigeant_principal":"Michaël Galy (fondateur-directeur)","portable_dirigeant":"06 20 72 66 96","telephone":"","email":"","email_dirigeant":"contact@lightinfitness.com","linkedin_dirigeant":"https://fr.linkedin.com/in/mickaelgaly","site_web":"https://lightinfitness.com","note_priorite":"Moyenne","source":"fichier home gym enrichi","statut":"À contacter","data":{"note":"Portable direct fondateur + 500+ établissements équipés en 12 ans. Positionnement : expert fitness pro + résidences haut de gamme. Gamme prix : 15k-80k€. Réalisations : hôtels 4-5* / résidences premium / clubs / collectivités. Signaux marketing : site éditorial très fort + blog SEO + LinkedIn Michaël actif. Siège : 6-8 rue Victor Laloux 37000 Tours.","sources":"Lightinfitness.com | LinkedIn"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Salle de sport / home gym","entreprise":"FIT' & RACK","ville":"France","zone":"","dirigeant_principal":"Xavier Anton & Florent Camisuli (co-gérants ingénieurs)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"contact@fitandrack.com","linkedin_dirigeant":"https://www.linkedin.com/in/xavier-anton-1642081b6/","site_web":"https://www.fitandrack.com","note_priorite":"Moyenne","source":"fichier home gym enrichi","statut":"À contacter","data":{"note":"100% Made in France depuis 2014. Positionnement : concepteur custom racks et home gyms. Gamme prix : 15k-60k€. Réalisations : home gyms / garage gyms / coachs / clubs. Signaux marketing : LinkedIn cofondateurs actifs + presse In Extenso + Instagram. Siège : 10 Chemin du Chêne 69380 Civrieux-d'Azergues.","sources":"FitandRack.com | Pappers | LinkedIn"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Salle de sport / home gym","entreprise":"Powergym France","ville":"France","zone":"","dirigeant_principal":"Alexandre Rusch (gérant cofondateur)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"powergym@powergym.fr","linkedin_dirigeant":"","site_web":"https://www.powergym.fr","note_priorite":"Moyenne","source":"fichier home gym enrichi","statut":"À contacter","data":{"note":"Leader home gym équipement Pro + shop n°1 ATX FR. Positionnement : configuration sur-mesure ATX premium. Gamme prix : 10k-50k€. Réalisations : home gyms particuliers / configurations sur-mesure. Signaux marketing : site SEO fort / France Bleu / SuperPhysique podcast. Siège : 18 Rue des 2 Ponts 18230 Saint-Doulchard + 6 Rue Maurice Roy 18000 Bourges.","sources":"Powergym.fr | Pappers | societe.com"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Salle de sport / home gym","entreprise":"Sport Protech Gymconcept","ville":"France","zone":"","dirigeant_principal":"Yann Obitz / Florian Rivet (groupe Sport Protech)","portable_dirigeant":"","telephone":"04 37 28 98 61","email":"","email_dirigeant":"contact@sport-protech.com","linkedin_dirigeant":"","site_web":"https://www.sport-protech.com/gymconcept","note_priorite":"Moyenne","source":"fichier home gym enrichi","statut":"À contacter","data":{"note":"Branche dédiée home gym design du groupe Sport Protech. Positionnement : clé en main athlètes. Gamme prix : 30k-100k€. Réalisations : home gyms football pro. Signaux marketing : capitalise sur notoriété Sport Protech. Siège : Sérézin-du-Rhône (entité dédiée gym design).","sources":"Annuaire entreprises | Sport-Protech.com"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Salle de sport / home gym","entreprise":"Technogym Boutique Zürich","ville":"Suisse","zone":"","dirigeant_principal":"Manager local Technogym CH","portable_dirigeant":"","telephone":"+41 43 558 98 60","email":"","email_dirigeant":"","linkedin_dirigeant":"https://www.linkedin.com/company/technogym","site_web":"https://www.technogym.com/en-CH/technogym-zurich","note_priorite":"Moyenne","source":"fichier home gym enrichi","statut":"À contacter","data":{"note":"Marque mondiale + Interior Design service home gyms luxe. Positionnement : flagship Technogym CH + délégation Suisse romande. Gamme prix : 30k-200k€. Réalisations : villas Zürich / chalets Verbier Gstaad / résidences. Signaux marketing : marque mondiale + site CH dédié + showroom 120m². Siège : Pelikanstrasse 5 8001 Zürich.","sources":"Technogym.com CH"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Salle de sport / home gym","entreprise":"Rêv'extérieur","ville":"Luxembourg","zone":"","dirigeant_principal":"Régis Hofmann (associé clé)","portable_dirigeant":"","telephone":"+352 277 602 40","email":"","email_dirigeant":"contact@revexterieur.lu","linkedin_dirigeant":"https://www.linkedin.com/in/régis-hofmann-rêv'extérieur-luxembourg-6b462688/","site_web":"https://www.revexterieur.lu","note_priorite":"Moyenne","source":"fichier home gym enrichi","statut":"À contacter","data":{"note":"Showroom 300m² wellness premium + LinkedIn Régis Hofmann actif. Positionnement : équipements fitness/cardio design + spa. Gamme prix : 20k-100k€. Réalisations : spas + home gyms résidentiels Bertrange / Howald. Signaux marketing : LinkedIn Régis Hofmann actif + showroom physique 300m². Siège : 272 Route de Thionville L-5884 Howald. ⚠️ AUSSI dans catégorie Spa intérieur (overlap).","sources":"Revexterieur.lu | LinkedIn"}},

  // ─── PRIORITÉ BASSE ─────────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Salle de sport / home gym","entreprise":"Incept Sport","ville":"France","zone":"","dirigeant_principal":"Équipe commerciale","portable_dirigeant":"","telephone":"01 46 49 10 80","email":"","email_dirigeant":"info@incept-sport.fr","linkedin_dirigeant":"","site_web":"https://www.incept-sport.fr","note_priorite":"Basse","source":"fichier home gym enrichi","statut":"À contacter","data":{"note":"Distributeur officiel Concept2 + Wattbike France 38 ans. Positionnement : équipement premium. Gamme prix : 5k-30k€ équipement. Réalisations : hôtels / résidences premium / clubs pro / sportifs élite. Signaux marketing : site spécialisé + Facebook + référent Hyrox. Siège : 190 Rue d'Estienne d'Orves 92700 Colombes.","sources":"Incept-Sport.fr | Facebook"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Salle de sport / home gym","entreprise":"Arcae Studio","ville":"France","zone":"","dirigeant_principal":"Direction non publique","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"http://www.athletica-design.com/arcae","note_priorite":"Basse","source":"fichier home gym enrichi","statut":"À contacter","data":{"note":"Studio archi+design dédié salles sport luxe + hôtels + résidences VIP. Positionnement : Signature. Gamme prix : 40k-150k€+. Réalisations : espaces fitness Signature hôtels / résidences privées. Signaux marketing : presse archi (IDEAT / journal du luxe) — faible présence digitale propre. Siège : Paris (adresse non publiée).","sources":"Crea-home.fr | IDEAT"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Salle de sport / home gym","entreprise":"Pent Fitness (distribution)","ville":"France","zone":"","dirigeant_principal":"Marek Bigas (fondateur Pologne)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"contact@pentfitness.com","linkedin_dirigeant":"","site_web":"https://www.pentfitness.com","note_priorite":"Basse","source":"fichier home gym enrichi","statut":"À contacter","data":{"note":"⚠️ Marque distribution Europe (HQ Pologne) — pas hub FR/CH/BE/LU officiel. Positionnement : marque luxury fitness handcrafted bois/cuir/inox. Gamme prix : 30k-100k€ équipement seul. Réalisations : yachts / villas / hôtels palaces / chalets Verbier. Signaux marketing : très forte présence Instagram + AD/IDEAT + revendeurs architectes.","sources":"Pentfitness.com | Modern Furnishings | Iron House"}}

].map(p => ({ qualification: '', date_relance: null, ne_plus_contacter: false, ...p }))
