// Cibles RÉELLES « Lieux de réception / domaines / châteaux » (INDESCALE).
// 27 cibles FR/CH/BE/LU. Liste figée. Notes denses regroupant positionnement, gamme prix,
// réalisations, signaux marketing. 'n/a' laissé vide (jamais inventé).
// Spécificité : portables 06/07 quasi-introuvables (SCI/SCEA familiales + corporate Oetker/Airelles).

let _c = 0
const cid = () => 'lieu-' + (++_c)

export const LIEUX_RECEPTION_PROSPECTS = [
  // ─── PRIORITÉ HAUTE ────────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Château La Coste","ville":"France","zone":"","dirigeant_principal":"Paddy McKillen (propriétaire) + Daniel Kennedy (Art Director)","portable_dirigeant":"","telephone":"+33 4 42 61 92 90","email":"","email_dirigeant":"events@chateau-la-coste.com","linkedin_dirigeant":"","site_web":"https://chateau-la-coste.com","note_priorite":"Haute","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"🔥 UHNW absolu — McKillen, fort branding art = angle Mitja parfait. Positionnement : domaine art+architecture+vin 200ha — Villa La Coste 28 villas — capacité outdoor jusqu'à 2000 pax. Gamme prix : 40-150k€ (privatisation Villa La Coste + château). Réalisations : mariages célébrités HNW internationales (US/UK). Signaux marketing : Insta 380k+ + presse Vogue Architectural Digest + pas d'ads visibles. Siège : 750 Route de la Cride, 13610 Le Puy-Sainte-Réparade (Provence Aix).","sources":"Château La Coste | Irish Times | Indagare"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Domaine de Verchant","ville":"France","zone":"","dirigeant_principal":"Pierre & Chantal Mestre (propriétaires fondateurs Orchestra-Premaman) - DG Gérald Van Reck","portable_dirigeant":"","telephone":"+33 4 67 07 26 00","email":"","email_dirigeant":"reservations@domainedeverchant.com","linkedin_dirigeant":"https://linkedin.com/in/gerald-van-reck","site_web":"https://domainedeverchant.com","note_priorite":"Haute","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"🔥 Pierre Mestre entrepreneur Orchestra-Premaman = profil PRODIGIO idéal + déjà mappé côté viticole = double angle. Positionnement : Relais & Châteaux 5* — vignoble — salle 280m² + terrasse cristal 200m² — 200+ pax assis. Gamme prix : 30-80k€. Réalisations : mariages Sud France HNW + corporate Montpellier. Signaux marketing : Insta 60k + presse Côté Sud + partenariat Vogue Wedding. Siège : Mas de Verchant, 34170 Castelnau-le-Lez.","sources":"Pappers | mapping viticole Rayyân"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Château Saint-Martin & Spa (Oetker Collection)","ville":"France","zone":"","dirigeant_principal":"Maja Oetker (famille propriétaire) - DG Christian Clerc (Oetker Collection)","portable_dirigeant":"","telephone":"+33 4 93 58 02 02","email":"","email_dirigeant":"reservations@chateau-st-martin.com","linkedin_dirigeant":"","site_web":"https://oetkerhotels.com/chateau-saint-martin","note_priorite":"Haute","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"Groupe corporate Oetker — chemin via DG site (pas via groupe). Positionnement : Relais & Châteaux 14ha Vence — chapelle 12e siècle — 52 chambres pour weekend mariage. Gamme prix : 80-200k€ (privatisation hôtel + cérémonie). Réalisations : weddings US/Russie/Moyen-Orient haute société. Signaux marketing : Insta 35k + presse Condé Nast + Forbes 5 stars. Siège : 2490 Avenue des Templiers, 06140 Vence (Côte d'Azur).","sources":"Oetker Hotels | Tourmag"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Château de Bagnols","ville":"France","zone":"","dirigeant_principal":"Jean-Claude Lavorel (propriétaire 2011 - Lavorel Hôtels)","portable_dirigeant":"","telephone":"+33 4 74 71 40 00","email":"","email_dirigeant":"info@chateaudebagnols.com","linkedin_dirigeant":"https://linkedin.com/in/jean-claude-lavorel","site_web":"https://chateaudebagnols.com","note_priorite":"Haute","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"🔥 Lavorel = entrepreneur Lyon + exclusivité totale = ticket très élevé. Positionnement : château 13e siècle classé MH — exclusivité totale uniquement — 150 pax — jardins français. Gamme prix : 80-200k€ (exclusivité weekend). Réalisations : mariages international UHNW + corporate Lyon/Genève. Signaux marketing : Insta 40k + Worldwide Escapes + sélection Tatler. Siège : Le Bourg, 69620 Bagnols (Beaujolais).","sources":"Château de Bagnols | Lyon Tourist Office"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Château d'Estoublon (Airelles)","ville":"France","zone":"","dirigeant_principal":"Stéphane Courbit + Jean-Guillaume Prats + Nicolas/Carla Sarkozy (actionnaires)","portable_dirigeant":"","telephone":"+33 4 90 54 64 00","email":"","email_dirigeant":"events@estoublon.com","linkedin_dirigeant":"https://linkedin.com/in/jean-guillaume-prats","site_web":"https://estoublon.com","note_priorite":"Haute","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"🔥 Courbit + Sarkozy + Prats (ex-LVMH) = network or — pitch via Prats. Positionnement : domaine 300ha vignes+oliviers — 10 chambres+suites — privatisation totale. Gamme prix : 50-150k€ (privatisation domaine). Réalisations : mariages people / Sarkozy network / Bordeaux Prats. Signaux marketing : Insta 90k + presse Madame Figaro Vogue + mariage Courbit. Siège : Route de Maussane, 13990 Fontvieille (Alpilles).","sources":"Decanter | Wikipedia"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Airelles Bastide de Gordes","ville":"France","zone":"","dirigeant_principal":"Stéphane Courbit (propriétaire groupe Airelles) - DG site Lionel Servant","portable_dirigeant":"","telephone":"+33 4 90 72 12 12","email":"","email_dirigeant":"reservations.gordes@airelles.com","linkedin_dirigeant":"https://linkedin.com/in/lionel-servant","site_web":"https://airelles.com/destination/gordes-hotel","note_priorite":"Haute","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"Palace 5* 16e siècle ramparts Gordes — 40 ch + spa Guerlain — capacité 180 pax. Gamme prix : 90-250k€ (privatisation à partir de 90k€). Réalisations : mariages célébrités cinéma/luxe + destination weddings US. Signaux marketing : Insta 100k+ + pub permanente Vogue + pas d'ads perfo. Siège : Rue de la Combe, 84220 Gordes (Luberon).","sources":"Airelles | FrenchWeddingStyle"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Domaine de Manville","ville":"France","zone":"","dirigeant_principal":"Société RMC (Président SAS)","portable_dirigeant":"","telephone":"+33 4 90 54 40 20","email":"","email_dirigeant":"reservations@domainedemanville.fr","linkedin_dirigeant":"","site_web":"https://domainedemanville.fr","note_priorite":"Haute","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"Relais & Châteaux 5* — 30 ch + 9 maisons hôtes + golf 18T + spa — capacité 300 pax. Gamme prix : 30-90k€ (privatisation événementielle). Réalisations : mariages très haut de gamme parisien/international. Signaux marketing : Insta 50k + presse Tatler Brides + Vogue. Siège : Domaine de Manville, 13520 Les Baux-de-Provence (Alpilles).","sources":"Domaine de Manville | Pappers"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Château de Berne","ville":"France","zone":"","dirigeant_principal":"Mark Dixon (propriétaire - fondateur Regus/IWG)","portable_dirigeant":"","telephone":"+33 4 94 60 43 60","email":"","email_dirigeant":"info@chateauberne.com","linkedin_dirigeant":"https://linkedin.com/in/mark-dixon-iwg","site_web":"https://chateauberne.com","note_priorite":"Haute","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"Mark Dixon (Regus) entrepreneur = profil PRODIGIO idéal. Positionnement : Relais & Châteaux 5* — vignoble + amphithéâtre 500 places — salles 230m² et 288m² — 130 pax assis. Gamme prix : 40-120k€. Réalisations : mariages internationaux + corporate luxury brands. Signaux marketing : Insta 80k + presse Wine Spectator Forbes + ads Meta visibles été. Siège : Chemin des Imberts, 83780 Flayosc (Provence Var).","sources":"Wine Spectator | Rayon Boissons"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Château Saint Pierre de Serjac","ville":"France","zone":"","dirigeant_principal":"Karl O'Hanlon + Laurent Bonfils (propriétaires) - DG Jérôme Bonfils (Domaines Bonfils)","portable_dirigeant":"","telephone":"+33 4 67 32 35 78","email":"","email_dirigeant":"events@serjac.com","linkedin_dirigeant":"https://linkedin.com/in/jerome-bonfils","site_web":"https://serjac.com","note_priorite":"Haute","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"Groupe Domaine & Demeure (Bonfils + O'Hanlon) opère aussi Capitoul = pitch unique à 2 lieux. Positionnement : Château 19e restauré — 102 ch (36 maisons + 8 suites) — spa — capacité 190 pax — turnkey wedding planner. Gamme prix : 15-50k€. Réalisations : mariages UK/Irish/Scandinaves haut de gamme. Signaux marketing : Insta 25k + présent Mariages.net premium + pas d'ads visibles. Siège : 34480 Puissalicon (Hérault Béziers).","sources":"Pappers | FrenchWeddingStyle"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Le Domaine du Mas de Pierre","ville":"France","zone":"","dirigeant_principal":"Famille propriétaire indépendante","portable_dirigeant":"","telephone":"+33 4 93 59 00 10","email":"","email_dirigeant":"info@lemasdepierre.com","linkedin_dirigeant":"","site_web":"https://lemasdepierre.com","note_priorite":"Haute","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"5* Resort & Spa — 76 ch privatisables (min 2 nuits) — 3 salons modulables 180m² — 160 pax. Gamme prix : 40-120k€. Réalisations : mariages UHNW Côte d'Azur + anniversaires haut de gamme. Signaux marketing : Insta 30k + presse Conde Nast + pas d'ads perfo. Siège : 2320 Route des Serres, 06570 Saint-Paul-de-Vence.","sources":"Le Mas de Pierre | ABC Salles"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Château de Tourreau","ville":"France","zone":"","dirigeant_principal":"Propriétaire privé (location villa luxe - Sotheby's / Le Collectionist)","portable_dirigeant":"","telephone":"+33 4 90 65 56 22","email":"","email_dirigeant":"info@chateaudetourreau.com","linkedin_dirigeant":"","site_web":"https://chateaudetourreau.com","note_priorite":"Haute","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"Château 1612 + chapelle consacrée — 9 suites + 6 salons 850m² — privatisation totale — 120 pax. Gamme prix : 40-100k€ (privatisation 3-7 nuits). Réalisations : destination weddings UK/US + célébrités. Signaux marketing : Insta 15k + French Wedding Style + Mas Amor distribution. Siège : Chemin des Genêts, 84260 Sarrians (Provence Vaucluse).","sources":"French Wedding Style | Aix and Provence Luxury"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Abbaye de Talloires","ville":"France","zone":"","dirigeant_principal":"Famille Tiffenat (exploitation historique)","portable_dirigeant":"","telephone":"+33 4 50 60 77 33","email":"","email_dirigeant":"info@abbaye-talloires.com","linkedin_dirigeant":"","site_web":"https://abbaye-talloires.com","note_priorite":"Haute","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"Hôtel 4* abbaye 17e bord du lac — 37 ch — 200 pax. Gamme prix : 20-60k€. Réalisations : mariages Genève + Lyon + international UHNW (vue lac). Signaux marketing : Insta 18k + Christopher Simonne + pas d'ads. Siège : Chemin des Moines, 74290 Talloires-Montmin (Haute-Savoie Lac d'Annecy).","sources":"Smart Moments | Abbaye Talloires"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Hôtel Château de la Chèvre d'Or","ville":"France","zone":"","dirigeant_principal":"Famille Wolff propriétaire (5 ch + restos Michelin)","portable_dirigeant":"","telephone":"+33 4 92 10 66 66","email":"","email_dirigeant":"sales@chevredor.com","linkedin_dirigeant":"","site_web":"https://chevredor.com","note_priorite":"Haute","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"🔥 Vue mer iconique Èze — clientèle Monaco/Russie/Asie. Positionnement : Relais & Châteaux 5* nid d'aigle médiéval Èze — capacité 80 pax max. Gamme prix : 40-150k€ (cérémonie 2k-3,5k€ + dîner 125-240€/pax). Réalisations : mariages UHNW Monaco/Russie/Asie. Signaux marketing : Insta 80k + Vogue Brides + presse internationale. Siège : Rue du Barri, 06360 Èze (Côte d'Azur).","sources":"Chèvre d'Or | R&C"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Portes des Iris (Château de Vullierens)","ville":"Suisse","zone":"","dirigeant_principal":"Famille Bovy (propriétaire historique Vullierens)","portable_dirigeant":"","telephone":"+41 21 869 88 88","email":"","email_dirigeant":"info@portesdesiris.ch","linkedin_dirigeant":"","site_web":"https://portesdesiris.ch","note_priorite":"Haute","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"6 salles 700 assis / terrasses 1600 pax — jardins iris célèbres — agréé cérémonies civiles. Gamme prix : 20-60k CHF. Réalisations : corporate Genève/Lausanne + mariages destination. Signaux marketing : Insta 15k + partenariats Suisse Tourisme. Siège : Route des Iris, 1115 Vullierens (Vaud).","sources":"Portes des Iris | Suisse Tourisme"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Domaine de Châteauvieux","ville":"Suisse","zone":"","dirigeant_principal":"Philippe Chevrier (propriétaire depuis 1989 - Chef 2 étoiles Michelin 19/20)","portable_dirigeant":"","telephone":"+41 22 753 15 11","email":"","email_dirigeant":"info@chateauvieux.ch","linkedin_dirigeant":"https://linkedin.com/in/philippe-chevrier-chef","site_web":"https://chateauvieux.ch","note_priorite":"Haute","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"🔥 Chef 2* Michelin + Relais & Châteaux. Positionnement : 19/20 Gault Millau — vue Rhône+Jura — vignobles Genève. Gamme prix : 15-50k CHF. Réalisations : mariages gastronomiques HNW Genève + corporate Big4/banques. Signaux marketing : Insta 25k + R&C + Les Grandes Tables du Monde. Siège : 16 Chemin de Châteauvieux, 1242 Peney-Dessus (Satigny Genève).","sources":"Chateauvieux.ch | Wikipedia"}},

  // ─── PRIORITÉ MOYENNE ──────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Château de Mercuès","ville":"France","zone":"","dirigeant_principal":"Georges Vigouroux (propriétaire depuis 1983 - famille viticole)","portable_dirigeant":"","telephone":"+33 5 65 20 00 01","email":"","email_dirigeant":"mercues@relaischateaux.com","linkedin_dirigeant":"","site_web":"https://chateaudemercues.com","note_priorite":"Moyenne","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"Relais & Châteaux 4* — résidence Comtes-Évêques 7 siècles — restaurant Michelin — 100 pax. Gamme prix : 20-60k€. Réalisations : mariages Sud-Ouest + Bordeaux + Toulouse + corporate vin. Signaux marketing : Insta 20k + Relais & Châteaux + Gault Millau. Siège : 46090 Mercuès (Cahors Lot).","sources":"Wikipedia | R&C"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Le Mas des Herbes Blanches","ville":"France","zone":"","dirigeant_principal":"Direction site (groupe Beaumier)","portable_dirigeant":"","telephone":"+33 4 90 05 79 79","email":"","email_dirigeant":"reservation@herbesblanches.com","linkedin_dirigeant":"","site_web":"https://herbesblanches.com","note_priorite":"Moyenne","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"Relais & Châteaux 5* — 48 ch — capacité 330 pax cocktail / 150 dansante. Gamme prix : 25-70k€. Réalisations : mariages international + corporate luxury. Signaux marketing : Insta 35k + Relais & Châteaux marketing centralisé. Siège : Route de Murs, 84220 Joucas (Luberon).","sources":"ABC Salles | R&C"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Château d'Augerville (Les Collectionneurs)","ville":"France","zone":"","dirigeant_principal":"Direction site (Les Collectionneurs réseau)","portable_dirigeant":"","telephone":"+33 2 38 32 12 07","email":"","email_dirigeant":"reservations@chateau-augerville.com","linkedin_dirigeant":"","site_web":"https://chateau-augerville.com","note_priorite":"Moyenne","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"5* Golf 18T + Spa 620m² — 40 ch — salle 330m² climatisée — 200 pax — 80km Paris. Gamme prix : 15-50k€. Réalisations : mariages parisiens haut de gamme + corporate finance. Signaux marketing : Insta 12k + Les Collectionneurs + ads Meta IDF visibles. Siège : Place du Château, 45330 Augerville-la-Rivière (Loiret).","sources":"1001Salles | Wikipedia"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Château de Vault-de-Lugny","ville":"France","zone":"","dirigeant_principal":"Famille Bourzeix (propriétaire depuis 1967)","portable_dirigeant":"","telephone":"+33 3 86 34 07 86","email":"","email_dirigeant":"info@lugny.fr","linkedin_dirigeant":"","site_web":"https://lugny.fr","note_priorite":"Moyenne","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"5* douves — 80ha — 16 ch — restaurant gastro — château intime. Gamme prix : 15-50k€. Réalisations : mariages intimistes 30-80 pax + corporate haut de gamme. Signaux marketing : Insta 8k + Yonder + Maisons & Jardins. Siège : 11 rue du Château, 89200 Vault-de-Lugny (Bourgogne Vézelay-Chablis).","sources":"Bourgogne Tourisme | Yonder"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Hostellerie La Briqueterie (Beauvallon)","ville":"France","zone":"","dirigeant_principal":"Alix Philipon (rénovation depuis 2004) - groupe Beauvallon","portable_dirigeant":"","telephone":"+33 3 26 59 99 99","email":"","email_dirigeant":"reservations@labriqueterie.fr","linkedin_dirigeant":"https://linkedin.com/in/alix-philipon","site_web":"https://hostellerielabriqueterie.com","note_priorite":"Moyenne","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"Relais & Châteaux 5* — 40 ch + spa — vignobles Champagne — 1 étoile Michelin (Nawal Rezagui). Gamme prix : 20-60k€. Réalisations : mariages Paris + corporate maisons Champagne. Signaux marketing : Insta 12k + Tatler + R&C network. Siège : 4 Route de Sézanne, 51530 Vinay (Champagne Vinay).","sources":"R&C | Maison et Jardins Actuels"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Château de Mille","ville":"France","zone":"","dirigeant_principal":"Propriétaire privé (vignoble historique Luberon)","portable_dirigeant":"","telephone":"+33 4 90 74 11 94","email":"","email_dirigeant":"contact@chateau-de-mille.com","linkedin_dirigeant":"","site_web":"https://chateau-de-mille.com","note_priorite":"Moyenne","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"Plus ancien vignoble Luberon — privatisation 2-3 jours — 8 ch château + 2 gîtes — 150 pax. Gamme prix : 15-40k€ (privatisation 2 jours). Réalisations : destination weddings US/UK Luberon. Signaux marketing : Insta 6k + Virginie Jones + niche premium. Siège : Route de Bonnieux, 84400 Apt (Luberon).","sources":"Virginie Jones | Le Blog de Madame C"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Château Capitoul","ville":"France","zone":"","dirigeant_principal":"Groupe Domaine & Demeure (Karl O'Hanlon)","portable_dirigeant":"","telephone":"+33 4 30 17 39 22","email":"","email_dirigeant":"events@chateaucapitoul.com","linkedin_dirigeant":"https://linkedin.com/in/karl-o-hanlon","site_web":"https://chateaucapitoul.com","note_priorite":"Moyenne","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"Même équipe que Serjac. Positionnement : domaine 100ha lagune Méditerranée — Asado brasserie + Méditerranéo fine dining — 134-268 pax couchage. Gamme prix : 15-50k€. Réalisations : mariages UK/Irish + corporate Languedoc. Signaux marketing : Insta 15k + i-escape + niche premium destination. Siège : Avenue de Gruissan, 11100 Narbonne (Languedoc).","sources":"Château Capitoul | Domaine de Meure"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Château du Pont d'Oye","ville":"Belgique","zone":"","dirigeant_principal":"Famille Nothomb (propriétaire historique)","portable_dirigeant":"","telephone":"+32 63 22 94 46","email":"","email_dirigeant":"info@chateaudupontdoye.com","linkedin_dirigeant":"","site_web":"https://chateaudupontdoye.com","note_priorite":"Moyenne","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"Château 17e — Forêt d'Anlier — 12 ch luxe — 70-120 pax — privatisation totale. Gamme prix : 5,9-30k€. Réalisations : mariages Belgique + Luxembourg + Lorraine FR. Signaux marketing : Insta 8k + 100% recommandation couples + pas d'ads. Siège : Rue du Pont d'Oye 1, 6720 Habay (Luxembourg belge).","sources":"Château du Pont d'Oye"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Château de Bourglinster","ville":"Luxembourg","zone":"","dirigeant_principal":"État luxembourgeois (Ministère Culture) - Chef René Mathieu","portable_dirigeant":"","telephone":"+352 78 78 78 1","email":"","email_dirigeant":"banquets@bourglinster.lu","linkedin_dirigeant":"","site_web":"https://bourglinster.lu","note_priorite":"Moyenne","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"Château médiéval restauré — Chef Michelin René Mathieu. Positionnement : salons 20-120 assis / 600 cocktail. Gamme prix : 10-40k€. Réalisations : mariages luxembourgeois + corporate institutionnel. Signaux marketing : Insta faible + institution publique + pas d'ads. Siège : 8 rue du Château, L-6162 Bourglinster (Junglinster).","sources":"Bourglinster.lu"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Château de Coppet","ville":"Suisse","zone":"","dirigeant_principal":"Famille d'Haussonville (descendants Mme de Staël)","portable_dirigeant":"","telephone":"+41 22 776 10 28","email":"","email_dirigeant":"receptions@chateaudecoppet.ch","linkedin_dirigeant":"","site_web":"https://chateaudecoppet.ch","note_priorite":"Moyenne","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"Château historique Mme de Staël — 6 espaces — caves 200 assis/280 debout — parc romantique. Gamme prix : 15-50k CHF. Réalisations : mariages Genève + corporate luxe finance. Signaux marketing : Insta faible + institution patrimoine. Siège : Rue Joseph-Pellet, 1296 Coppet (Vaud Genève).","sources":"Chateaudecoppet.ch"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Château Maison Blanche","ville":"Suisse","zone":"","dirigeant_principal":"Société viticole (rénovation récente - partenaire OVV)","portable_dirigeant":"","telephone":"+41 24 466 68 69","email":"","email_dirigeant":"events@maison-blanche.ch","linkedin_dirigeant":"","site_web":"https://maison-blanche.ch","note_priorite":"Moyenne","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"Château 1573 viticole reconnu mariages civils Vaud — privatisation modulable. Gamme prix : 10-40k CHF. Réalisations : mariages Lavaux + Genève + corporate vin. Signaux marketing : Insta 5k + OVV partenariat + niche premium suisse. Siège : Route de Corbeyrier, 1853 Yvorne (Vaud).","sources":"Maison-blanche.ch"}},

  // ─── PRIORITÉ BASSE ─────────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Lieux de réception / domaines / châteaux","entreprise":"Château de Chamarande","ville":"France","zone":"","dirigeant_principal":"Conseil Départemental Essonne (propriétaire public)","portable_dirigeant":"","telephone":"+33 1 60 82 52 01","email":"","email_dirigeant":"chamarande@cd-essonne.fr","linkedin_dirigeant":"","site_web":"https://chamarande.essonne.fr","note_priorite":"Basse","source":"fichier lieux réception enrichi","statut":"À contacter","data":{"note":"⚠️ Institution publique — usage limité. Positionnement : domaine départemental 98ha + centre art contemporain. Gamme prix : 5-25k€ (collectivité publique). Réalisations : corporate art + mariages parisiens créatifs. Signaux marketing : Insta 8k + opéré comme institution. Siège : 38 rue du Commandant Arnoux, 91730 Chamarande (Île-de-France Essonne).","sources":"Chamarande.essonne.fr"}}

].map(p => ({ qualification: '', date_relance: null, ne_plus_contacter: false, ...p }))
