// Cibles RÉELLES « Location matériel événementiel premium » (INDESCALE).
// 22 cibles FR/CH/BE/LU. Liste figée. Notes denses regroupant positionnement, gamme prix,
// réalisations, signaux marketing. 'n/a' laissé vide (jamais inventé).

let _c = 0
const cid = () => 'loc-' + (++_c)

export const LOCATION_MATERIEL_PROSPECTS = [
  // ─── PRIORITÉ HAUTE ────────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Location matériel événementiel premium","entreprise":"Atawa","ville":"France","zone":"","dirigeant_principal":"Maxime Houssin (Co-Founder & CEO) + Aymeric de Guerre (Co-Founder Dir Commercial)","portable_dirigeant":"","telephone":"01 84 88 35 90","email":"","email_dirigeant":"contact@atawa.com","linkedin_dirigeant":"https://www.linkedin.com/in/maxime-houssin-356ab826/","site_web":"https://www.atawa.com","note_priorite":"Haute","source":"fichier location matériel enrichi","statut":"À contacter","data":{"note":"🔥 Scale-up structurée + marketing mûr → PRODIGIO prouve acquisition incrémentale. Positionnement : leader montant infra événementielle haut de gamme — tentes + mobilier + déco turnkey. Gamme prix : 5-50k€ / event. Réalisations : mariages destination luxe + corporate Fortune 500 + festivals. Signaux marketing : site très éditorialisé + SEO dominant + LinkedIn actif + story incubation Dauphine. Siège : Meudon (HQ) / Lyon historique. France entière (11 agences) + Suisse.","sources":"Crunchbase | site officiel"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Location matériel événementiel premium","entreprise":"Options France (Maison Options)","ville":"France","zone":"","dirigeant_principal":"Brice Chabrand (Directeur Boutique Paris) - Maurizio Sala (Dir Genève)","portable_dirigeant":"","telephone":"01 41 14 04 04","email":"","email_dirigeant":"contact@options.fr","linkedin_dirigeant":"","site_web":"https://www.options.fr","note_priorite":"Haute","source":"fichier location matériel enrichi","statut":"À contacter","data":{"note":"🔥 Leader historique + faible signal performance digital → gap énorme à combler. Positionnement : N°1 historique location vaisselle + mobilier événementiel premium. Gamme prix : 5-30k€ / event. Réalisations : royal weddings + grands palaces + cérémonies présidentielles. Signaux marketing : 350 salariés + 15 000 m² stockage + showrooms Paris + Bxl + Genève. Siège : Paris HQ — Boutique 21 Rue Gros 75016. Couvre France (11) + Suisse (2) + Belgique (2) + Luxembourg (1) + UK + Espagne.","sources":"site officiel | Pages Jaunes"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Location matériel événementiel premium","entreprise":"Maison Sash","ville":"France","zone":"","dirigeant_principal":"Fondateur à confirmer (SAS récente)","portable_dirigeant":"","telephone":"01 47 73 09 25","email":"","email_dirigeant":"contact@maisonsash.com","linkedin_dirigeant":"","site_web":"https://www.maisonsash.com","note_priorite":"Haute","source":"fichier location matériel enrichi","statut":"À contacter","data":{"note":"🔥 Pure premium niche + image éditoriale forte mais machine d'acquisition quasi-absente. Positionnement : arts de la table HdG signés (Oscar de la Renta / Christian Lacroix) — niche luxe pure. Gamme prix : 3-15k€ / event. Réalisations : marques de luxe + wedding planners premium + corporate top. Signaux marketing : collections designers + pivot 2024 vers mobilier + approche éditoriale. Siège : 3 cours Valmy 92800 Puteaux. Paris IDF + France + Europe.","sources":"site officiel"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Location matériel événementiel premium","entreprise":"Be Lounge","ville":"France","zone":"","dirigeant_principal":"Fondateur (10 ans existence)","portable_dirigeant":"","telephone":"04 42 24 33 90","email":"","email_dirigeant":"contact@be-lounge.com","linkedin_dirigeant":"","site_web":"https://www.be-lounge.com","note_priorite":"Haute","source":"fichier location matériel enrichi","statut":"À contacter","data":{"note":"🔥 Multi-agences + ticket élevé + déjà structurés mais marketing dispersé. Positionnement : précurseur tente nomade + mobilier — 5000 installs structures. Gamme prix : 8-50k€ / event. Réalisations : mariages destination Sud + Corse + corporate premium. Signaux marketing : stock 12 000 chaises + 20 000 m² + Insta très actif. Siège : 3 agences Aix-en-Provence + Bordeaux + Toulouse. France entière + Corse + Suisse + Costa Brava.","sources":"site officiel"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Location matériel événementiel premium","entreprise":"La Toile Nomade","ville":"France","zone":"","dirigeant_principal":"Marie & Quentin (couple gérants - architectes)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.latoilenomade.com","note_priorite":"Haute","source":"fichier location matériel enrichi","statut":"À contacter","data":{"note":"Stretch tents éco-design + approche architecte. Positionnement : grandes capacités (50-300 invités). Gamme prix : 6-20k€ / event. Réalisations : mariages destination Sud-Ouest + Provence. Signaux marketing : approche architecte / Instagram esthétique / Mariages.net top rated. Siège : Pau (Béarn). Couvre Pau + Biarritz + Toulouse + Montpellier + Marseille + Aix + Avignon + Paris.","sources":"site officiel | mariages.net"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Location matériel événementiel premium","entreprise":"Eric Chauvin (Un Jour de Fleurs)","ville":"France","zone":"","dirigeant_principal":"Eric Chauvin (Fondateur - fleuriste haute couture)","portable_dirigeant":"","telephone":"01 45 50 43 54","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://chauvinparis.com","note_priorite":"Haute","source":"fichier location matériel enrichi","statut":"À contacter","data":{"note":"🔥 Fleuriste signature avec presse mais zéro acquisition payante structurée. Positionnement : fleuriste haute couture — référence ultime mariage royal. Gamme prix : 15-100k€ / wedding. Réalisations : mariage Charlène Wittstock & Albert II Monaco + Versailles + Opéra Garnier + Pitti Florence. Signaux marketing : Vogue + presse internationale + 20 ans + signature 'haute couture florale'. Siège : 22 Rue Jean Nicot 75007 Paris.","sources":"site officiel | Yelp"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Location matériel événementiel premium","entreprise":"Lachaume","ville":"France","zone":"","dirigeant_principal":"Direction Lachaume (SA depuis 1845 - fondé Jules Lachaume)","portable_dirigeant":"","telephone":"01 42 60 57 26","email":"","email_dirigeant":"contact@maisonlachaume.com","linkedin_dirigeant":"","site_web":"https://maisonlachaume.com","note_priorite":"Haute","source":"fichier location matériel enrichi","statut":"À contacter","data":{"note":"🔥 Plus ancien fleuriste de Paris (1845) — patrimoine Proust/Dior/YSL/Lagerfeld. Positionnement : héritage 180 ans + proximité Élysée. Gamme prix : 15-80k€ / wedding. Réalisations : mariages élite + Dior haute couture + Élysée proximité. Signaux marketing : patrimoine 180 ans + Insta @lachaume.fleurs très soigné. Siège : 103 rue du Faubourg-Saint-Honoré 75008 Paris.","sources":"Wikipedia | site officiel"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Location matériel événementiel premium","entreprise":"Castor Fleuriste","ville":"France","zone":"","dirigeant_principal":"Louis-Géraud Castor (Fondateur 2017) + Marianne Mairesse (co-gérante)","portable_dirigeant":"","telephone":"01 40 56 34 68","email":"","email_dirigeant":"contact@castor-fleuriste.com","linkedin_dirigeant":"","site_web":"https://castorfleuriste.com","note_priorite":"Haute","source":"fichier location matériel enrichi","statut":"À contacter","data":{"note":"🔥 Le fleuriste préféré de la mode + bouquets contemporains Marais. Positionnement : bouquets contemporains Marais. Gamme prix : 8-50k€ / wedding. Réalisations : mariages mode + défilés + L'Officiel + Vogue. Signaux marketing : presse L'Officiel + Insta très éditorial + SARL 550k€ capital. Siège : 14 Rue Debelleyme 75003 Paris.","sources":"societe.com | L'Officiel | Insta"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Location matériel événementiel premium","entreprise":"Maison Vertumne (Atelier Vertumne)","ville":"France","zone":"","dirigeant_principal":"Clarisse Béraud (Fondatrice 1995 - Creative Designer)","portable_dirigeant":"","telephone":"01 42 86 06 76","email":"","email_dirigeant":"contact@maison-vertumne.fr","linkedin_dirigeant":"https://www.linkedin.com/in/clarisse-beraud-91436b12/","site_web":"https://www.maisonvertumne.com","note_priorite":"Haute","source":"fichier location matériel enrichi","statut":"À contacter","data":{"note":"🔥 30 ans + auteure 'Secrets de fleuriste' + LinkedIn actif. Positionnement : décoration florale + scénographie mariage signature 'art floral'. Gamme prix : 10-60k€ / wedding. Réalisations : 30 ans + Salon Carrousel du Louvre + livre 'Secrets de fleuriste'. Signaux marketing : auteure / formations / LinkedIn actif / Insta @maisonvertumne_paris. Siège : 12 rue de la Sourdière 75001 Paris.","sources":"site officiel | LinkedIn | Babelio"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Location matériel événementiel premium","entreprise":"Christian Tortu","ville":"France","zone":"","dirigeant_principal":"Christian Tortu (Fondateur - icône)","portable_dirigeant":"","telephone":"+33 1 43 26 02 56","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.christiantortu.fr","note_priorite":"Haute","source":"fichier location matériel enrichi","statut":"À contacter","data":{"note":"🔥 Icône du 'bouquet chic' — Dior/Chanel/Balmain/Cannes. Positionnement : héritage 40 ans + marque de parfums Lothantique. Gamme prix : 20-150k€ / wedding. Réalisations : Cannes Film Festival + mariages magnats pétrole + défilés haute couture. Signaux marketing : marque de parfums Lothantique + Wikipédia + héritage 40 ans. Siège : 6 Carrefour de l'Odéon 75006 Paris.","sources":"Wikipédia | site officiel"}},

  // ─── PRIORITÉ MOYENNE ──────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Location matériel événementiel premium","entreprise":"126 Events","ville":"France","zone":"","dirigeant_principal":"Direction non identifiée","portable_dirigeant":"","telephone":"01 48 43 00 00","email":"","email_dirigeant":"contact@126events.com","linkedin_dirigeant":"","site_web":"https://location-mobilier-paris.com","note_priorite":"Moyenne","source":"fichier location matériel enrichi","statut":"À contacter","data":{"note":"Mobilier événementiel premium + cinéma/série. Positionnement : Paris IDF + France. Gamme prix : 5-25k€ / event. Réalisations : tournages cinéma + mariages + foires pro. Signaux marketing : showroom 600 m² + SEO fort 'location mobilier paris'. Siège : 126 Avenue du Général Leclerc 93500 Pantin.","sources":"site officiel | Pages Jaunes"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Location matériel événementiel premium","entreprise":"Tentickle France","ville":"France","zone":"","dirigeant_principal":"Filiale d'un groupe SA","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"marseille@tentickle.com","linkedin_dirigeant":"","site_web":"https://www.tentickle-stretchtents.com/fr","note_priorite":"Moyenne","source":"fichier location matériel enrichi","statut":"À contacter","data":{"note":"Référence mondiale tentes stretch premium 'German design'. Positionnement : France (Aix HQ) + 35 pays. Gamme prix : 5-30k€ / event. Réalisations : galas + Cannes Film Festival + corporate F500. Signaux marketing : réseau international + portfolio prestige. Siège : Aix-en-Provence.","sources":"site officiel"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Location matériel événementiel premium","entreprise":"OCN Events (ex-Organic Concept)","ville":"France","zone":"","dirigeant_principal":"Famille Lourdel","portable_dirigeant":"","telephone":"03 27 33 36 86","email":"","email_dirigeant":"contact@ocn.events","linkedin_dirigeant":"","site_web":"https://www.ocn.events","note_priorite":"Moyenne","source":"fichier location matériel enrichi","statut":"À contacter","data":{"note":"Tentes & chapiteaux mariage + corporate Nord. Positionnement : Hauts-de-France + Normandie + IDF + Picardie + Bretagne. Gamme prix : 4-20k€ / event. Réalisations : mariages châteaux Nord + festivals + corporate. Signaux marketing : présence éditoriale modérée + mariages haut de gamme. Siège : Nord de France.","sources":"site officiel"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Location matériel événementiel premium","entreprise":"Ça Me Tente","ville":"France","zone":"","dirigeant_principal":"Olivia (gérante)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.cametente.com","note_priorite":"Moyenne","source":"fichier location matériel enrichi","statut":"À contacter","data":{"note":"Tentes berbères 220 m² authentiques + tentes nomades. Positionnement : Gard + Hérault + Vaucluse + Bouches-du-Rhône + Drôme. Gamme prix : 5-18k€ / event. Réalisations : mariages destination Provence + festivals + corporate. Signaux marketing : 12 ans expertise + esthétique tente berbère + mariages.net. Siège : Montpellier / Sud.","sources":"site officiel"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Location matériel événementiel premium","entreprise":"Fête24","ville":"France","zone":"","dirigeant_principal":"Famille gérante (English-speaking family-run)","portable_dirigeant":"07 66 43 02 11","telephone":"","email":"","email_dirigeant":"bonjour@fete24.com","linkedin_dirigeant":"","site_web":"https://fete24.com","note_priorite":"Moyenne","source":"fichier location matériel enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct family-run. Positionnement : stretch tents + production événementielle EN/FR pour mariages destination. Gamme prix : 2200€ HT (10x7,5m) à 15k€ (30x10m). Réalisations : mariages internationaux Château Pujols + Pyrénées. Signaux marketing : family-run / 17 ans / niche destination wedding international. Siège : 44b Rue de la Résistance 24130 Prigonrieux (Bergerac).","sources":"site officiel"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Location matériel événementiel premium","entreprise":"Twist Events","ville":"Suisse","zone":"","dirigeant_principal":"Direction non identifiée","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"info@twist-events.ch","linkedin_dirigeant":"","site_web":"https://twist-events.ch","note_priorite":"Moyenne","source":"fichier location matériel enrichi","statut":"À contacter","data":{"note":"Stretch tents + crossover + bambou + mobilier Romandie. Positionnement : Genève + toute Romandie + Vaud + Valais + Haute-Savoie + Ain. Gamme prix : 8-30 KCHF / event. Réalisations : mariages luxe Romandie + corporate Genève. Signaux marketing : catalogue digitalisé + Partybooker.ch top tier. Siège : Carouge / Genève.","sources":"site officiel | partybooker"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Location matériel événementiel premium","entreprise":"All-Loc","ville":"Belgique","zone":"","dirigeant_principal":"Direction non identifiée","portable_dirigeant":"","telephone":"+32 2 384 89 86","email":"","email_dirigeant":"info@all-loc.be","linkedin_dirigeant":"","site_web":"https://www.all-loc.be","note_priorite":"Moyenne","source":"fichier location matériel enrichi","statut":"À contacter","data":{"note":"Top 10 BE tentes luxe + tribunes (5 pays). Positionnement : Belgique + France + Pays-Bas + Luxembourg + Suisse. Gamme prix : 10-50k€ / event. Réalisations : mariages royaux/luxe BE + corporate Bxl + festivals. Signaux marketing : production interne (couture+métal+menuiserie) + réputation BE solide. Siège : Braine-l'Alleud.","sources":"site officiel"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Location matériel événementiel premium","entreprise":"Thiribut Events","ville":"Belgique","zone":"","dirigeant_principal":"Famille Thiribut (PME 2011)","portable_dirigeant":"+32 474 62 85 97","telephone":"","email":"","email_dirigeant":"info@thiributevents.be","linkedin_dirigeant":"","site_web":"https://www.thiributevents.be","note_priorite":"Moyenne","source":"fichier location matériel enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct family-run + tentes + mobilier + Horeca + AV full service Wallonie. Positionnement : Belgique entière + Nord France + Luxembourg. Gamme prix : 4-25k€ / event. Réalisations : mariages Wallonie + Bxl + corporate. Signaux marketing : PME 2011 + multi-provinces + catalogue complet. Siège : Rue de Thiribut 30 Forville (Fernelmont).","sources":"site officiel"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Location matériel événementiel premium","entreprise":"Options Bruxelles","ville":"Belgique","zone":"","dirigeant_principal":"Direction locale Options Group","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"contact-be@options.fr","linkedin_dirigeant":"","site_web":"https://www.options.be","note_priorite":"Moyenne","source":"fichier location matériel enrichi","statut":"À contacter","data":{"note":"Antenne BE du leader Options. Positionnement : vaisselle + mobilier premium Belgique entière. Gamme prix : 5-30k€ / event. Réalisations : mariages château + corporate luxe Bxl. Signaux marketing : showroom Bxl + catalogue identique HQ Paris. Siège : Bruxelles (showroom).","sources":"site officiel"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Location matériel événementiel premium","entreprise":"Roses Costes Dani Roses (Hôtel Costes)","ville":"France","zone":"","dirigeant_principal":"Danièle 'Dani' Graule (Propriétaire - chanteuse/actrice icône)","portable_dirigeant":"","telephone":"+33 1 42 44 50 09","email":"","email_dirigeant":"dani@hotelcostes.com","linkedin_dirigeant":"","site_web":"https://www.hotelcostes.com/roses-costes-dani-roses","note_priorite":"Moyenne","source":"fichier location matériel enrichi","statut":"À contacter","data":{"note":"Boutique signature Hôtel Costes dédiée rose — 200+ variétés. Positionnement : Paris + monde via Costes. Gamme prix : 12-60k€ / wedding. Réalisations : mariages clientèle Costes/Pigalle + soirées défilés. Signaux marketing : marque Costes + Goop + Vogue + presse Joséphine Bonaparte. Siège : 239 rue Saint-Honoré 75001 Paris.","sources":"Yelp | Goop | montecristomagazine"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Location matériel événementiel premium","entreprise":"Mathilde Bourdy (Les Fleurs du Grillon)","ville":"France","zone":"","dirigeant_principal":"Mathilde Bourdy","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://mariages.net","note_priorite":"Moyenne","source":"fichier location matériel enrichi","statut":"À contacter","data":{"note":"Ferme florale + scénographie mariage destination Provence. Positionnement : Drôme provençale + Provence + Sud-Est. Gamme prix : 6-25k€ / wedding. Réalisations : mariages destination Provence avril-octobre. Signaux marketing : Mariages.net top rated + réputation locale Drôme. Siège : Drôme provençale.","sources":"mariages.net"}},

  // ─── PRIORITÉ BASSE ─────────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Location matériel événementiel premium","entreprise":"Tamboo (Nord Bâches)","ville":"France","zone":"","dirigeant_principal":"Direction Nord Bâches","portable_dirigeant":"","telephone":"03 20 87 22 60","email":"","email_dirigeant":"contact@tamboo-tente.fr","linkedin_dirigeant":"","site_web":"https://www.tamboo-tente.fr","note_priorite":"Basse","source":"fichier location matériel enrichi","statut":"À contacter","data":{"note":"Fabricant français tentes stretch sur-mesure (B2B revendeurs). Positionnement : France entière (vente + location partenaires). Gamme prix : 3-15k€. Réalisations : fabrication pour acteurs événementiel (Atawa / Be Lounge…). Signaux marketing : Made in France + B2B fabricant. Siège : Templemars 59 (Nord).","sources":"site officiel"}}

].map(p => ({ qualification: '', date_relance: null, ne_plus_contacter: false, ...p }))
