// Cibles RÉELLES « Photographes / vidéastes mariage haut de gamme » (INDESCALE).
// 31 cibles FR/CH/BE/LU. Liste figée. Notes denses regroupant positionnement, gamme prix,
// réalisations, signaux marketing. 'n/a' laissé vide (jamais inventé).
// Spécificité secteur : ~55% portables 06/07 trouvés (solo-entrepreneurs Insta-friendly).

let _c = 0
const cid = () => 'photo-' + (++_c)

export const PHOTOGRAPHES_MARIAGE_PROSPECTS = [
  // ─── PRIORITÉ HAUTE ────────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Greg Finck Photography","ville":"France","zone":"","dirigeant_principal":"Greg Finck","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"greg@gregfinck.com","linkedin_dirigeant":"","site_web":"https://www.gregfinck.com","note_priorite":"Haute","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"🔥 TOP MONDIAL Harper's Bazaar — levier maximal Mitja-style. Positionnement : fine art / film / éditorial international, top photographe luxe FR. Gamme prix : 6-12k€+ par mariage destination. Réalisations : mariages célébrités Provence/Côte d'Azur + publications Vogue / Harper's Bazaar / Elle Wedding. Signaux marketing : cité Harper's Bazaar Top Wedding Photographers in the World + branding ultra-premium. Siège : Paris (France).","sources":"gregfinck.com | rocketreach.co"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Lifestories by Yann Audic","ville":"France","zone":"","dirigeant_principal":"Yann Audic","portable_dirigeant":"+33 6 28 80 80 70","telephone":"","email":"","email_dirigeant":"yann@lifestorieswedding.com","linkedin_dirigeant":"","site_web":"https://lifestorieswedding.com","note_priorite":"Haute","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct + Ritz Paris + Château de la Gaude. Positionnement : lifestyle / éditorial / fine art. Gamme prix : 5-8k€. Réalisations : Ritz Paris + Château de la Gaude Provence + La Mariée aux Pieds Nus features. Signaux marketing : featured La Mariée aux Pieds Nus + mode/lifestyle/Vogue-adjacent. Siège : Paris (Île-de-France).","sources":"lifestorieswedding.com/contact-3"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Pierre Atelier","ville":"France","zone":"","dirigeant_principal":"Pierre Atelier (founder)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"pierreatelierparis@gmail.com","linkedin_dirigeant":"","site_web":"https://pierreatelier.com","note_priorite":"Haute","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"Destination wedding photographer + luxury & editorial visual storytelling. Gamme prix : 4-7k€. Réalisations : mariages Paris luxe + destination Europe. Signaux marketing : recommandé par wedding planners US/UK + listé Wezoree top vendor. Siège : Paris.","sources":"pierreatelier.com | wezoree.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Maxime Bernadin","ville":"France","zone":"","dirigeant_principal":"Maxime Bernadin","portable_dirigeant":"06 16 60 03 87","telephone":"","email":"","email_dirigeant":"contact@maximebernadin.com","linkedin_dirigeant":"","site_web":"https://www.maximebernadin.com","note_priorite":"Haute","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct + vu Vogue + clientèle internationale. Positionnement : photographe mariage luxe Paris (French Wedding Style / Carats & Cake). Gamme prix : 3-6k€ (collections 8/10/12h dès 3000€). Réalisations : mariages Paris + Provence + Côte d'Azur + Lac Côme. Signaux marketing : cite Vogue + bilingue FR/EN. Siège : Paris.","sources":"maximebernadin.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Sylvain Bouzat","ville":"France","zone":"","dirigeant_principal":"Sylvain Bouzat","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"sylvain.bouzat@gmail.com","linkedin_dirigeant":"","site_web":"https://sylvain-bouzat-photographe-mariage.com","note_priorite":"Haute","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"Award-winning destination wedding photographer + publié Vogue Wedding. Positionnement : fine art. Gamme prix : 5-10k€. Réalisations : mariages Provence, Côte d'Azur, Genève, NYC, Maroc, Corse. Signaux marketing : publié Vogue Wedding + 15+ ans + multi-pays. Siège : Lyon.","sources":"sylvain-bouzat-photographe-mariage.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Le Joli Studio","ville":"France","zone":"","dirigeant_principal":"Sonja Kalicky","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.lejolistudio.com","note_priorite":"Haute","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"Luxury wedding photographer Paris & Normandie + cinematic + fashion-inspired. Positionnement : châteaux + elopements. Gamme prix : 5-9k€ estimé. Réalisations : mariages châteaux + élopements Riviera/Provence. Signaux marketing : branding ultra-éditorial + niche luxury wedding planners Paris. Siège : Paris.","sources":"lejolistudio.com/about"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Les Frères Carmona","ville":"France","zone":"","dirigeant_principal":"Frères Carmona (duo)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://lesfrerescarmona.com","note_priorite":"Haute","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"🔥 15 mariages/an seulement — dates 12-18 mois à l'avance = besoin pipe ultra-qualifié. Positionnement : photographes reportage éditorial mariages luxe Saint-Tropez / Riviera. Gamme prix : 6-10k€. Réalisations : mariages villas privées Saint-Tropez + weekends multi-réceptions. Signaux marketing : saisons limitées. Siège : Sud France (Saint-Tropez/Cannes/Nice/Monaco/Aix/Luberon).","sources":"lesfrerescarmona.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Pierre & Julia","ville":"France","zone":"","dirigeant_principal":"Pierre & Julia (duo)","portable_dirigeant":"07 49 49 10 07","telephone":"","email":"","email_dirigeant":"contact@pierre-et-julia.fr","linkedin_dirigeant":"","site_web":"https://www.pierre-et-julia.fr","note_priorite":"Haute","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct + duo photo+vidéo = upsell PRODIGIO clair + 250+ couples. Positionnement : Fine Art lumière douce. Gamme prix : 2,5-6k€ (6h weekend dès 2500€). Réalisations : 250+ mariages France entière. Signaux marketing : référencé French Wedding Suppliers + duo photo+video = upsell. Siège : Paris / Normandie.","sources":"pierre-et-julia.fr/infos"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Gordon Wedding Films","ville":"France","zone":"","dirigeant_principal":"Meryll de Gordon","portable_dirigeant":"+33 6 47 92 03 76","telephone":"","email":"","email_dirigeant":"contact@gordonweddingfilms.com","linkedin_dirigeant":"","site_web":"https://www.gordonweddingfilms.com","note_priorite":"Haute","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct + 5x Best Wedding Videographer France 2021-2025 + EN+FR + destination = match parfait PRODIGIO. Positionnement : destination wedding videographer. Gamme prix : 5-9k€. Réalisations : mariages destination France + Thaïlande. Signaux marketing : 5x Best Wedding Videographer + French Wedding Style featured. Siège : Saint-Antonin-sur-Bayon (Provence).","sources":"gordonweddingfilms.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"PRORÉAL","ville":"France","zone":"","dirigeant_principal":"Jordan Abauzit","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.proreal-video.com","note_priorite":"Haute","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"🔥 AGENCE (pas freelance) → structure mature pour deal récurrent. Positionnement : films + photo mariage de luxe Île-de-France cinematic + élégant. Gamme prix : 5-9k€. Réalisations : mariages luxe Île-de-France + international. Signaux marketing : agence pas freelance = structure mature. Siège : Île-de-France.","sources":"proreal-video.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Christophe Viseux Photography","ville":"Suisse","zone":"","dirigeant_principal":"Christophe Viseux","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"info@christopheviseux.ca","linkedin_dirigeant":"","site_web":"https://geneva.christopheweddingphoto.com","note_priorite":"Haute","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"🔥 Award-winning WPJA / ISPWP / Fearless + publié Brides, Martha Stewart, Town & Country + multi-pays. Positionnement : Suisse + Dubaï + Ottawa + worldwide. Gamme prix : 5-10k€. Réalisations : mariages Suisse + Dubaï + Ottawa + destination. Signaux marketing : top awards internationaux + multi-pays. Siège : Genève (FR-CH-CA multi-base).","sources":"geneva.christopheweddingphoto.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Pino Romeo Photographie","ville":"Belgique","zone":"","dirigeant_principal":"Pino Romeo","portable_dirigeant":"+32 485 13 11 67","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.photoromeo.be","note_priorite":"Haute","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"🔥 TOP 100 mondial Fearless + portable direct = autorité éditoriale forte. Positionnement : photographe mariage artistique Belgique. Gamme prix : 4-7k€. Réalisations : mariages Namur / Brabant Wallon / Luxembourg / France. Signaux marketing : TOP 100 mondial Fearless. Siège : Happe – Ciney (5590 Namur Sud).","sources":"photoromeo.be"}},

  // ─── PRIORITÉ MOYENNE ──────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Daria Lorman Photography","ville":"France","zone":"","dirigeant_principal":"Daria Lorman","portable_dirigeant":"+33 6 48 96 80 35","telephone":"","email":"","email_dirigeant":"daria.lorman@gmail.com","linkedin_dirigeant":"","site_web":"https://parishappypictures.com","note_priorite":"Moyenne","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct + Top-10 Mariage.com Île-de-France. Positionnement : destination wedding photographer Paris. Gamme prix : 3-6k€. Réalisations : Château Bouffémont + mariages destination Paris. Signaux marketing : Style Me Pretty + Green Wedding Shoes + Wedding Chicks features. Siège : Paris.","sources":"parishappypictures.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Lawrence Banahan – Wedding Photo Côte d'Azur","ville":"France","zone":"","dirigeant_principal":"Lawrence Banahan","portable_dirigeant":"+33 6 80 71 99 02","telephone":"","email":"","email_dirigeant":"lawrence@banahan.fr","linkedin_dirigeant":"","site_web":"https://www.banahan.fr","note_priorite":"Moyenne","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct + 20+ ans Riviera. Positionnement : reportage couleur & N&B Côte d'Azur. Gamme prix : 3-6k€. Réalisations : mariages Cannes / Monaco / Saint-Tropez. Signaux marketing : Insta @weddingphotocotedazur + marque historique. Siège : Saint-Raphaël.","sources":"banahan.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Alexandre Lorig Photographe","ville":"France","zone":"","dirigeant_principal":"Alexandre Lorig","portable_dirigeant":"06 09 85 33 33","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.alexandre-lorig-photographe.com","note_priorite":"Moyenne","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct + photographe événementiel + mariage HdG PACA depuis 2011 (SARL LA Photo Prod). Gamme prix : 3-6k€. Réalisations : mariages Monaco, Saint-Tropez, Cannes, Luberon. Signaux marketing : société constituée + couverture régionale large. Siège : Sud-Est (Aix-en-Provence).","sources":"alexandre-lorig-photographe.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Sébastien Laban Photographe","ville":"France","zone":"","dirigeant_principal":"Sébastien Laban","portable_dirigeant":"06 03 97 29 63","telephone":"","email":"","email_dirigeant":"sebastienlaban-photographe@hotmail.fr","linkedin_dirigeant":"","site_web":"https://www.sebastienlaban-photographe.com","note_priorite":"Moyenne","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct + double casquette photo/réalisateur. Positionnement : Lyon ↔ Riviera ↔ Monaco. Gamme prix : 3-5k€. Réalisations : mariages Côte d'Azur + Lyon. Signaux marketing : double casquette. Siège : Lyon.","sources":"sebastienlaban-photographe.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Studio JOLY Photographie","ville":"France","zone":"","dirigeant_principal":"Marine & Raphaël (duo)","portable_dirigeant":"07 55 62 31 61","telephone":"","email":"","email_dirigeant":"contact@studiojolyphotographie.com","linkedin_dirigeant":"","site_web":"https://studiojolyphotographie.com","note_priorite":"Moyenne","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct + studio physique bastide + duo couple. Positionnement : Provence & Côte d'Azur fine art & émotion. Gamme prix : 4-7k€. Réalisations : mariages Provence + Cannes. Signaux marketing : studio physique bastide Cotignac. Siège : Cotignac (Var, 83).","sources":"studiojolyphotographie.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Guénolé Veillon Films","ville":"France","zone":"","dirigeant_principal":"Guénolé Veillon","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.guenoleveillonfilms.com","note_priorite":"Moyenne","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"Vidéaste mariage luxe Provence/Occitanie + films 8-12 min cinematic. Gamme prix : 3-6k€. Réalisations : mariages Provence, Montpellier, Toulouse. Signaux marketing : brochure complète envoyée à la demande (positionnement premium). Siège : Montpellier (Hérault).","sources":"guenoleveillonfilms.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Studio Memory","ville":"France","zone":"","dirigeant_principal":"Vincent (founder)","portable_dirigeant":"+33 6 25 24 94 90","telephone":"","email":"","email_dirigeant":"contact@studiomemory.fr","linkedin_dirigeant":"","site_web":"https://www.studiomemory.fr","note_priorite":"Moyenne","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct + 180+ films Paris/IDF. Positionnement : vidéaste mariage Paris depuis 2011 naturel + esthétique. Gamme prix : 3-5k€. Réalisations : 180+ films mariage Paris/IDF. Signaux marketing : 15 ans expérience + ancrage Paris fort. Siège : Paris (18 rue Pasquier).","sources":"studiomemory.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Callènes Films","ville":"France","zone":"","dirigeant_principal":"Mathias Callènes","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.callenes-films.com","note_priorite":"Moyenne","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"Style 'Wild & Epic' cinematic + destination + recommande confrères = réseau dense. Gamme prix : 3-6k€. Réalisations : mariages Lyon / Paris / France destination. Signaux marketing : recommandation confrères = réseau. Siège : France (basé Lyon).","sources":"callenes-films.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"The Rendez-Vous Films","ville":"France","zone":"","dirigeant_principal":"Sara & Guillaume (duo)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.the-rendez-vous.com","note_priorite":"Moyenne","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"Duo photo+vidéo = upsell PRODIGIO + jeune marque montante. Positionnement : Provence/Côte d'Azur sensible + cinematic + Italie/Europe. Gamme prix : 4-7k€. Réalisations : mariages Côte d'Azur + Italie. Signaux marketing : duo photo+vidéo = upsell. Siège : Côte d'Azur / Provence.","sources":"the-rendez-vous.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Once Upon a Day","ville":"France","zone":"","dirigeant_principal":"Laetitia & Clément (duo couple)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://onceuponaday.fr","note_priorite":"Moyenne","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"Packs Photo+Vidéo 4-8k€ = match exact ticket PRODIGIO. Positionnement : duo photo+vidéo France + Europe. Gamme prix : 4-8k€ photo+video / dès 2.7k€ solo. Réalisations : mariages France entière + Europe. Signaux marketing : packs Photo+Video déjà 4-8k€. Siège : Alsace (Haguenau / Epfig).","sources":"onceuponaday.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"WeddingLight (Olivier)","ville":"France","zone":"","dirigeant_principal":"Olivier","portable_dirigeant":"+33 6 24 96 71 57","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://weddinglight.com","note_priorite":"Moyenne","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct + 25 ans XP worldwide + clientèle internationale. Positionnement : lifestyle wedding photographer + videographer Paris. Gamme prix : 4-8k€. Réalisations : mariages Paris, Loire, Normandie, Provence. Signaux marketing : très orienté clientèle US/UK destination Paris. Siège : Paris (central).","sources":"weddinglight.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Monika Breitenmoser Photography","ville":"Suisse","zone":"","dirigeant_principal":"Monika Breitenmoser","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"info@monikabreitenmoser.com","linkedin_dirigeant":"","site_web":"https://monikabreitenmoser.com","note_priorite":"Moyenne","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"Photographe mariage Suisse romande sensible + authentique + intemporel. Gamme prix : CHF 5-9k. Réalisations : mariages Genève / Lausanne / Lac Léman. Signaux marketing : discrétion + clientèle CHF aisée. Siège : Nyon (Suisse romande).","sources":"monikabreitenmoser.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"David Ghisa Photographer","ville":"Luxembourg","zone":"","dirigeant_principal":"David Ghisa","portable_dirigeant":"+352 691 898 183","telephone":"","email":"","email_dirigeant":"contact@davidghisa.com","linkedin_dirigeant":"","site_web":"https://www.davidghisa.com","note_priorite":"Moyenne","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"🔥 Portable LU direct. Positionnement : wedding & portrait photographer Luxembourg + storytelling élégant. Gamme prix : 3-6k€. Réalisations : mariages Luxembourg + destination. Signaux marketing : partenaire AMCHAM Luxembourg + présence Insta @davidghisa. Siège : Mertert (L-6670, Luxembourg).","sources":"davidghisa.com | fearlessphotographers.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Marion Dessard Photographe","ville":"Luxembourg","zone":"","dirigeant_principal":"Marion Dessard","portable_dirigeant":"+352 671 13 15 13","telephone":"","email":"","email_dirigeant":"hello@mariondessard.com","linkedin_dirigeant":"","site_web":"https://www.mariondessard.com","note_priorite":"Moyenne","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"🔥 Portable LU direct + studio physique Creative Hub. Positionnement : portrait + mariage + corporate Luxembourg. Gamme prix : 3-6k€. Réalisations : mariages + portraits Luxembourg. Signaux marketing : studio physique + croisement corporate (réseau B2B). Siège : Differdange (Creative Hub 1535°).","sources":"mariondessard.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Adel Photographer","ville":"Luxembourg","zone":"","dirigeant_principal":"Adel Fahem","portable_dirigeant":"+33 6 51 89 82 22","telephone":"","email":"","email_dirigeant":"contact@adelphotographer.com","linkedin_dirigeant":"","site_web":"https://adelphotographer.com","note_priorite":"Moyenne","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct (WhatsApp) + multilingue + multi-pays. Positionnement : storyteller wedding photographer Luxembourg. Gamme prix : 3-5k€. Réalisations : mariages LUX + FR + BE. Signaux marketing : numéro WhatsApp = canal direct. Siège : Luxembourg.","sources":"adelphotographer.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Naderi Photography","ville":"Luxembourg","zone":"","dirigeant_principal":"Sobhan (Sam) Naderi","portable_dirigeant":"+352 621 748 460","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://naderi.lu","note_priorite":"Moyenne","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"🔥 Portable LU direct + Fearless + WPJA Top 3 Luxembourg 2026 + videographer. Positionnement : wedding photographer & videographer Luxembourg + châteaux/estates. Gamme prix : 3-6k€. Réalisations : mariages châteaux Luxembourg. Signaux marketing : listé Fearless + WPJA Top 3. Siège : Rameldange (L-6995).","sources":"naderi.lu"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Frédéric Rochefort Photographe","ville":"Belgique","zone":"","dirigeant_principal":"Frédéric Rochefort","portable_dirigeant":"+32 497 077 411","telephone":"","email":"","email_dirigeant":"info@fredericrochefort.com","linkedin_dirigeant":"","site_web":"https://fredericrochefort.com","note_priorite":"Moyenne","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"🔥 Portable BE direct + couverture toute la Belgique + destination. Positionnement : photographe mariage Belgique premium + équipement haut de gamme. Gamme prix : 3-6k€. Réalisations : mariages Bruxelles / Liège / Namur / Mons / Antwerp / Gand / Bruges. Signaux marketing : présence forte SEO. Siège : Herne (1540 Belgique).","sources":"fredericrochefort.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Justin Mertens Photographer","ville":"Belgique","zone":"","dirigeant_principal":"Justin Mertens","portable_dirigeant":"+32 491 495 178","telephone":"","email":"","email_dirigeant":"justinmertensphotographer@gmail.com","linkedin_dirigeant":"","site_web":"https://www.justinmertensphotographer.com","note_priorite":"Moyenne","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"🔥 Portable BE direct + 17 ans XP + structure pro (TVA BE) + 4-pays. Positionnement : event photographer + photographe mariage. Gamme prix : 3-5k€. Réalisations : mariages Namur, Liège, Bruxelles, France, Luxembourg, Suisse. Signaux marketing : structure pro. Siège : Namur (Belgique).","sources":"justinmertensphotographer.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Yann Mignonet – Yann M Studio","ville":"Belgique","zone":"","dirigeant_principal":"Yann Mignonet","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"yann.mignonet@gmail.com","linkedin_dirigeant":"","site_web":"https://www.yannmignonet.com","note_priorite":"Moyenne","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"Destination wedding + portrait + editorial luxury + clientèle BE+FR luxe. Positionnement : timeless elegance hybride. Gamme prix : 4-7k€. Réalisations : mariages Château du Biez / Bourgogne / Belleville Alpes. Signaux marketing : vendor 'Timeless Elegance'. Siège : Marcq-en-Baroeul (FR Nord).","sources":"yannmignonet.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Photographes / vidéastes mariage haut de gamme","entreprise":"Anneleen Jegers Photography","ville":"Belgique","zone":"","dirigeant_principal":"Anneleen Jegers","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.anneleenjegers.com","note_priorite":"Moyenne","source":"fichier photographes mariage enrichi","statut":"À contacter","data":{"note":"Wedding + family photographer Gent + KASK Gent (bachelor doc photo). Positionnement : documentaire intime. Gamme prix : 3-5k€. Réalisations : mariages Belgique + Europe. Signaux marketing : background documentaire artistique + branding cohérent. Siège : Gent (Belgique).","sources":"anneleenjegers.com"}}

].map(p => ({ qualification: '', date_relance: null, ne_plus_contacter: false, ...p }))
