// Cibles RÉELLES « Spa intérieur / hammam / piscine intérieure » (INDESCALE).
// Importées du fichier spa-hammam-piscine-interieure.csv (25 cibles, FR/CH/BE/LU).
// Cette catégorie est une LISTE FIGÉE (pas de navigation par ville) : marché niche
// national/international. Données telles que fournies ; 'n/a' laissé vide (jamais inventé),
// la note de qualification dense (positionnement, gamme prix, signaux marketing,
// réalisations) et les sources sont conservées dans `data`.

let _c = 0
const cid = () => 'spa-' + (++_c)

export const SPA_HAMMAM_PISCINE_PROSPECTS = [
  // ─── PRIORITÉ HAUTE ────────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"Azur Pool Concept","ville":"France","zone":"","dirigeant_principal":"Couple co-fondateurs (noms non publics)","portable_dirigeant":"+33 6 16 93 02 28","telephone":"04 94 40 77 92","email":"","email_dirigeant":"contact@azurpoolconcept.com","linkedin_dirigeant":"","site_web":"https://azurpoolconcept.com","note_priorite":"Haute","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"🔥 ANGLE PRODIGIO TRÈS FORT (zone Pampelonne/Ramatuelle = même cible Mitja). Positionnement : construction/rénovation piscines luxe sur-mesure Golfe St-Tropez 30 ans (débordement+naturelles+contemporaines). Gamme prix : 100-500k€ projet villa St-Tropez. Réalisations : villas Ramatuelle/Gassin/Pampelonne. Signaux marketing : mobile direct publié + Facebook actif / PAS d'ads = patron-artisan accessible.","sources":"https://azurpoolconcept.com | pagesjaunes | mappy"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"Blue Factory","ville":"Belgique","zone":"","dirigeant_principal":"Stéphane Meeùs + Philippe Meeùs","portable_dirigeant":"+32 472 23 95 54","telephone":"","email":"","email_dirigeant":"info@bluefactory.be","linkedin_dirigeant":"","site_web":"https://bluefactory.be","note_priorite":"Haute","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"🔥 ANGLE PRODIGIO TRÈS FORT (zone Lasne/Genval = CSP+++ wallon, équivalent BE de la cible PRODIGIO). Positionnement : pisciniste Brabant wallon béton+débordement+naturelles+jacuzzi+intérieures clientèle Lasne. Gamme prix : 100-400k€ projet villa premium Brabant. Réalisations : villas Lasne + Genval + Wavre. Signaux marketing : mobile belge direct publié + site honnête + peu d'ads = patrons-frères accessibles.","sources":"https://bluefactory.be | piscinesbelgique.be"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"Soredi-Henry (distributeur exclusif KLAFS Est France)","ville":"France","zone":"","dirigeant_principal":"Aurélien Henry (Directeur) + Vanessa Lefakis (Co-gérante)","portable_dirigeant":"","telephone":"03 89 71 24 11","email":"","email_dirigeant":"contact@klafs-sauna.com","linkedin_dirigeant":"","site_web":"https://klafs-sauna.com","note_priorite":"Haute","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"ANGLE PRODIGIO FORT (site daté + zéro Instagram + pas d'ads = besoin marketing énorme sur grand territoire). Positionnement : distributeur exclusif Klafs Est France sauna/hammam sur-mesure résidentiel et hôtelier 35 ans (atelier Compagnons du Devoir, showroom 200m²). Gamme prix : 30-150k€ projet privé (sauna+hammam combiné). Réalisations : showroom Orbey 200m² + chantiers grandes villas Alsace + Suisse romande.","sources":"societe.com | klafs-sauna.com | ehonline.eu"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"Kristech","ville":"France","zone":"","dirigeant_principal":"Nicolae-Cristian NISTOR (Président SAS)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"contact@kristech.fr","linkedin_dirigeant":"","site_web":"https://kristech.fr","note_priorite":"Haute","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"ANGLE PRODIGIO ÉLEVÉ (site fonctionnel mais peu sophistiqué + pas d'ads). Positionnement : constructeur hammam sur-mesure premium maçonné Paris + piscines IDF A à Z conception/fabrication/installation. Gamme prix : 30-80k€ hammam maçonné premium. Réalisations : hammams maçonnés villas IDF + douches sensorielles. Siège : 21 Avenue de l'Europe 92310 Sèvres.","sources":"societe.com SIREN 910576131 | kristech.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"Aqua-Real","ville":"France","zone":"","dirigeant_principal":"Maxime Le Dû (Directeur) + dirigeant SOPALD (président SAS)","portable_dirigeant":"","telephone":"02 47 29 11 64","email":"","email_dirigeant":"contact@aqua-real.fr","linkedin_dirigeant":"https://linkedin.com/in/maxime-le-dû-9329ba254","site_web":"https://aqua-real.fr","note_priorite":"Haute","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"ANGLE PRODIGIO MOYEN-FORT (site soigné mais peu d'ads + Instagram modeste). Positionnement : atelier artisanal Touraine spas/hammams/saunas/grottes glace sur-mesure haut de gamme résidentiel et thalasso 25 ans. Gamme prix : 30-100k€ résidentiel jusqu'à 500k€ centres. Réalisations : espaces wellness villa + références centres thalasso premium. Siège : 21 rue Amédée et Léon Bollée 37320 Esvres-sur-Indre.","sources":"aqua-real.fr | dnb.com | LinkedIn Maxime Le Dû"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"Spa One","ville":"France","zone":"","dirigeant_principal":"Fondateur non nommé (créé 2012, expérience depuis 1995)","portable_dirigeant":"","telephone":"04 93 32 55 75","email":"","email_dirigeant":"contact@spa-one.fr","linkedin_dirigeant":"","site_web":"https://spa-one.fr","note_priorite":"Haute","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"ANGLE PRODIGIO ÉLEVÉ (cible identique PRODIGIO + site honnête mais pas premium + peu d'ads). Positionnement : spécialiste installateur spa+sauna Côte d'Azur partenaire Röger Klafs + Canadian Spa International. Gamme prix : 30-120k€ projet villa CSP+++. Réalisations : villas Cannes/Mougins/Monaco. Siège : La Colle-sur-Loup 06480.","sources":"spa-one.fr | 100pour100spas.com"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"Piscines Caron / Le Bassin Bleu","ville":"France","zone":"","dirigeant_principal":"Renaud Suc (Directeur Le Bassin Bleu)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"contact@lebassinbleu.com","linkedin_dirigeant":"https://fr.linkedin.com/company/bassin-bleu","site_web":"https://lebassinbleu.com","note_priorite":"Haute","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"ANGLE PRODIGIO ÉLEVÉ sur zone Bassin/Cap Ferret (site moderne + photos pros + peu d'ads). Positionnement : piscines béton armé luxe + intérieures + urbaines système constructif breveté Caron clientèle CSP+++ Arcachon/Cap Ferret. Gamme prix : 80-300k€ piscine béton sur-mesure. Réalisations : piscines Cap Ferret + Pyla + villas urbaines Bordeaux. Siège : Le Bouscat 33110.","sources":"lebassinbleu.com | piscines-caron.com | LinkedIn"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"JPS Spapiscines (réseau L'Esprit Piscine)","ville":"France","zone":"","dirigeant_principal":"Yann Le Petit (Président) + Adrien Bloquet + héritage Patrick Bloquet (fondateur 1997)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"https://linkedin.com/in/yann-le-petit-jps-spapiscines","site_web":"https://esprit-piscine.fr/spapiscines-jps-nantes","note_priorite":"Haute","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"ANGLE PRODIGIO MOYEN-FORT (site Esprit Piscine pro + LinkedIn actif Yann Le Petit). Positionnement : piscines sur-mesure intérieures + extérieures + spas membre du groupement L'Esprit Piscine (30 piscinistes premium France). Gamme prix : 50-200k€ piscine sur-mesure résidentielle. Réalisations : piscines intérieures villas Loire-Atlantique + couloirs nage. Siège : La Plaine-sur-Mer 44770.","sources":"societe.com SIREN 411534480 | pappers | LinkedIn"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"Piscines Logintec","ville":"France","zone":"","dirigeant_principal":"Fondateur non public (20+ ans expérience)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://piscines-logintec.com","note_priorite":"Haute","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"ANGLE PRODIGIO ÉLEVÉ (site dense mais design daté + pas d'ads visibles). Positionnement : constructeur piscines béton armé haut de gamme sur-mesure 06/PACA 2000+ bassins pool house + spas intégrés. Gamme prix : 80-400k€ piscine béton premium villa. Réalisations : villas Cannes/Antibes/Mougins/St-Tropez. Siège : Antibes 06160.","sources":"piscines-logintec.com"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"Nicollier Group SA (Carré Bleu Suisse)","ville":"Suisse","zone":"","dirigeant_principal":"François Nicollier (Président CA) + Sébastien Nicollier (Administrateur)","portable_dirigeant":"","telephone":"+41 27 747 13 00","email":"","email_dirigeant":"info@nicollier.ch","linkedin_dirigeant":"","site_web":"https://nicollier.ch","note_priorite":"Haute","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"ANGLE PRODIGIO ÉLEVÉ sur zone chalet/villa (site pro + réalisations photos qualité + peu d'ads). Positionnement : pisciniste maçonné Suisse romande depuis 1979 partenaire Carré Bleu international depuis 2000 piscines intérieures luxe 70 collaborateurs. Gamme prix : 150-600k€ piscine intérieure Valais/Vaud. Réalisations : villas Valais + chalets Verbier/Crans + bassins urbains Genève. Siège : Chemin du Rhône 133 1926 Fully (VS).","sources":"moneyhouse | nicollier.ch | search.ch"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"BE Piscines SA","ville":"Suisse","zone":"","dirigeant_principal":"Alain Caberlon (Président CA) + Jérémy Caberlon (équipe dirigeante)","portable_dirigeant":"","telephone":"+41 22 (à confirmer)","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://bepiscines.ch","note_priorite":"Haute","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"ANGLE PRODIGIO ÉLEVÉ (site fonctionnel + présence digitale faible). Positionnement : concepteur/constructeur piscines + abris + spas + sauna + hammam entreprise familiale 1960 père en fils partenaire EuroPiscine. Gamme prix : 80-400k€ projet complet luxe. Réalisations : villas Genève + Veyrier. Siège : Rue de la Rôtisserie 6 1204 Genève.","sources":"bepiscines.ch | europiscine.com | local.ch"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"h2o facilities (h2o piscines)","ville":"Suisse","zone":"","dirigeant_principal":"Didier Menoud (Directeur depuis reprise des co-fondateurs retraités)","portable_dirigeant":"","telephone":"+41 22 879 99 50","email":"","email_dirigeant":"irina.stoica@h2o-f.ch","linkedin_dirigeant":"","site_web":"https://h2o-piscines.ch","note_priorite":"Haute","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"ANGLE PRODIGIO ÉLEVÉ (site très pro + photos qualité agence + peu d'ads). Positionnement : pisciniste luxe Suisse romande depuis 2007 35 collaborateurs ingénieurs+designers piscines intérieures climatisées sur-mesure. Gamme prix : 200-700k€ piscine intérieure climatisée villa. Réalisations : villas Genève/Vaud/Valais + bassins urbains. Siège : Avenue des Grandes Communes 8 1213 Genève (Onex).","sources":"h2o-f.ch | h2o-piscines.ch"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"Piscine & Spa SA","ville":"Suisse","zone":"","dirigeant_principal":"Fondateur non public (fondé 1989)","portable_dirigeant":"","telephone":"+41 22 (à confirmer)","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://piscine-spa.ch","note_priorite":"Haute","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"ANGLE PRODIGIO ÉLEVÉ (site pro + niche très haut ticket). Positionnement : constructeur piscine sur-mesure Genève depuis 1989 spécialisé couloirs de nage + piscines intérieures climatisées + planchers mobiles + inox. Gamme prix : 200-800k€ piscine intérieure inox couloir nage. Réalisations : villas Genève + bassins luxe couloir nage. Siège : Genève.","sources":"piscine-spa.ch"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"Tahiti Piscines SA","ville":"Belgique","zone":"","dirigeant_principal":"Direction non publique (entreprise 45 ans)","portable_dirigeant":"","telephone":"+32 4 (Awans — à confirmer)","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://tahitipiscines.be","note_priorite":"Haute","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"ANGLE PRODIGIO ÉLEVÉ (site fonctionnel + présence digitale modérée). Positionnement : constructeur piscines intérieures + extérieures Belgique depuis 45 ans gamme wellness complète (spa+sauna+hammam+infrarouge). Gamme prix : 80-350k€ projet résidentiel haut de gamme. Réalisations : piscines villas Liège + Bruxelles. Siège : Rue de l'Estampage 16 4340 Awans (Liège).","sources":"companyweb.be BE0872236371 | tahitipiscines.be"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"Piscines Infinity","ville":"Belgique","zone":"","dirigeant_principal":"Direction non publique","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://piscines-infinity.be","note_priorite":"Haute","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"ANGLE PRODIGIO ÉLEVÉ (zone CSP+++ wallone — site moderne + photos qualité). Positionnement : constructeur piscines béton armé monolithique luxe Bruxelles + Brabant spécialisation piscines intérieures + débordement + mosaïque. Gamme prix : 150-500k€ piscine béton intérieure premium. Réalisations : villas Brabant wallon + Bruxelles Uccle/Lasne. Siège : Bruxelles.","sources":"piscines-infinity.be"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"Instal-Fit Sàrl","ville":"Luxembourg","zone":"","dirigeant_principal":"Direction non publique (40+ ans expérience)","portable_dirigeant":"","telephone":"+352 (à confirmer)","email":"","email_dirigeant":"contact@instalfit.lu","linkedin_dirigeant":"https://lu.linkedin.com/company/instalfit","site_web":"https://instalfit.lu","note_priorite":"Haute","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"ANGLE PRODIGIO ÉLEVÉ (Luxembourg = pouvoir d'achat extrême — site moderne + LinkedIn actif). Positionnement : leader home wellness Luxembourg 40+ ans piscines/spas/saunas/hammams sur-mesure résidentiel haut de gamme. Gamme prix : 80-400k€ projet complet villa Lux. Réalisations : villas Howald + Kirchberg + résidentiel premium Lux. Siège : ZI Hamm 7A rue de Bitbourg L-1273 Luxembourg.","sources":"instalfit.lu | paperjam.lu"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"Vielliard & Francheteau Architectures (architecte hybride)","ville":"France","zone":"","dirigeant_principal":"Thomas Vielliard + Jacques Francheteau (co-fondateurs cabinet 2018)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://vf-architectures.fr","note_priorite":"Haute","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"🎯 PRESCRIPTEUR PRODIGIO TRÈS FORT — si tu signes 1 architecte, tu accèdes à TOUTE leur clientèle CSP+++ d'un coup. Positionnement : cabinet architecte luxe villas + maisons contemporaines avec offre wellness suite intégrée (spa+sauna+hammam+piscine intérieure sur-mesure clé en main). Gamme prix : wellness suite 200-800k€ dans projet villa global 3-15M€. Réalisations : villas Saint-Jean-Cap-Ferrat + Eze + Saint-Tropez + Cap-Ferrat. Signaux marketing : site soigné + presse luxe (RREC Rolls-Royce 2024). Bureaux : Écully (69) + Nice (06) + Golfe Saint-Tropez.","sources":"vf-architectures.fr | archiliste.fr"}},

  // ─── PRIORITÉ MOYENNE ──────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"Roca Spa (ADEO SARL)","ville":"France","zone":"","dirigeant_principal":"Jérémy Berteloot (Gérant depuis sept. 2024)","portable_dirigeant":"+33 6 52 01 63 73","telephone":"","email":"","email_dirigeant":"contact@rocaspa.fr","linkedin_dirigeant":"","site_web":"https://rocaspa.fr","note_priorite":"Moyenne","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"🔥 Mobile direct publié + marketing digital basique = petite structure accessible. Positionnement : distributeur et concepteur spas premium 2 showrooms (Nord+Sud) couverture France Europe. Gamme prix : 15-50k€ spa premium installé. Réalisations : showrooms Bourbourg + Rivesaltes. Siège : 15 rue du Guindal 59630 Bourbourg + 3 rue des Caroubiers 66600 Rivesaltes.","sources":"pappers SIREN 507450971 | rocaspa.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"Spa-Mosaïque","ville":"France","zone":"","dirigeant_principal":"Direction non publique","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"contact@spa-mosaique.com","linkedin_dirigeant":"","site_web":"https://spa-mosaique.com","note_priorite":"Moyenne","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"ANGLE PRODIGIO ÉLEVÉ (site léger + peu de digital). Positionnement : fabricant spa mosaïque haut de gamme sur-mesure matériaux nobles IDF + Nord. Gamme prix : 15-60k€ spa mosaïque sur-mesure. Réalisations : spas carrelés intégrés architecture villa. Siège : Paris/Nord (non confirmé).","sources":"spa-mosaique.com"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"Nordique France (distributeur exclusif Tylö Helo)","ville":"France","zone":"","dirigeant_principal":"Direction non publique (entreprise familiale 1973)","portable_dirigeant":"","telephone":"01 49 09 60 60","email":"","email_dirigeant":"contact@nordiquefrance.com","linkedin_dirigeant":"https://fr.linkedin.com/company/nordique-france","site_web":"https://nordiquefrance.com","note_priorite":"Moyenne","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"ANGLE PRODIGIO MOYEN (présence digitale honnête + Instagram actif modeste). Positionnement : distributeur exclusif Tylö (Suède) depuis 1973 sauna/hammam/spa premium résidentiel et pro. Gamme prix : 20-80k€ équipement résidentiel haut de gamme. Réalisations : showrooms premium Paris+Lyon. Siège : showroom Paris 14e + Saint-Priest Technoland (siège Épône 78).","sources":"nordiquefrance.com | LinkedIn"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"Mori Piscines SA","ville":"Suisse","zone":"","dirigeant_principal":"Norbert Mori (Membre CA) + Sylvie Jacquet (mandataire)","portable_dirigeant":"","telephone":"+41 22 (à confirmer)","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://moripiscines.ch","note_priorite":"Moyenne","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"ANGLE PRODIGIO MOYEN-FORT (site sobre + peu d'ads + bouche-à-oreille). Positionnement : pisciniste Genève+Lausanne depuis 1989 ~900 piscines conception/construction/rénovation luxe bureau d'études interne. Gamme prix : 150-500k€ piscine luxe résidentielle. Réalisations : villas Genève + Lausanne CSP+++. Siège : Chemin de la Pallanterie 7-8 1252 Meinier (GE).","sources":"moneyhouse | business-monitor.ch | moripiscines.ch"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"Designo Piscines (Designo Wellness Sàrl)","ville":"Suisse","zone":"","dirigeant_principal":"Olivier Henrotte (Co-fondateur Designo Wellness Sàrl)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"https://linkedin.com/in/olivier-henrotte-a720805","site_web":"https://designo-piscines.ch","note_priorite":"Moyenne","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"ANGLE PRODIGIO MOYEN-FORT (LinkedIn perso fondateur actif + site moderne). Positionnement : pisciniste Suisse romande piscines monocoque inox depuis 2022 (abandon béton) spécialiste piscine intérieure année. Gamme prix : 150-500k€ piscine inox intérieure. Réalisations : villas Vaud + Genève + Valais. Siège : Suisse romande (4 bureaux).","sources":"designo-piscines.ch | LinkedIn Olivier Henrotte"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"Rêv'extérieur","ville":"Luxembourg","zone":"","dirigeant_principal":"Direction non publique","portable_dirigeant":"","telephone":"+352 277 602 40","email":"","email_dirigeant":"contact@revexterieur.lu","linkedin_dirigeant":"https://lu.linkedin.com/company/revexterieur","site_web":"https://revexterieur.lu","note_priorite":"Moyenne","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"ANGLE PRODIGIO MOYEN-FORT (site moderne + présence digitale correcte). Positionnement : magasin 300m² Howald spas/piscines/saunas/hammams/infrarouge sur-mesure haut de gamme visite à domicile + projet clé en main. Gamme prix : 50-300k€ projet wellness résidentiel premium. Réalisations : villas Luxembourg + Moselle française. Siège : 272 Route de Thionville L-5884 Howald.","sources":"revexterieur.lu | editus.lu | yellow.lu"}},

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"Concept Détente","ville":"Luxembourg","zone":"","dirigeant_principal":"Nunes José + Rech René-Pierre (co-fondateurs 20+ ans expérience)","portable_dirigeant":"","telephone":"+352 (à confirmer)","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://conceptdetente.com","note_priorite":"Moyenne","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"ANGLE PRODIGIO MOYEN-FORT (site honnête + peu d'ads). Positionnement : pisciniste Luxembourg piscines intérieures+extérieures + spas + saunas + hammams + pergolas créateurs identifiés en duo. Gamme prix : 60-300k€ projet villa résidentielle. Réalisations : villas sud-Luxembourg + frontière FR. Siège : Esch-sur-Alzette.","sources":"conceptdetente.com | concept-detente.lu"}},

  // ─── PRIORITÉ BASSE ─────────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"experience-domicile","categorie":"Spa intérieur / hammam / piscine intérieure","entreprise":"Diffazur Piscines","ville":"France","zone":"","dirigeant_principal":"Monique Richard-Benielli (fondatrice / direction post-décès G. Benielli avril 2025) + 2e/3e génération famille","portable_dirigeant":"","telephone":"04 93 14 16 16","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://diffazur.fr","note_priorite":"Basse","source":"fichier spa-hammam-piscine enrichi","statut":"À contacter","data":{"note":"⚠️ MOINS D'ANGLE PRODIGIO (marketing digital lourd + ads visibles = trop gros, pas pure cible). Positionnement : leader européen piscines béton 350+ salariés segment luxe + segment moyen-gamme — gamme premium dans l'offre pas exclusif premium. Gamme prix : 40-300k€+ piscine béton premium. Réalisations : plus de 90.000 piscines réalisées villas Côte d'Azur. Siège : Allée des Architectes 06700 Saint-Laurent-du-Var.","sources":"wikipedia | diffazur.fr | pagesjaunes"}}

].map(p => ({ qualification: '', date_relance: null, ne_plus_contacter: false, ...p }))
