// Cibles RÉELLES « Traiteurs premium / gastronomiques » (INDESCALE).
// 24 cibles FR/CH/BE/LU. Liste figée. Notes denses regroupant positionnement, gamme prix,
// réalisations, signaux marketing. 'n/a' laissé vide (jamais inventé).
// Spécificité secteur : portables 06/07 quasi-introuvables publiquement (CEO derrière standard).

let _c = 0
const cid = () => 'trait-' + (++_c)

export const TRAITEURS_PREMIUM_PROSPECTS = [
  // ─── PRIORITÉ HAUTE ────────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Traiteurs premium / gastronomiques","entreprise":"Groupe Potel et Chabot (Momense)","ville":"France","zone":"","dirigeant_principal":"Edouard Flateau (Président depuis oct. 2024) / Alain Postic (DG Momense)","portable_dirigeant":"","telephone":"+33 1 53 23 15 15","email":"","email_dirigeant":"contact@poteletchabot.com","linkedin_dirigeant":"https://linkedin.com/in/edouardflateau","site_web":"https://groupepoteletchabot.com","note_priorite":"Haute","source":"fichier traiteurs premium enrichi","statut":"À contacter","data":{"note":"🔥 Refonte identité 2026 + relance Dalloyau + expansion Côte d'Azur — CEO Edouard Flateau ex-Bain = appétence ROI. Positionnement : traiteur historique 1820 + nouveau groupe Momense (fusion Saint Clair + relance Dalloyau). Gamme prix : 200-500€/pers événementiel prestige. Réalisations : galas Élysée/UNESCO/Cannes + déploiement Côte d'Azur 2026. Signaux marketing : refonte identité 2026 + relance Dalloyau + expansion Côte d'Azur = momentum acquisition. Siège : 3 rue de Berri 75008 Paris.","sources":"consultor.fr | lhotellerie-restauration.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Traiteurs premium / gastronomiques","entreprise":"Dalloyau Réceptions","ville":"France","zone":"","dirigeant_principal":"Stéphane Facchin (Président Réceptions) - sous tutelle Potel & Chabot","portable_dirigeant":"","telephone":"+33 1 43 59 18 10","email":"","email_dirigeant":"reception@dalloyau.fr","linkedin_dirigeant":"https://linkedin.com/in/stephane-facchin","site_web":"https://dalloyaureceptions.fr","note_priorite":"Haute","source":"fichier traiteurs premium enrichi","statut":"À contacter","data":{"note":"🔥 Marque iconique rachetée 3,3M€ — BESOIN URGENT de leads pour rentabiliser. Positionnement : Maison 1802 EPV — rachetée par Potel & Chabot — relance prévue 2026. Gamme prix : 120-300€/pers. Réalisations : réceptions corporate + mariages parisiens haut de gamme. Signaux marketing : marque en cours de refonte complète = besoin urgent acquisition pour redéploiement. Siège : 2 Place Edouard VII 75009 Paris.","sources":"journalduluxe.fr | 1001traiteurs.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Traiteurs premium / gastronomiques","entreprise":"Fauchon L'Événement","ville":"France","zone":"","dirigeant_principal":"Augustin de Beaurepaire (DG Cultures Food) / Christoph Descamps (Dir. marque Fauchon)","portable_dirigeant":"","telephone":"+33 1 70 39 38 00","email":"","email_dirigeant":"contact@flevenement.fr","linkedin_dirigeant":"https://linkedin.com/in/christoph-descamps","site_web":"https://flevenement.fr","note_priorite":"Haute","source":"fichier traiteurs premium enrichi","statut":"À contacter","data":{"note":"🔥 Marque iconique en RECONSTRUCTION post-liquidation 2020 — besoin MAX de notoriété. Positionnement : marque luxe relancée par Cultures Food group. Gamme prix : 150-350€/pers. Réalisations : branche Côte d'Azur en développement actif. Signaux marketing : marque iconique en RECONSTRUCTION = besoin maximal de leads/notoriété. Siège : 11 rue du Landy 93400 Saint-Ouen-sur-Seine.","sources":"meet-in.fr | email-gourmand.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Traiteurs premium / gastronomiques","entreprise":"Giry Traiteur (Groupe TOSEVENTS)","ville":"France","zone":"","dirigeant_principal":"Nicolas Bret (fondateur) / Marion Mary (DG groupe TOSEVENTS)","portable_dirigeant":"","telephone":"+33 4 93 47 47 47","email":"","email_dirigeant":"contact@giry-traiteur.com","linkedin_dirigeant":"https://linkedin.com/in/marion-mary-tosevents","site_web":"https://giry-traiteur.com","note_priorite":"Haute","source":"fichier traiteurs premium enrichi","statut":"À contacter","data":{"note":"🔥 Maison 1968 + groupe TOSEVENTS en expansion multi-villes + ISO 20121. Positionnement : Cannes/Monaco/Saint-Tropez (Lyon/Grenoble/Marseille/Paris/Cannes). Gamme prix : 150-400€/pers. Réalisations : Palais des Festivals Cannes + yachts + villas Monaco-Saint-Tropez. Signaux marketing : groupe en expansion + label ISO + Traiteurs de France. Siège : Cannes (06).","sources":"giry-traiteur.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Traiteurs premium / gastronomiques","entreprise":"Lacoste Traiteur","ville":"France","zone":"","dirigeant_principal":"Didier Oudin (PDG depuis 2005) / Jeremie Oudin (DG)","portable_dirigeant":"","telephone":"+33 5 56 57 59 67","email":"","email_dirigeant":"contact@lacoste-traiteur.com","linkedin_dirigeant":"https://linkedin.com/in/jeremie-oudin-027b1728","site_web":"https://lacoste-traiteur.com","note_priorite":"Haute","source":"fichier traiteurs premium enrichi","statut":"À contacter","data":{"note":"Direction père-fils + LinkedIn actif = approche directe possible. Positionnement : maison fondée 1983 par Chef Jean-Claude Lacoste — rachetée 2005 — membre Traiteurs de France 2006. Gamme prix : 100-250€/pers. Réalisations : mariages haut de gamme Médoc + Arcachon. Signaux marketing : direction père-fils LinkedIn actif. Siège : 47 Avenue de la Forêt - ZAC Mermoz 33327 Eysines.","sources":"lacoste-traiteur.com | linkedin"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Traiteurs premium / gastronomiques","entreprise":"Erisay Réceptions / Maison Erisay","ville":"France","zone":"","dirigeant_principal":"Direction Erisay + Chefs signature Fabrice Fontaine (finaliste Bocuse d'Or) et Dominique Bréban","portable_dirigeant":"","telephone":"+33 2 32 33 81 81","email":"","email_dirigeant":"contact@erisay-traiteur.fr","linkedin_dirigeant":"https://linkedin.com/in/fabrice-fontaine-chef","site_web":"https://erisay-traiteur.fr","note_priorite":"Haute","source":"fichier traiteurs premium enrichi","statut":"À contacter","data":{"note":"🔥 NOUVEAU membre Traiteurs de France 2024 = ambition de scale = matching parfait PRODIGIO. Positionnement : 50 ans d'existence — 20 à 5000 invités. Gamme prix : 100-250€/pers. Réalisations : mariages prestige Normandie/Paris-rurale. Signaux marketing : nouveau membre Traiteurs de France 2024. Siège : Normandie - secteur Eure (Rouen) + Paris/Evreux/Chartres.","sources":"traiteurs-de-france.com | mariages.net"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Traiteurs premium / gastronomiques","entreprise":"Traiteur Paulus","ville":"Belgique","zone":"","dirigeant_principal":"Patrick Celeghin (CEO/chef - Mastercooks of Belgium) / Grégory Vaussort (co-actionnaire depuis 2022)","portable_dirigeant":"","telephone":"+32 83 23 40 00","email":"","email_dirigeant":"info@paulus.be","linkedin_dirigeant":"https://linkedin.com/in/patrick-celeghin","site_web":"https://paulus.be","note_priorite":"Haute","source":"fichier traiteurs premium enrichi","statut":"À contacter","data":{"note":"🔥 Rachat nov. 2022 — phase classique de scale post-acquisition = cible PRODIGIO majeure. Positionnement : 20+ ans + membre Mastercooks of Belgium. Gamme prix : 80-200€/pers. Réalisations : galas 1000+ convives + RSC Anderlecht + mariages prestige. Signaux marketing : rachat 2022 = phase de scale. Siège : Allée des Artisans 11 5590 Ciney. Bureaux Wallonie + Bruxelles +32 2 513 93 47.","sources":"paulus.be | horecamagazine.be"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Traiteurs premium / gastronomiques","entreprise":"Choux de Bruxelles","ville":"Belgique","zone":"","dirigeant_principal":"Chef Damien Audusseau (Executive Chef depuis 2017 - Mastercooks of Belgium - Gault&Millau Silver Chef 2020)","portable_dirigeant":"","telephone":"+32 2 359 92 40","email":"","email_dirigeant":"info@chou.be","linkedin_dirigeant":"https://linkedin.com/in/damien-audusseau","site_web":"https://chouxdebruxelles.be","note_priorite":"Haute","source":"fichier traiteurs premium enrichi","statut":"À contacter","data":{"note":"🔥 Chef star + lieux événementiels propres + référence absolue Bruxelles. Positionnement : 30+ ans + référence Bruxelles. Gamme prix : 150-350€/pers. Réalisations : mariages prestige Bruxelles + galas internationaux. Signaux marketing : chef à forte notoriété médiatique = écosystème éditorial déjà actif. Siège : Boulevard Louis Schmidt 1 1040 Bruxelles.","sources":"chouxdebruxelles.be | mastercooks.be"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Traiteurs premium / gastronomiques","entreprise":"Steffen Traiteur (Groupe Steffen)","ville":"Luxembourg","zone":"","dirigeant_principal":"Tom Steffen (CEO Groupe Steffen - diplômé Institut Paul Bocuse)","portable_dirigeant":"","telephone":"+352 399 650 300","email":"","email_dirigeant":"reception@steffen.lu","linkedin_dirigeant":"https://linkedin.com/in/tom-steffen-luxembourg","site_web":"https://steffentraiteur.lu","note_priorite":"Haute","source":"fichier traiteurs premium enrichi","statut":"À contacter","data":{"note":"🔥 CEO actif médias + groupe diversifié = signaux scale. Positionnement : maison 1989 — 3e génération — groupe complet (traiteur + boucherie + restos). Gamme prix : 100-250€/pers. Réalisations : mariages Grand-Duché + réceptions corporate haut de gamme. Signaux marketing : CEO actif médias (interviews vidéo). Siège : Z.A. Op Zaemer 5 L-8366 Hagen / Steinfort.","sources":"steffentraiteur.lu | facebook"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Traiteurs premium / gastronomiques","entreprise":"Gourmet Brothers Groupe","ville":"Suisse","zone":"","dirigeant_principal":"Benjamin Luzuy (Chef-fondateur célèbre RTS) + Marie Luzuy + Paul Cassigneul","portable_dirigeant":"","telephone":"+41 22 318 70 70","email":"","email_dirigeant":"info@gourmetbrothers.ch","linkedin_dirigeant":"https://linkedin.com/in/benjamin-luzuy","site_web":"https://gourmetbrothers.ch","note_priorite":"Haute","source":"fichier traiteurs premium enrichi","statut":"À contacter","data":{"note":"🔥 Chef TV (émission RTS) = forte notoriété media + approche moderne. Positionnement : Suisse romande (Genève + national). Gamme prix : 150-350 CHF/pers. Réalisations : mariages prestige Genève/Lausanne + box gastronomiques. Signaux marketing : chef star avec emprise media = écosystème acquisition naturel. Siège : Genève.","sources":"gaultmillau.ch | suisse-conventionbureau.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Traiteurs premium / gastronomiques","entreprise":"Bijoux Catering","ville":"Suisse","zone":"","dirigeant_principal":"Rachid Benboudy (Chef-fondateur) + Carlos Diogo Machado Alves + Tobias Majewski","portable_dirigeant":"","telephone":"+41 44 800 80 80","email":"","email_dirigeant":"info@bijouxcatering.ch","linkedin_dirigeant":"https://linkedin.com/in/rachid-benboudy","site_web":"https://bijouxcatering.ch","note_priorite":"Haute","source":"fichier traiteurs premium enrichi","statut":"À contacter","data":{"note":"🔥 Positionnement aviation+luxe = clientèle UHNW = ticket très élevé. Positionnement : luxe + private jets/aviation + réceptions privées + mariages exclusifs. Gamme prix : 200-500 CHF/pers. Réalisations : mariages VIP Zurich + aviation privée + lounges aéroports. Signaux marketing : aviation+luxe = clientèle UHNW. Siège : Zurich. Couvre Zurich + Bâle + Genève.","sources":"bijouxcatering.ch | moneyhouse.ch"}},

  // ─── PRIORITÉ MOYENNE ──────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Traiteurs premium / gastronomiques","entreprise":"Maison Lenôtre","ville":"France","zone":"","dirigeant_principal":"Franck Chanevas (DG depuis 2025) / Nathalie Bellon-Szabo (Présidente du board)","portable_dirigeant":"","telephone":"+33 1 30 81 46 46","email":"","email_dirigeant":"contact@lenotre.com","linkedin_dirigeant":"","site_web":"https://lenotre.com","note_priorite":"Moyenne","source":"fichier traiteurs premium enrichi","statut":"À contacter","data":{"note":"Référence absolue gastronomie française depuis 1957 (Sodexo group). Positionnement : France + International. Gamme prix : 150-400€/pers événementiel. Réalisations : mariages prestige Paris/Versailles/Riviera + galas internationaux. Signaux marketing : SEO ultra dominant + presse permanente + plan 'doubler CA international en 5 ans'. Siège : 40 Rue Pierre Curie 78370 Plaisir.","sources":"lejdd.fr | hr-infos.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Traiteurs premium / gastronomiques","entreprise":"Saint Clair Le Traiteur","ville":"France","zone":"","dirigeant_principal":"Alain Postic (DG Momense)","portable_dirigeant":"","telephone":"+33 1 41 96 22 22","email":"","email_dirigeant":"info@saintclair.com","linkedin_dirigeant":"https://linkedin.com/in/alain-postic","site_web":"https://saintclair.com","note_priorite":"Moyenne","source":"fichier traiteurs premium enrichi","statut":"À contacter","data":{"note":"Sous bannière Momense en pleine restructuration de marque. Positionnement : branche premium de Momense créée par François Clerc (resto étoilé) — 5 lieux d'exception Paris. Gamme prix : 150-350€/pers. Réalisations : Pavillon Dauphine Saint Clair + mariages prestige Paris. Signaux marketing : restructuration en cours. Siège : 7 avenue Edouard Belin 92500 Rueil-Malmaison.","sources":"saintclair.com | meet-in.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Traiteurs premium / gastronomiques","entreprise":"LeCADET Réceptions","ville":"France","zone":"","dirigeant_principal":"Famille fondatrice (Thomas et Alexandre - direction commerciale active)","portable_dirigeant":"","telephone":"+33 1 39 14 20 67","email":"","email_dirigeant":"contact@lecadet.fr","linkedin_dirigeant":"https://linkedin.com/company/lecadet-traiteur","site_web":"https://lecadet.fr","note_priorite":"Moyenne","source":"fichier traiteurs premium enrichi","statut":"À contacter","data":{"note":"Famille indépendante 1987 + multi-marques (LeCADET / Lina&Louis / Fée d'Un Jour). Positionnement : Paris/IDF. Gamme prix : 80-200€/pers. Réalisations : mariages IDF + galas corporate. Signaux marketing : multi-marques + RSE = signaux marketing actifs. Siège : 72-74 rue du Capitaine Maignan 78800 Houilles.","sources":"lecadet.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Traiteurs premium / gastronomiques","entreprise":"Pavillon Traiteur","ville":"France","zone":"","dirigeant_principal":"Direction familiale + Chef Philippe Joannès (MOF) en partenariat","portable_dirigeant":"","telephone":"+33 4 92 28 22 60","email":"","email_dirigeant":"contact@pavillontraiteur.fr","linkedin_dirigeant":"https://linkedin.com/in/philippe-joannes-mof","site_web":"https://pavillontraiteur.fr","note_priorite":"Moyenne","source":"fichier traiteurs premium enrichi","statut":"À contacter","data":{"note":"Référence haut de gamme Riviera depuis 1990 + labo 2000m² + MOF associé. Positionnement : Côte d'Azur (Monaco-Saint-Tropez). Gamme prix : 180-400€/pers. Réalisations : mariages 100-1000 invités + villas/yachts Riviera. Signaux marketing : présence Riviera dominante + chef MOF = positionnement très défendable. Siège : 770 chemin Saint-Bernard 06220 Vallauris + labo Mouans-Sartoux.","sources":"pavillontraiteur.fr | cotedazurfrance.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Traiteurs premium / gastronomiques","entreprise":"Onzième Art Traiteur","ville":"France","zone":"","dirigeant_principal":"Direction non publique","portable_dirigeant":"","telephone":"+33 4 94 14 22 22","email":"","email_dirigeant":"contact@11emeart.com","linkedin_dirigeant":"","site_web":"https://11emeart.com","note_priorite":"Moyenne","source":"fichier traiteurs premium enrichi","statut":"À contacter","data":{"note":"Traiteur signature 10+ ans. Positionnement : Marseille à Monaco (St-Tropez/Cannes/Nice). Gamme prix : 150-350€/pers. Réalisations : mariages exception Antibes/Grimaud/Roquebrune-Cap-Martin. Signaux marketing : site très éditorial + scénographies sur-mesure. Siège : La Valette-du-Var (83) près de Toulon.","sources":"onziemearttraiteur.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Traiteurs premium / gastronomiques","entreprise":"Monblanc Traiteur","ville":"France","zone":"","dirigeant_principal":"Bernard Monblanc (PDG) / Morgan Monblanc (manager) - Christophe (responsable mariage)","portable_dirigeant":"","telephone":"+33 5 56 21 73 73","email":"","email_dirigeant":"contact@monblanc-traiteur.com","linkedin_dirigeant":"","site_web":"https://monblanc-traiteur.com","note_priorite":"Moyenne","source":"fichier traiteurs premium enrichi","statut":"À contacter","data":{"note":"Maison familiale 3 générations — boucherie pivotée vers événementiel. Positionnement : Bordeaux Sud-Ouest. Gamme prix : 80-180€/pers. Réalisations : mariages prestige Médoc/Pessac-Léognan. Signaux marketing : famille fondatrice = décision rapide possible. Siège : 18 Avenue Pierre Mendès France 33127 Saint-Jean-d'Illac.","sources":"monblanc-traiteur.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Traiteurs premium / gastronomiques","entreprise":"Humblot Expériences","ville":"France","zone":"","dirigeant_principal":"Direction non publique (Lucie Lavelle = Marketing & Com)","portable_dirigeant":"","telephone":"+33 5 57 26 24 26","email":"","email_dirigeant":"contact@humblot-traiteur.fr","linkedin_dirigeant":"https://linkedin.com/in/lucie-lavelle","site_web":"https://humblot-experiences.com","note_priorite":"Moyenne","source":"fichier traiteurs premium enrichi","statut":"À contacter","data":{"note":"30+ ans + membre fondateur Traiteurs de France + correspondant Potel & Chabot en Aquitaine. Positionnement : Bordeaux/La Rochelle/Biarritz. Gamme prix : 100-280€/pers. Réalisations : mariages exception + galas jusqu'à 6000 invités. Signaux marketing : marque Sud-Ouest sans CEO LinkedIn visible — passer par Lucie Lavelle. Siège : Bordeaux (33).","sources":"humblot-experiences.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Traiteurs premium / gastronomiques","entreprise":"Husser Traiteur","ville":"France","zone":"","dirigeant_principal":"Famille Husser (Dany Husser branche pâtisserie)","portable_dirigeant":"","telephone":"+33 3 88 50 09 38","email":"","email_dirigeant":"contact@hussertraiteur.fr","linkedin_dirigeant":"","site_web":"https://hussertraiteur.fr","note_priorite":"Moyenne","source":"fichier traiteurs premium enrichi","statut":"À contacter","data":{"note":"Maison familiale historique + rejoint Traiteurs de France récemment. Positionnement : Alsace (Strasbourg + Bas-Rhin). Gamme prix : 80-200€/pers. Réalisations : mariages prestige Alsace + châteaux Route des Vins. Signaux marketing : famille + ambition réseau premium = signaux scale. Siège : Strasbourg/Eckbolsheim.","sources":"hussertraiteur.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Traiteurs premium / gastronomiques","entreprise":"Hartichoc","ville":"Belgique","zone":"","dirigeant_principal":"Tinne Milis et Sarah Milis (sœurs co-fondatrices - 25+ ans expérience)","portable_dirigeant":"+32 498 50 30 06","telephone":"","email":"","email_dirigeant":"info@hartichoc.be","linkedin_dirigeant":"","site_web":"https://hartichoc.be","note_priorite":"Moyenne","source":"fichier traiteurs premium enrichi","statut":"À contacter","data":{"note":"🔥 Portable 0498 = ligne dirigeantes directe. Positionnement : maison fondée par sœurs Milis — mariages sur-mesure + cuisine italienne. Gamme prix : 80-200€/pers. Réalisations : mariages premium Bruxelles + Brabant. Signaux marketing : portable direct dirigeantes. Siège : Leuvensesteenweg 228B 3370 Boutersem.","sources":"hartichoc.be"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Traiteurs premium / gastronomiques","entreprise":"Pèitry Le Traiteur","ville":"Luxembourg","zone":"","dirigeant_principal":"Quentin Debailleux (Chef de cuisine - dirigeant)","portable_dirigeant":"","telephone":"+352 26 78 75 98","email":"","email_dirigeant":"traiteur@peitry.lu","linkedin_dirigeant":"https://linkedin.com/in/quentin-debailleux","site_web":"https://traiteur.peitry.lu","note_priorite":"Moyenne","source":"fichier traiteurs premium enrichi","statut":"À contacter","data":{"note":"15+ ans expérience + chef-dirigeant approche signature. Positionnement : Luxembourg + Grande Région. Gamme prix : 90-220€/pers. Réalisations : mariages Luxembourg + chef à domicile prestige. Signaux marketing : petite structure agile + chef-CEO = décision rapide. Siège : 18 Route de Luxembourg L-6910 Roodt-sur-Syre.","sources":"traiteur.peitry.lu"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Traiteurs premium / gastronomiques","entreprise":"Kaempff-Kohler","ville":"Luxembourg","zone":"","dirigeant_principal":"Guill Kaempff et Christian Kaempff (3e génération - formés Munich/Londres)","portable_dirigeant":"","telephone":"+352 47 47 47-1","email":"","email_dirigeant":"info@kaempff-kohler.lu","linkedin_dirigeant":"https://linkedin.com/company/kaempff-kohler","site_web":"https://kaempff-kohler.lu","note_priorite":"Moyenne","source":"fichier traiteurs premium enrichi","statut":"À contacter","data":{"note":"Centenaire (1922) — patrimoine à valoriser via storytelling acquisition. Positionnement : traiteur + restos + épicerie + pâtisserie + fromagerie. Gamme prix : 120-280€/pers. Réalisations : mariages prestige + réceptions diplomatiques Luxembourg. Signaux marketing : marque centenaire = patrimoine à valoriser. Siège : 14 rue du Curé L-1368 Luxembourg-Ville.","sources":"kaempff-kohler.lu | cc.lu"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Traiteurs premium / gastronomiques","entreprise":"Plaisir des Saveurs (PBO Gourmet)","ville":"Suisse","zone":"","dirigeant_principal":"Mickaël Brun (fondateur 2006) + Nicolas Perrenoud + Vincent Orain","portable_dirigeant":"","telephone":"+41 22 388 50 50","email":"","email_dirigeant":"info@plaisir-des-saveurs.ch","linkedin_dirigeant":"https://linkedin.com/in/mickael-brun-chef","site_web":"https://plaisir-des-saveurs.ch","note_priorite":"Moyenne","source":"fichier traiteurs premium enrichi","statut":"À contacter","data":{"note":"Né à l'École Hôtelière de Genève — approche gastronomique sur-mesure + agriculture raisonnée. Positionnement : Suisse romande (Genève). Gamme prix : 140-300 CHF/pers. Réalisations : mariages haut de gamme Genève + réceptions diplomatiques. Signaux marketing : trois associés actifs = comité direction réactif. Siège : Genève (École Hôtelière de Genève).","sources":"plaisir-des-saveurs.ch"}},

  // ─── PRIORITÉ BASSE ─────────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Traiteurs premium / gastronomiques","entreprise":"Savary Traiteur / Atelier By Savary","ville":"France","zone":"","dirigeant_principal":"Famille Savary (direction)","portable_dirigeant":"","telephone":"+33 5 56 50 33 33","email":"","email_dirigeant":"contact@savary-traiteur.fr","linkedin_dirigeant":"","site_web":"https://savary-traiteur.fr","note_priorite":"Basse","source":"fichier traiteurs premium enrichi","statut":"À contacter","data":{"note":"Brigade dirigée par chef formé maisons étoilées. Positionnement : Bordeaux Nouvelle-Aquitaine. Gamme prix : 80-200€/pers. Réalisations : mariages + événements pros région bordelaise. Signaux marketing : marque double (Savary + Atelier By Savary) ciblant pro/privé. Siège : Bordeaux (33).","sources":"savary-traiteur.fr"}}

].map(p => ({ qualification: '', date_relance: null, ne_plus_contacter: false, ...p }))
