// Cibles RÉELLES « Wedding planners / organisation de mariage » (INDESCALE).
// 18 cibles FR/CH/BE/LU/MC. Liste figée. Notes denses regroupant positionnement, gamme prix,
// réalisations, signaux marketing. 'n/a' laissé vide (jamais inventé).

let _c = 0
const cid = () => 'wp-' + (++_c)

export const WEDDING_PLANNERS_PROSPECTS = [
  // ─── PRIORITÉ HAUTE ────────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Wedding planners / organisation de mariage","entreprise":"Atout Coeur Wedding","ville":"France","zone":"","dirigeant_principal":"Stefania Magro","portable_dirigeant":"+33 6 07 38 02 90","telephone":"","email":"","email_dirigeant":"stefania@sm-consulting.fr","linkedin_dirigeant":"https://www.linkedin.com/in/stefania-magro-04b17057/","site_web":"https://www.atoutcoeurwedding.paris","note_priorite":"Haute","source":"fichier wedding planners enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct + 20 ans + presse Gala + clientèle internationale CSP+++. Positionnement : Wedding planner prestige n°1 sur-mesure 20+ ans. Gamme prix : honoraires 25-60k€ (mariages 150-400k€). Réalisations : mariages classiques Paris/Provence, presse Gala/Mon Carnet. Signaux marketing : Insta très actif + presse Gala/Mariages.net premium. Siège : 54 rue de Greneta, 75002 Paris.","sources":"atoutcoeurwedding.paris | LinkedIn"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Wedding planners / organisation de mariage","entreprise":"The Wedding Planners Monaco","ville":"Monaco","zone":"","dirigeant_principal":"Imène Hanafi (fondatrice 2015)","portable_dirigeant":"+33 6 64 97 55 27","telephone":"","email":"","email_dirigeant":"imene@theweddingplannersmonaco.com","linkedin_dirigeant":"https://www.instagram.com/theweddingplannersmonaco/","site_web":"https://www.theweddingplannersmonaco.com","note_priorite":"Haute","source":"fichier wedding planners enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct + Monaco/Riviera/Como + clientèle palaces = profil PRODIGIO parfait. Positionnement : luxury wedding designer Monaco Riviera Italie 10 ans. Gamme prix : honoraires 40-100k€ (mariages 250k€+). Réalisations : mariages villas Cap-Martin, palaces Monte-Carlo, Lake Como. Signaux marketing : Insta 35k+ followers + Monaco Directory + Wezoree. Siège : Monaco.","sources":"theweddingplannersmonaco.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Wedding planners / organisation de mariage","entreprise":"Sumptuous Events","ville":"France","zone":"","dirigeant_principal":"Jean-Charles Vaneck","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"efren@sumptuous-events.com","linkedin_dirigeant":"https://www.linkedin.com/in/jeancharlesvaneck/","site_web":"https://sumptuous-events.com","note_priorite":"Haute","source":"fichier wedding planners enrichi","statut":"À contacter","data":{"note":"🔥 Figure médiatique Paris + Vogue + Brides + Engage Summit. Positionnement : world-renowned luxury event designer City of Lights. Gamme prix : honoraires 30-80k€ (mariages 200k€+). Réalisations : mariages Opéra Garnier / châteaux IDF + Engage Summits Paris. Signaux marketing : presse Vogue/Brides international + DWP Insider. Siège : Paris 75. Couvre Paris / France / Italie / USA.","sources":"sumptuous-events.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Wedding planners / organisation de mariage","entreprise":"Luxury Events Agency by Sandrine Arnould","ville":"France","zone":"","dirigeant_principal":"Sandrine Arnould (25+ ans)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"https://www.linkedin.com/in/sandrine-arnould/","site_web":"https://luxury-events-agency.com","note_priorite":"Haute","source":"fichier wedding planners enrichi","statut":"À contacter","data":{"note":"🔥 Ticket le plus élevé du segment + même clientèle UHNW que chalet Mitja. Positionnement : destination WP luxe worldwide 25 ans Marrakech/Provence. Gamme prix : honoraires 50-150k€ (mariages 300k€-1M€). Réalisations : mariages Marrakech palais / Saint-Tropez villas / Maldives. Signaux marketing : Insta @luxury_events_agency + Threads + LinkedIn. Siège : Saint-Tropez (FR) + international. Couvre France / Italie / Grèce / Maroc / Maldives / Worldwide.","sources":"luxury-events-agency.com + LinkedIn"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Wedding planners / organisation de mariage","entreprise":"AAVA Wedding","ville":"France","zone":"","dirigeant_principal":"Chloé Atlan (cofondatrice 2002)","portable_dirigeant":"","telephone":"+33 4 93 43 73 79","email":"","email_dirigeant":"request@aavawedding.com","linkedin_dirigeant":"https://www.linkedin.com/in/chloé-atlan-a210b8201/","site_web":"https://www.aavawedding.com","note_priorite":"Haute","source":"fichier wedding planners enrichi","statut":"À contacter","data":{"note":"🔥 Pionnière Cannes + DWP Award Europe + clientèle internationale. Positionnement : première agence de WP de France (2002) DWP Award 2019 Best WP Europe. Gamme prix : honoraires 30-80k€ (mariages 200k€+). Réalisations : mariages Cap Ferrat / Saint-Tropez clientèle internationale. Signaux marketing : DWP Insider partner + French Wedding Style + Insta @aavawedding. Siège : 114 bd Carnot, 06110 Cannes.","sources":"aavawedding.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Wedding planners / organisation de mariage","entreprise":"Alejandra Poupel Events","ville":"France","zone":"","dirigeant_principal":"Alejandra Poupel","portable_dirigeant":"","telephone":"+33 1 40 81 03 37","email":"","email_dirigeant":"contact@alejandrap.com","linkedin_dirigeant":"","site_web":"https://alejandrapoupel.com","note_priorite":"Haute","source":"fichier wedding planners enrichi","statut":"À contacter","data":{"note":"Wedding planner luxe Europe internationale 5 langues. Positionnement : Paris / Europe. Gamme prix : honoraires 40-100k€ (mariages 300k€+). Réalisations : Opéra Garnier, Vaux-le-Vicomte, Engage 23. Signaux marketing : Vogue / NYT / Grace Ormonde / WedLuxe. Siège : Paris 75.","sources":"alejandrapoupel.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Wedding planners / organisation de mariage","entreprise":"By Mademoiselle C","ville":"France","zone":"","dirigeant_principal":"Céline & Marjorie (duo fondatrices, 2010)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"bonjour@bymademoisellec.com","linkedin_dirigeant":"","site_web":"https://www.bymademoisellec.com","note_priorite":"Haute","source":"fichier wedding planners enrichi","statut":"À contacter","data":{"note":"Duo féminin Provence depuis 2010 élégance naturelle. Positionnement : Provence / Côte d'Azur / Corse. Gamme prix : honoraires 20-50k€ (mariages 100-250k€). Réalisations : mariages domaines Provence + châteaux Corse. Signaux marketing : référencement Vogue Wedding partners + presse Madame C. Siège : Provence.","sources":"bymademoisellec.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Wedding planners / organisation de mariage","entreprise":"Samantha Bottelier Events","ville":"France","zone":"","dirigeant_principal":"Samantha Bottelier","portable_dirigeant":"+33 6 20 11 47 96","telephone":"","email":"","email_dirigeant":"contact@samanthabottelierevents.com","linkedin_dirigeant":"https://www.linkedin.com/in/samantha-bottelier-88985766/","site_web":"https://www.samanthabottelierevents.com","note_priorite":"Haute","source":"fichier wedding planners enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct + bespoke design. Positionnement : luxury & bespoke wedding planner designer Paris. Gamme prix : honoraires 20-50k€ (mariages 100-250k€). Réalisations : mariage intime Shangri-La Paris + Provence châteaux. Signaux marketing : Insta @samanthabottelierevents + Wedding Chicks Wedding Wire. Siège : Paris 75.","sources":"samanthabottelierevents.com"}},

  // ─── PRIORITÉ MOYENNE ──────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Wedding planners / organisation de mariage","entreprise":"Elodie Villemus Weddings","ville":"France","zone":"","dirigeant_principal":"Elodie Villemus (groupe Label Emotion)","portable_dirigeant":"","telephone":"04 90 33 17 96","email":"","email_dirigeant":"info@elodievillemus.com","linkedin_dirigeant":"https://fr.linkedin.com/in/elodie-villemus-1572562aa","site_web":"https://www.elodievillemus.com","note_priorite":"Moyenne","source":"fichier wedding planners enrichi","statut":"À contacter","data":{"note":"Notoriété TV (Top Chef du mariage) + groupe multi-sites France/Europe. Positionnement : France / Provence / Cannes / Paris / Genève / Londres. Gamme prix : honoraires 20-50k€ (mariages 80-250k€). Réalisations : mariages Cannes/Provence/Genève + programme TV exposure. Signaux marketing : notoriété TV + Insta groupe + Label Emotion. Siège : 18 allée du Fenouil, 84250 Le Thor (Provence).","sources":"elodievillemus.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Wedding planners / organisation de mariage","entreprise":"Justine Huette","ville":"France","zone":"","dirigeant_principal":"Justine Huette (depuis 2016)","portable_dirigeant":"06 62 21 16 83","telephone":"","email":"","email_dirigeant":"info@justinehuette.fr","linkedin_dirigeant":"https://fr.linkedin.com/in/justine-huette-wedding-planner-b49351101","site_web":"https://justinehuette.fr","note_priorite":"Moyenne","source":"fichier wedding planners enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct + limite 8-10 mariages/an (besoin pipe ultra-qualifié). Positionnement : luxury WP Paris IDF. Gamme prix : honoraires 15-35k€ (mariages 80-200k€). Réalisations : mariages châteaux IDF, mentions site/Insta. Signaux marketing : Insta @justinehuette_weddingplanner + presse. Siège : Paris/IDF (Moisenay 77).","sources":"justinehuette.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Wedding planners / organisation de mariage","entreprise":"Héra et Lutèce","ville":"France","zone":"","dirigeant_principal":"Fiona Sand (fondatrice 2010)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"bonjour@heralutece.com","linkedin_dirigeant":"","site_web":"https://heralutece.com","note_priorite":"Moyenne","source":"fichier wedding planners enrichi","statut":"À contacter","data":{"note":"Genuine hospitality, understated luxury. Positionnement : planning & design studio Paris / France / International. Gamme prix : honoraires 20-50k€ (mariages 100-300k€). Réalisations : mariages Paris/châteaux + elopements internationaux. Signaux marketing : WeddingWire 18 reviews + portfolio films wedding. Siège : Paris.","sources":"heralutece.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Wedding planners / organisation de mariage","entreprise":"Organsa Wedding Planner","ville":"France","zone":"","dirigeant_principal":"Sandrine Rosette (fondatrice 2010)","portable_dirigeant":"+33 6 48 46 18 78","telephone":"","email":"","email_dirigeant":"contact@organsa-event.com","linkedin_dirigeant":"https://www.linkedin.com/in/sandrinerosetteweddingplanner/","site_web":"https://organsa-event.com","note_priorite":"Moyenne","source":"fichier wedding planners enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct + 500+ mariages destination + clientèle US. Positionnement : curated & elevated weddings clientèle US. Gamme prix : honoraires 25-60k€ (mariages 150-300k€). Réalisations : 500+ mariages destination Europe / US clients. Signaux marketing : site FR/EN + WeddingWire + LinkedIn actif. Siège : Paris.","sources":"organsa-event.com"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Wedding planners / organisation de mariage","entreprise":"Jules et moi","ville":"France","zone":"","dirigeant_principal":"Catherine Dondina (fondatrice 2007)","portable_dirigeant":"","telephone":"01 47 03 35 06","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://julesetmoi.fr","note_priorite":"Moyenne","source":"fichier wedding planners enrichi","statut":"À contacter","data":{"note":"Agence WP référence France élue agence de l'année 2026 Mariages.net. Positionnement : Paris / France / International (franchise). Gamme prix : honoraires 15-40k€ (mariages 80-200k€). Réalisations : 600+ mariages organisés réseau franchise multi-villes. Signaux marketing : Mariages.net Award + formation + franchise nationale. Siège : 8 rue Greffulhe, 75008 Paris (+ siège 56 rue Marg. Rochechouart 75009).","sources":"julesetmoi.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Wedding planners / organisation de mariage","entreprise":"Wonder Events","ville":"Suisse","zone":"","dirigeant_principal":"Alice Salini-Nessi (fondatrice)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"alice@wonderevents.ch","linkedin_dirigeant":"https://www.linkedin.com/in/alice-nessi-9b10b88a/","site_web":"https://www.wonderevents.ch","note_priorite":"Moyenne","source":"fichier wedding planners enrichi","statut":"À contacter","data":{"note":"Luxury WP studio Suisse + Lake Como background fashion/luxe. Positionnement : Suisse (Tessin) / Lake Como / Toscane / Europe. Gamme prix : honoraires CHF 25-60k (mariages 150-300k€). Réalisations : mariages Lake Como / Toscane / Suisse italienne. Signaux marketing : Insta + Moneyhouse + portfolio fashion-led. Siège : Via Lüèra 10, 6883 Novazzano (CH).","sources":"wonderevents.ch"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Wedding planners / organisation de mariage","entreprise":"LuxWedding","ville":"Luxembourg","zone":"","dirigeant_principal":"Lynn Weistroffer (depuis 2011)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"https://www.linkedin.com/in/lynn-weistroffer-a0373930/","site_web":"https://luxwedding.lu","note_priorite":"Moyenne","source":"fichier wedding planners enrichi","statut":"À contacter","data":{"note":"Fine-art destination WP Luxembourg + Europe. Positionnement : Luxembourg / Venise / Grèce / Italie / Sud France. Gamme prix : honoraires 20-50k€ (mariages 100-250k€). Réalisations : mariages destination Venise/Grèce/Italie + Luxembourg châteaux. Signaux marketing : Insta @luxwedding.lu + @lynn_luxwedding + editus.lu. Siège : Crauthem (Luxembourg).","sources":"luxwedding.lu"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Wedding planners / organisation de mariage","entreprise":"Cassandra Albertini Wedding Planner","ville":"France","zone":"","dirigeant_principal":"Cassandra Albertini","portable_dirigeant":"+33 6 14 19 15 43","telephone":"","email":"","email_dirigeant":"contact@cassandraweddingplanner.fr","linkedin_dirigeant":"https://www.linkedin.com/in/cassandra-albertini/","site_web":"https://www.cassandraweddingplanner.fr","note_priorite":"Moyenne","source":"fichier wedding planners enrichi","statut":"À contacter","data":{"note":"🔥 Portable direct + élite WP design bold + couverture Grand Est + LU + BE. Positionnement : élite WP mariages d'exception design bold. Gamme prix : honoraires 15-35k€ (mariages 80-180k€). Réalisations : mariages Grand Est / Luxembourg / IDF haut de gamme. Signaux marketing : Insta @cassandra_weddingplanner + LinkedIn élite. Siège : 10A boucle des jardins du triangle, 57290 Fameck.","sources":"cassandraweddingplanner.fr"}},

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Wedding planners / organisation de mariage","entreprise":"Lucy Till French Weddings","ville":"France","zone":"","dirigeant_principal":"Rhiann Janak (CEO actuelle, fondé par Lucy Till 2005)","portable_dirigeant":"","telephone":"","email":"","email_dirigeant":"","linkedin_dirigeant":"","site_web":"https://www.lucytillfrenchweddings.com","note_priorite":"Moyenne","source":"fichier wedding planners enrichi","statut":"À contacter","data":{"note":"Luxury destination WP English-speaking couples 20 ans. Positionnement : Provence / French Riviera / Alpes / Lake Como / Paris. Gamme prix : honoraires 25-60k€ (mariages 150-300k€). Réalisations : mariages domaines Luberon / Riviera / Lake Como / Tuscany. Signaux marketing : référencée frenchweddings.net + AngloInfo + Insta. Siège : Aix-en-Provence.","sources":"lucytillfrenchweddings.com"}},

  // ─── PRIORITÉ BASSE ─────────────────────────────────────────────────────────

  {id: cid(),"app":"indescale","secteur_id":"evenementiel","categorie":"Wedding planners / organisation de mariage","entreprise":"Catherine Vionnet — Your Authentic Wedding","ville":"Suisse","zone":"","dirigeant_principal":"Catherine Vionnet","portable_dirigeant":"+41 79 430 90 34","telephone":"","email":"","email_dirigeant":"hello@yourauthenticwedding.ch","linkedin_dirigeant":"","site_web":"https://yourauthenticwedding.ch","note_priorite":"Basse","source":"fichier wedding planners enrichi","statut":"À contacter","data":{"note":"⚠️ Ticket plus bas que cible PRODIGIO mais profil propre. Positionnement : WP certifiée Swiss Wedding Masterclass mariages élégants Suisse + Sud France. Gamme prix : CHF 8-15k coordination / 2k coaching. Réalisations : mariages chalets / domaines vaudois et genevois. Signaux marketing : site bilingue FR/EN + Insta + Yelp. Siège : Lausanne (VD).","sources":"yourauthenticwedding.ch"}}

].map(p => ({ qualification: '', date_relance: null, ne_plus_contacter: false, ...p }))
