-- Seed INDESCALE — catégorie « Home cinéma / salle de projection privée » (15 cibles enrichies).
-- À exécuter UNE FOIS dans Supabase → SQL Editor, après schema.sql. Idempotent par (app, categorie, entreprise).
create unique index if not exists prospects_cine_uniq
  on prospects (app, categorie, entreprise)
  where app = 'indescale' and place_id is null;

insert into prospects (app, secteur_id, categorie, ville, entreprise, telephone, portable_dirigeant, email_dirigeant, dirigeant_principal, linkedin_dirigeant, note_priorite, source, statut, data)
values
  ('indescale', 'experience-domicile', 'Home cinéma / salle de projection privée', 'France', 'Ocinema', '03 44 66 30 99', '+33 6 25 47 16 62', 'lodoick.dlfd@ocinema.com', 'Lodoïck de la Forest Divonne', 'https://www.linkedin.com/in/lodoïck-de-la-forest-divonne-a94205155/', 'Haute', 'fichier cinéma enrichi', 'À contacter', '{"note":"🔥 CIBLE LA PLUS QUALIFIÉE — portable + email perso direct confirmés via LinkedIn About + Pappers","sources":"https://www.linkedin.com/in/lodoïck-de-la-forest-divonne-a94205155/ | https://www.pappers.fr/entreprise/ocinema-440256485"}'::jsonb),
  ('indescale', 'experience-domicile', 'Home cinéma / salle de projection privée', 'Belgique', 'AV Architects', '+32 81 84 10 11', '+32 477 52 54 54', 'info@avarchitects.be', 'Lionel Pierrard / Kevin Brouwet', 'https://be.linkedin.com/company/av-architects1', 'Haute', 'fichier cinéma enrichi', 'À contacter', '{"note":"🔥 Mobile belge 0477 (= 06 en BE) — ligne directe agence — email perso Pierrard/Brouwet probable prenom@avarchitects.be (à confirmer LinkedIn)","sources":"https://www.electriciens.pro/gembloux/audio-visual-architects/ | https://be.linkedin.com/company/av-architects1"}'::jsonb),
  ('indescale', 'experience-domicile', 'Home cinéma / salle de projection privée', 'Luxembourg', 'Cinemotion', '+352 26 67 12 14', '+352 661 15 67 15', 'contact@cinemotion.biz', 'Richard Czapla', 'https://lu.linkedin.com/in/richard-czapla-20406990', 'Haute', 'fichier cinéma enrichi', 'À contacter', '{"note":"🔥 Portable Luxembourg direct — alias HCFR \"moudugnou\" confirme — CIBLE TRÈS QUALIFIÉE","sources":"https://lu.linkedin.com/in/richard-czapla-20406990 | https://www.yellow.lu/en/yellow-pages/6051520-cinemotion-ellange"}'::jsonb),
  ('indescale', 'experience-domicile', 'Home cinéma / salle de projection privée', 'France', 'Votre Cinéma', '09 62 03 31 24', NULL, 'lionel@votrecinema.fr', 'Lionel Lavaure', NULL, 'Moyenne', 'fichier cinéma enrichi', 'À contacter', '{"note":"Email direct format prenom@votrecinema.fr (100%) — fixe 09 (non-géo) = standard — portable perso non publié — LinkedIn DM https://www.linkedin.com/in/lionel-lavaure-245b70122/","sources":"https://rocketreach.co/votre-cinema-email-format_b7d58190c0e121db | https://www.houzz.fr/pro/votrecinema/"}'::jsonb),
  ('indescale', 'experience-domicile', 'Home cinéma / salle de projection privée', 'France', 'ASC Audiovisuel', '04 92 28 30 00', NULL, 'eric@asc-france.com', 'Eric Farnet', 'https://www.linkedin.com/in/eric-farnet-6b801823/', 'Moyenne', 'fichier cinéma enrichi', 'À contacter', '{"note":"Email perso direct (eric@) confirmé via article presse — LinkedIn actif — portable perso à demander via standard","sources":"https://www.webtimemedias.com/article/mougins-eric-farnet-le-petit-poucet-qui-defie-orange-sur-la-fibre | https://www.linkedin.com/in/eric-farnet-6b801823/"}'::jsonb),
  ('indescale', 'experience-domicile', 'Home cinéma / salle de projection privée', 'France', 'AVM Cinesound', '04 92 18 10 15', NULL, 'patrick.havy@avm-cinesound.com', 'Patrick Havy', NULL, 'Moyenne', 'fichier cinéma enrichi', 'À contacter', '{"note":"Email perso confirmé ContactOut + Viadeo — Membre BNI Cagnes Baie des Anges — portable accessible via inscription BNI","sources":"https://contactout.com/patrick-havy-70431 | https://bni-alpesmaritimes.fr/cagnes-baie-des-anges/fr/memberdetails?encryptedMemberId=QNLk2TKMLNaQmJ83hKsHpw%3D%3D&name=Patrick+HAVY"}'::jsonb),
  ('indescale', 'experience-domicile', 'Home cinéma / salle de projection privée', 'Monaco', 'Audio Feeling International (AFI MC)', '+377 92 05 75 65', NULL, 'afimc@monaco377.com', 'Jean-François Fabre', NULL, 'Moyenne', 'fichier cinéma enrichi', 'À contacter', '{"note":"Dirigeant = JF Fabre confirmé. Monaco = portable opaque sectoriellement. Email = boîte directe (showroom 22 Quai Jean-Charles Rey)","sources":"https://www.afimc.com/mentions-legales | https://www.afimc.com/contact"}'::jsonb),
  ('indescale', 'experience-domicile', 'Home cinéma / salle de projection privée', 'Monaco', 'THC Monaco', '+377 97 70 70 42', NULL, 'pdm@thcmonaco.com', 'pdm + jlg (initiales DAF + Dir Projets)', NULL, 'Moyenne', 'fichier cinéma enrichi', 'À contacter', '{"note":"2 emails directs initiales (pdm = DAF / jlg = Dir Projets) — Monaco extrêmement opaque — visite physique 2 Bd Jardin Exotique seule solution pour identifier","sources":"https://thcmonaco.com/en/ | https://www.monte-carlo.mc/en/directory/shopping/household-appliances-audiovisual/thc-total-home-control/"}'::jsonb),
  ('indescale', 'experience-domicile', 'Home cinéma / salle de projection privée', 'Suisse', 'Video Systems SA', '+41 22 329 22 88', NULL, NULL, 'Eric Rabischung', 'https://fr.linkedin.com/in/eric-rabischung-0024ab52', 'Moyenne', 'fichier cinéma enrichi', 'À contacter', '{"note":"Mentions légales confirment Rabischung comme responsable — adresse 5 route des Jeunes 1227 Genève — LinkedIn DM recommandé","sources":"https://www.vidsys.ch/mentions-legales | https://fr.linkedin.com/in/eric-rabischung-0024ab52"}'::jsonb),
  ('indescale', 'experience-domicile', 'Home cinéma / salle de projection privée', 'Suisse', 'Digistore SA', '+41 22 329 22 88', NULL, 'digistore@digistore.ch', 'Henri Emmanuel Feige (administrateur unique)', NULL, 'Haute', 'fichier cinéma enrichi', 'À contacter', '{"note":"✅ NOUVEAU dirigeant identifié = Henri Emmanuel Feige via Moneyhouse — ex-président devenu administrateur unique — passer standard pour transfert","sources":"https://www.moneyhouse.ch/en/company/digistore-sa-12050265021 | https://digistore.ch/nous-contacter"}'::jsonb),
  ('indescale', 'experience-domicile', 'Home cinéma / salle de projection privée', 'Belgique', 'Cinephil SRL', '+32 81 22 41 49', NULL, 'info@cinephil.be', 'Direction non identifiée', NULL, 'Moyenne', 'fichier cinéma enrichi', 'À contacter', '{"note":"SRL déc. 2002 BE0479027372 — 5.9 ETP — dirigeant non publié sur Companyweb gratuit — 75 avis Google 4.7/5 — visite showroom 30 rue Rogier 5000 Namur recommandée","sources":"https://www.companyweb.be/en/0479027372/cine-phil | https://www.cinephil.be/contact.html"}'::jsonb),
  ('indescale', 'experience-domicile', 'Home cinéma / salle de projection privée', 'France', 'Cine Install Services', NULL, NULL, NULL, 'Direction non identifiée (ex-SAE)', NULL, 'Moyenne', 'fichier cinéma enrichi', 'À contacter', '{"note":"Aucun nom dirigeant publié — équipe d''anciens SAE depuis 2004 — non trouvé Pappers/Societe.com/LinkedIn avec ces termes — appel direct standard ou LinkedIn search employés","sources":"https://www.cine-install.fr/ | http://www.cine-install.fr/contactez-nous"}'::jsonb),
  ('indescale', 'experience-domicile', 'Home cinéma / salle de projection privée', 'France', 'Custom Cinéma', NULL, NULL, 'contact@custom-cinema.fr', 'Gil Pétuaud-Létang', 'https://fr.linkedin.com/in/gil-petuaud-letang-25622934', 'Moyenne', 'fichier cinéma enrichi', 'À contacter', '{"note":"Mentions légales = SAS HAT 4 rue Massenet 33680 LACANAU — siège réel Lacanau pas Bouliac — portable absent Houzz/Pappers/LinkedIn — appeler standard ou LinkedIn DM","sources":"https://custom-cinema.fr/custom-cinema-une-entreprise-a-votre-service/mentions-legales/ | https://fr.linkedin.com/in/gil-petuaud-letang-25622934"}'::jsonb),
  ('indescale', 'experience-domicile', 'Home cinéma / salle de projection privée', 'France', 'L''Audiovidéiste', NULL, NULL, 't.lamouche@laudiovideiste.fr', 'Thomas Lamouche', 'https://www.linkedin.com/in/thomas-lamouche-771913153/', 'Haute', 'fichier cinéma enrichi', 'À contacter', '{"note":"✅ NOUVEAU dirigeant identifié = Thomas Lamouche — Gérant SARL créée sept 2018 (SIREN 842475196) Valencin 38540 — email direct confirmé Societe.com","sources":"https://www.societe.com/manager/Thomas.LAMOUCHE.yen3_C7RUsu.html | https://www.linkedin.com/in/thomas-lamouche-771913153/"}'::jsonb),
  ('indescale', 'experience-domicile', 'Home cinéma / salle de projection privée', 'France', 'Mon Ciné Privé', '04 84 88 53 28', NULL, NULL, 'Didier Autric', 'https://www.linkedin.com/in/didier-autric/', 'Moyenne', 'fichier cinéma enrichi', 'À contacter', '{"note":"Gérant A DYNAMIC HOME CINEMA (SIRET 43359877800044) — adresse réelle Rue Sainte 13000 Marseille — chaîne YouTube Didier AUTRIC active — LinkedIn DM ou formulaire","sources":"https://www.linkedin.com/in/didier-autric/ | https://www.moncineprive.com/mentions-legales"}'::jsonb)
on conflict do nothing;
